README.md

just a little proofreading in the README

Typo: problems problems

---

client/www/lib/auth.ts
client/www/pages/dash/index.tsx
server/src/instant/dash/routes.clj

Deletes the auth token on logout and unhides the logout button while we work on the hamburger.

Deletes auth token on logout

---

README.md
client/www/pages/index.tsx

We got some HN feedback, that people were confused where `useQuery`, `transact`, `tx`, et al were coming from in our 10 line example. 
I went ahead and made it more complete. This includes: 
- the import
- the init
@dwwoelfel @markyfyi @reichert621 @nezaj

[Examples] Make the Chat example more complete

---

server/src/instant/dash/admin.clj
server/src/instant/dash/routes.clj
server/src/instant/stripe.clj

Shows a list of paid apps, with how much they're paying, how long they've been paying and their usage.

Add admin page that shows paid apps

---

client/www/pages/intern/paid.tsx

Followup to https://github.com/instantdb/instant/pull/12, forgot to check in the /intern/paid page.

Add missing paid page

---

client/www/_posts/db_browser.md
client/www/_posts/next_firebase.md
client/www/pages/docs/schema.md
client/www/pages/docs/start-rn.md

An HN user pointed out a few typos: 
https://triplechecker.com/s/yyNfc1/instantdb.com?v=wh8Jr
I went ahead and fixed it.

[typos] fix a few typos

---

server/src/instant/db/cel.clj

This fixes a bug where `type(data.property)` would throw an exception when the property was an integer.
cel-java doesn't know how to determine the type of integers, it only knows longs. So we convert integers to longs when we retrieve them from the map.
Here's where the type check happens: https://github.com/google/cel-java/blob/dae82c6d10114bb1da643203569f90a757c6c5e6/runtime/src/main/java/dev/cel/runtime/StandardTypeResolver.java#L73-L105
As a bonus, it also fixes checking if something is false. Previously evaluating `data.bool_prop == false` would return false if it got `data={bool_prop: false}` because the `or` would return `NULL_VALUE` on false.

Fix `type(data.property)` in cel

---

client/www/pages/tutorial.tsx

Monaco internals were throwing, not entirely sure why, but giving each model a path resolved the issue.  Also, DRY'd up some code.

Fix tutorial Monaco model error

---

client/packages/cli/index.js
client/www/lib/auth.ts
client/www/pages/dash/index.tsx
server/src/instant/dash/routes.clj
server/src/instant/model/instant_cli_login.clj

Adds an additional layer of security by prompting the user to allow/deny CLI auth in the browser.

CLI auth confirmation step

---

client/sandbox/cli-nodejs/instant.schema.ts
server/src/instant/dash/routes.clj

We forgot to update the backend after renaming all of the keys! 😱

[cli][schema][attrs] Fix parsing of user schema defs into instant schema

---

client/www/components/dash/Perms.tsx
client/www/components/ui.tsx

Cmd+S to save, more flexible parsing:
https://github.com/user-attachments/assets/5f7727f2-0abb-41db-b0d3-f5d692019d23

Allow cmd+S to save rules.json, use JSON5 parser for more flexibility

---

client/sandbox/react-nextjs/pages/patterns/manage-users.tsx
client/sandbox/react-nextjs/pages/patterns/split-attributes.tsx
client/www/data/docsNavigation.js
client/www/pages/docs/patterns.md

Starting up a pattern page to give guidance on common user asks!
My thinking is instead of having big code blocks in the docs, we would link to full examples in github
[x] Add a pattern for public app id + permissions. [Discord](https://discord.com/channels/1031957483243188235/1276846435589034036)
[x] Add a pattern for restricting attr creation on the fly. [Discord](https://discord.com/channels/1031957483243188235/1276525050874433568)
[x] Add a patten for managing users. [Discord](https://discord.com/channels/1031957483243188235/1276928974307725342)
[x] Add a pattern for loading heavy content via links in the docs. [Discord](https://discord.com/channels/1031957483243188235/1148284450992574535/1276617379249393745) 
[Preview Link](https://instant-www-git-doc-patterns-jsv.vercel.app/docs/patt …

[Docs] Start patterns page

---

client/www/data/docsNavigation.js
client/www/pages/docs/showcase.md

Thought it might be nice to put together a little showcase page. Thoughts?
[Preview](https://instant-www-git-add-example-apps-page-jsv.vercel.app/docs/showcase)

[Docs] Add showcase page

---

client/README.md

Some users had questions about how to do this so adding some steps. h/t to fivestones from [discord](https://discord.com/channels/1031957483243188235/1031957483826204705/1278654888674328636)

[README] Add instructions for running a local app

---

client/www/pages/docs/instaml.md

h/t to Britannio for pointing this out. [Discord](https://discord.com/channels/1031957483243188235/1276693221254234145/1278810917315940353)

[Docs] Update instaml docs

---

client/www/components/ui.tsx
client/www/pages/dash/index.tsx

Adds a docs link to the sidebar, which will open the docs in a new tab with the current app pre-selected.

Docs link in sidebar

---

client/packages/core/__example__/standalone.esm.html
client/packages/core/__example__/standalone.umd.html
client/packages/core/package.json
client/packages/core/src/index.ts
client/packages/core/vite.config.ts
client/packages/react/__example__/standalone.esm.html
client/packages/react/__example__/standalone.umd.html
client/packages/react/package.json
client/packages/react/src/index.ts
client/packages/react/vite.config.ts
client/pnpm-lock.yaml

Uses Vite's library mode to bundle core and react libs :)

Script tag-friendly standalone builds

---

client/www/pages/intern/storage.tsx
server/src/instant/dash/admin.clj
server/src/instant/dash/routes.clj
server/src/instant/model/app.clj
server/src/instant/storage/s3.clj
server/src/instant/util/storage.clj

Adds internal metrics to track storage usage across apps.

Storage admin metrics

---

server/src/instant/dash/admin.clj

Orders subscriptions by when they started, newest first.

Show newest subscriptions first in intern/paid

---

client/www/pages/docs/patterns.md

Adds a pattern for rate limiting. [Discord](https://discord.com/channels/1031957483243188235/1278589421700120608/1278761861915082873)
[Preview docs](https://instant-www-git-limit-pattern-jsv.vercel.app/docs/patterns#setting-limits-via-permissions)

[Docs] Add limit pattern

---

client/www/pages/docs/start-rn.md

Deleted `Linking` import which is not used anywhere in the component.

Delete unused import

---

client/www/lib/url.tsx
client/www/pages/intern/top.jsx
server/src/instant/dash/admin.clj
server/src/instant/dash/routes.clj
server/src/instant/util/int.clj
server/src/instant/util/number.clj

The top page is getting slower and slower because of pulling too much historical data. Feels like the most interesting data is in the recent week.
To allow for more flexibility, you can use a query param to alter the number of days. E.g. adding `?n=10` to the url will fetch 10 days worth of data. The default is 7.

[Intern] Faster top

---

client/www/pages/docs/instaml.md

Was using batch transact for testing and realized the pattern on the docs missed adding the last batch

[Docs] Update batch pattern

---

client/www/components/DocsPage.jsx
client/www/components/docs/Layout.jsx

Memoizes various deps to prevent rerenders from broking scroll state

Improve docs mini nav

---

client/www/pages/docs/auth/magic-codes.md

A user asked how to sign out from the client in the discord. We have this method but I realize we didn't explicitly talk about it in our docs (we only talk about it from the server)

[Docs] Add client side sign out

---

server/refinery/config.yaml

Reduce log level from info to warn

Reduce the log volume that refinery produces

---

client/packages/core/src/Reactor.js

Fixes a bug where the user would see stale data if a mutation times out. We weren't notifying the queries that they needed to re-evaluate without the mutation after the timeout.
Refactors `finishTransaction` a bit so that you just pass the status instead of passing the status and whether it was an error. We infer whether it was an error from the status. 
Moves error handling for a failed mutation to its own method so that we can use it whether we failed for a timeout or failed for an error.

Notify subs when transaction times out

---

.github/workflows/js.yml

Vercel only accepts `a-z` `0-9` and `-`

Replace bad characters in domain alias

---

README.md

Adds YourKit to the readme. 
It's a nice, easy-to-use java profiler that can profile both memory and cpu in a running JVM.
If we add their logo and link to their site, they'll give us a free license.

Add Yourkit to the readme

---

client/packages/admin/package.json
client/packages/cli/package.json
client/packages/core/package.json
client/packages/react-native/package.json
client/packages/react/package.json

My release script didn't bump versions in package.json files.  Fixing.

Fix versions

---

client/www/components/dash/Sandbox.tsx

[www][sandbox] Log query and transaction errors in the output pane

---

client/sandbox/react-nextjs/pages/patterns/manage-users.tsx
client/sandbox/react-nextjs/pages/play/pagination.tsx
client/sandbox/react-nextjs/pages/play/stress.tsx

We never build sandbox packages in CI, but when I ran a `pnpm build` from `client`, it complained with some type errors.  This fixes those.

Fix types in sandbox

---

server/src/instant/config.clj
server/src/instant/db/permissioned_transaction.clj

Seeing a lot of connection get caught on this. Removing temporarily to reduce contention on Aurora.

[experiment] increase conn-count and remove xact-lock

---

client/www/pages/dash/index.tsx

Saves the last viewed app in LocalStorage so that we can show it when a user returns to the dash.

[www][dash] save last viewed app

---

client/www/lib/auth.ts
client/www/pages/dash/index.tsx

Removes v0 of CLI auth where we tried hitting an ephemeral localhost server.

Remove old CLI logi client-side flow

---

client/packages/admin/src/index.ts
client/packages/react-native/src/index.ts
client/packages/react/src/index.ts

I forgot to export updated schema types from admin

admin types export

---

client/packages/cli/index.js

`instant-cli -V` that reads from package.json

Support CLI version

---

client/www/pages/404.tsx

[dekuma](https://discord.com/channels/1031957483243188235/1148284450992574535/1286037265801281567) pointed out Google indexes some out of date docs, figured it would be nice to add a redirect!
@stopachka @dwwoelfel @markyfyi

[WWW] Add redirect on 404

---

client/www/pages/_app.tsx
client/www/pages/index.tsx

Context: Folks sometimes get confused w/ Instant, they think we're meant only for Figma/Notion apps. They think multiplayer/offline are nice-to-haves and not what they actually need for their new project.
We want to lean into Instant being a tool for productively building modern applications
**Before**
**After**

[WWW] Update two sentence

---

client/packages/cli/index.js
client/www/pages/docs/cli.md

Support svelte public env variables. [Discord](https://discord.com/channels/1031957483243188235/1287467897660116993/1287805939470176297)

[instant-cli] Support svelte public env

---

client/packages/admin/src/index.ts
client/packages/react-native/src/index.ts
client/packages/react/src/init.ts
client/packages/react/src/useQuery.ts
client/www/pages/_devtool/index.tsx
client/www/pages/dash/index.tsx

I just checked all of our `.d.ts` files and found a handful of similar type errors.
cc @stopachka

Fix errors in generated d.ts files in the rest of our packages

---

server/test/instant/admin/routes_test.clj

Realized I should also include a test for #270 to help get notified of a future regression

[Admin] Add test for ignoring id

---

client/www/pages/docs/init.md

[Docs] Update init grammar and copy

---

server/src/instant/db/cel.clj
server/test/instant/db/cel_test.clj

[One of our users](https://discord.com/channels/1031957483243188235/1148284450992574535/1290297082523029625) pointed out we don't have standard CEL macros enabled. This seemed like an easy lift so adding it in here!

[CEL] Add standard macros to CEL

---

client/sandbox/react-nextjs/pages/play/strong-todos.tsx
client/www/pages/docs/strong-init.md

Documenting InstantEntity and InstantSchemaDatabase

More docs for SI types

---

client/www/_posts/seed.md
client/www/components/marketingUi.tsx
client/www/pages/hiring.tsx
client/www/pages/index.tsx

* Adds hiring banner to the front page
* Adds hiring to nav and footer
* Adds hiring page [Preview link](https://instant-www-js-hiring-jsv.vercel.app/hiring)
* Adds seed page [Preview link](https://instant-www-js-hiring-jsv.vercel.app/essays/seed)
**Banner**

[WWW] Add hiring page

---

client/packages/admin/src/index.ts
client/sandbox/admin-sdk-express/src/index.ts
client/www/pages/docs/backend.md
server/src/instant/admin/routes.clj
server/src/instant/model/app_user.clj
server/src/instant/model/instant_user.clj

Users who owned their auth email stack were asking for a magic code helper to integrate Instant into their emails.

Admin "gen magic code" method

---

client/www/components/dash/explorer/EditNamespaceDialog.tsx

Allow users to delete backward links from the users edit namespace form.

Allow deleting refs from the `users` schema form

---

client/www/pages/_app.tsx

[typo] databse

---

client/www/_posts/seed.md

Thought it would be nice to add the thumbnail to the essay

[Essay] Add seed thumbnail to post

---

server/src/instant/core.clj

Sends metrics with gauges about how many connections and requests are open on the server.

Keep track of how many connections we have

---

server/src/instant/core.clj
server/src/instant/dash/routes.clj
server/src/instant/flags.clj
server/src/instant/stripe.clj

We can use this to help pro customers enable some other apps. 
@nezaj @dwwoelfel

[small] allow promo codes for some emails

---

client/www/pages/docs/users.md

Quick PR to fix some grammar issues on the managing users docs

[Docs] Grammar fixes to users docs

---

client/www/components/dash/Sandbox.tsx
server/src/instant/db/permissioned_transaction.clj

Shows attr checks in the sandbox:

Show attr checks in permissions

---

server/src/instant/lib/ring/websocket.clj
server/src/instant/reactive/session.clj

I'm curious if long ping times will help us identify sessions that are unhealthy and if we could use this as a signal that the websocket connection should be closed so that it can reconnect.
We set the last ping time every time we ping and then we set the ping latency when we get a pong. This isn't perfect because we don't have a way to correlate a ping with a pong, but it should still be roughly accurate.
We send the ping-latency along with the other event metrics in `receive-worker/handle-event`.

Track the time it takes a websocket to respond to our ping

---

client/packages/core/__tests__/src/instaml.test.js
server/src/instant/admin/model.clj
server/test/instant/admin/routes_test.clj

There was a typo and it was looking at the fwd-ident when it meant to look at the rev-ident.

Fix optimistic attrs for lookups on admin model

---

server/src/instant/flags.clj

Should have been `:disabled?` instead of `:disabled`

Fix hazelcast-disabled? flag

---

client/www/pages/pricing/index.tsx

For now we'll pause inquires for enterprise plans to focus on Instant Core !

[WWW] Disable enterprise

---

client/www/components/marketingUi.tsx

[WWW] Add terms to footer

---

client/www/pages/hiring.tsx

User reported this typo : )
@nezaj

[grammar] life time -> lifetime

---

server/src/instant/util/tracer.clj

[Now that all our sampling is happening in refinery](https://github.com/instantdb/instant/pull/378), we can remove our 'poor man's sampler! 

Remove sampling inside clojure

---

server/refinery/rules.yaml
server/src/instant/reactive/ephemeral.clj

I forgot about refresh-rooms 😳. Made sure to include it in our refinery config, we we sample it at a 1%

add refresh-rooms to refinery

---

server/refinery/rules.yaml

Seems to get us to our normal rate.

Just use our default refinery rule for everything

---

client/www/pages/docs/instaql.md

[vinciarts pointed this out on discord](https://discord.com/channels/1031957483243188235/1300512212477022208/1300528689330524292). Fixing it up!

[docs] Fix mistaken useQuery call to queryOnce call

---

client/www/pages/docs/strong-init.md

`core/src/schemaTypes.ts` is really nice! Thanks!

[docs] fix strong-init typos

---

client/www/components/marketingUi.tsx

Minor, but had it as a todo to check if we mention our NY address anywhere on the website. We don't list the address, but figured would update the footer

[www] Engineered in San Francisco

---

client/packages/cli/index.js
server/src/instant/admin/routes.clj
server/src/instant/model/schema.clj

Nowlow mentioned he'd like an admin schema endpoint. I thought it would be nice to set one up! 
This exposes the 'schema' layout we have for CLI. I won't add it in the official API just yet, but would be good to open it up and get feedback. 

[admin] add a GET /schema

---

client/sandbox/react-nextjs/app/play/large-query-perf/page.tsx

A user gave a good repro to test large nested queries, and how tx affects the store. 
Moved the demo inside here, so we can iterate on it. 

[test] perf for large queries

---

client/packages/core/src/instaql.js
client/packages/core/src/store.js

While looking into the large query perf optimizations, I realized that most of the time spent on those queries were looking up attrs: 
**I added an `attrs` index, for fwd ident, rev ident, blobs, and primary. This reduced one of the bigger queries from 240ms to about 20ms!** 
**Before**
**After**

[perf][client] improve client-side nested queries by 12x

---

server/src/instant/db/datalog.clj

Two issues that are fixed:
1. We were comparing `:value` in the or conditions when we should have been comparing `:value-blob`.
2. We wern't handling the `symbol-map` datastructure properly. With ands and ors nested in just the right way, we would stop traversing the tree early.

Fix for multiple $not with references

---

.github/workflows/clojure.yml
server/Dockerfile
server/docker-compose.yml

Tested in staging and didn't see the same freezing we were seeing in prod. Could be due to their improvements in handing virtual threads? 
Full changelog: https://www.yourkit.com/changes/

Upgrade yourkit

---

client/packages/core/src/instaql.js

As I was debugging perf, I saw a few too many `anonymous` function calls in the stack trace. Changed it up a bit so that we have the name. 

[sm] use function with names in instaql

---

client/www/pages/hiring.tsx

we missed a space between a link
@nezaj @dwwoelfel

[small] add spacing on hiring page

---

client/www/pages/docs/cli.md

One of users pointed out this blurb was confusing/misleading. Fixing it here!

[Docs] CLI doc fix

---

client/packages/core/src/devtool.ts

[Devtool] Add ids and adjust escape

---

client/www/pages/docs/presence-and-topics.md

Following up from https://github.com/instantdb/instant/pull/440, putting together a fuller topics example with real code that folks can run
https://github.com/user-attachments/assets/1af211f4-35e4-4c5e-bb66-de162eaa4428

[Docs] Add full topics example

---

server/src/instant/util/logging_exporter.clj

Should reduce our log expenses and maybe make things a little faster.

Exclude set-presence from the cloudwatch logs in prod

---

server/src/instant/reactive/session.clj

[test] increase num-receive-workers

---

server/flags-config/instant.schema.ts
server/flags-config/package.json
server/flags-config/pnpm-lock.yaml
server/resources/migrations/36_checked_data_type.up.sql
server/src/instant/db/indexing_jobs.clj

1. Fixes a bug where we notify every time we check for stuck jobs instead of checking if there are stuck jobs
2. Backdates the migration to indicate the constraint is checked.

Quick followup for checked types PR

---

client/www/lib/types.ts

Was reviewing #448 and noticed a small typo for types. Not a big deal but figured would push up

[sm][types] sm type fix for jobs

---

server/src/instant/admin/routes.clj
server/src/instant/dash/routes.clj
server/src/instant/db/instaql.clj
server/src/instant/db/permissioned_transaction.clj
server/src/instant/model/schema.clj
server/src/instant/reactive/session.clj
server/src/instant/superadmin/routes.clj

Follow up to #476, now we'll actually use the rules cache.

Use the cached rules

---

client/www/components/dash/Billing.tsx
client/www/pages/dash/index.tsx
server/src/instant/dash/routes.clj
server/src/instant/model/instant_subscription.clj
server/test/instant/stripe_test.clj

We enabled showing the billing tab to collaborators and above but needed to update a few more places
* Show the billing tab on the left
* Fetch subscription based on just app id, no need for user info
* Show friendly error message for portal link as well

[Dash] Show correct billing for collaborators

---

client/packages/cli/index.js

Previously, We had 6 total commands for push and pull: 
- `push-schema`: push _just_ the schema
- `push-perms`: push _just_ the perms
- `push`: push _both schema and perms
- `pull-schema`: pull _just_ the schema
- `pull-perms`: pull _just_ the perms
- `pull`: pull _both_  perms and schema
In this PR, we merge them into two commands: 
- `push schema | perms | all, defaults to all`
- `pull schema | perms | all, defaults to all`
I also moved the `-app` override to be an option, rather than an argument. 
**Callers of push-perms, pull-schema, et al**
These commands will continue working, but with a deprecation warning message: 
**Callers of push [app-id]**
If a caller included an app-id-or-name argument which _would_ have resolved to an app id before, we will continue supporting it, but print …

[cli] single push / pull command

---

client/packages/cli/index.js

Left these accidentally (they had no effect, but would cause ts warnings)
@nezaj @dwwoelfel

[sm] remove stray `opts` argument

---

client/packages/cli/index.js
client/www/pages/docs/cli.md
client/www/pages/docs/permissions.md
client/www/pages/docs/schema.md

Updated references to push-schema, pull-perms et al, to use our now more powerful `push` and `pull` commands

[cli][docs] Update docs for cli push and pull

---

client/packages/cli/index.js

When doing pull, if we couldn't find Instant's module in the package.json, we would warn and continue on. 
However, if we didn't have the module name, we would likely create an erroneous schema file. We default to `@instantdb/core`, so for all react and react-native users, they would get a broken file. 
In an ideal world we would prompt them here and install instant for them, but for now just stopping with an error instead: 

[small] make missing instant module an error rather than a warning

---

server/src/instant/reactive/session.clj

Adds some debug info about the queries we were executing when `:refresh` times out.
Passes a `debug-info` atom into handle-receive, then populates that atom with the queries we're going to run in `:refresh`. If we time out, then we'll put those queries in error we send to the client.
Here's what's new in the error event:
```diff
{
"op": "error",
"status": 500,
"client-event-id": null,
"original-event": {
"op": "refresh",
"session-id": "67401257-49b0-4f14-9fe3-2b838d83b339",
"total-delay-ms": 0,
"ws-ping-latency-ms": 0.463833,
+       "processed-tx-id": 1156752,
+       "instaql-queries": [
+           {
+               "colors": {}
+           }
+       ]
},
"type": "operation-timed-out",
"message": "Operation timed out: handle-receive",
"hint": {
"timeout-ms": 5000
}
}
```
Not sure if …

Add some debug info on refresh timeout/failure

---

client/packages/cli/index.js

If you set you've already set an `INSTANT_APP_ID` in your env var, `init` will now pick it up: 

[cli] init: detect the app id if possible

---

client/packages/cli/index.js

This PR: 
- Adds a `--app` flag to init, so you can provide an app id upfront
- Updates how we detect app ids, so if we experience an error in some input, we exit early rather than continue with other methods
- Previously, if an `env` app id was formatted incorrectly, we would print an error and then continue, prompting the user to create an app. But instead, i.m.o it's better to exit at that point 
- Generalizes the logic for detecting or creating an app into one function 
Now that `init` has a `--app` flag, there's a real similarity to `pull`. If you think about it, `init` is like `pull`, but it lets you create an app. 
Which begs the question: why shouldn't `pull` let you create an app, if it doesn't exist? 
I think it should. This first PR generalizes the logic for 'detecting' or …

[cli] add a `-a` flag to init

---

client/packages/cli/index.js

- Fixed grammar
- Added terminalLink to dashboard url 

[cli][small] fix grammar + use terminalLink for dashboard

---

client/packages/cli/index.js

Hasn't shipped, to prod, but missed this fn name. Pushing now just in case

[bugfix] lowercase -> toLowerCase

---

client/www/pages/docs/strong-init.md

I came across a few minor typos while reading through the strong-init documentation. This PR fixes those typos.

[Docs] Fixed minor typos in strong-init documentation.

---

client/packages/cli/index.js

Previously, 
If you ran `instant-cli pull schema`, and we couldn't find an env file, we would ask if the user wanted us to create one. 
This had a few issues: 
1. If the user had vite or next or svelte, the variable name may be need to be specific
2. If the user provided the app specifically -- i.e with --app, then it may not make sense to prompt the user to create a .env file -- they may not want it 
3. We also had a different section which printed information about adding newly created app ids to a .env file 
I now centralize all this, so: 
1. If the user ever creates or imports an app, we enter the .env info flow
2. We detect the ideal env name for the user (by checking for next, vite, etc in their package.json) 
3. If the user does not have a .env file, we prod to create it 
4. If the …

[cli] Centralize our `.env` messages, and detect the env name

---

server/src/instant/jdbc/failover.clj

Update the transaction id seq to the latest value before switching over.

Update the seq

---

client/packages/cli/index.js

Previously, if a user wrote something like: 
```bash
instant-cli push
``` 
And then there were no schema changes, the whole flow would exit. This didn't make sense though, as the user _may_ have wished to push perms too. 
Similarily, if a user wrote: 
```bash
instant-cli pull
```
And they didn't want to override their schema file for example, the whole flow would exit. But this also didn't make sense, as the user _could_ have wanted to pull perms. 
Updated `pushSchema` and `pullSchema` to return an `ok` flag. This returns `true` if the user decides to exit early, or there is no schema. It only returns false where there is a real error and we should break out. 

[cli][schema] Don't break early when user skips schema

---

server/src/instant/scripts/metrics.clj

ChatGPT made a suggestion on how to improve this query and running `EXPLAIN` showed about ~15% improvement here so figured we could commit it

[Metrics] Improve stats queries

---

server/src/instant/scratch/export.clj

We had a script that let us import apps into dev, to do perf checks and the like.
Putting it up for the team to use here. 
Credit to @dwwoelfel for writing the original version of this, and making debugging better + safer. 

[scratch] add export script

---

server/.gitignore
server/Makefile
server/deps.edn
server/src/instant/db/instaql.clj
server/src/instant/scratch/backtest.clj
server/src/instant/scratch/backtest_vars.clj
server/test/instant/db/instaql_test.clj

Consider a query like this:
```edn
{:conversations {:$ {:where {:groups "group-id", :messages.time {:$gte 0}}}}}
```
This would produce two patterns, which looked like: 
```edn
;; cond-1
[?conversation :groups "group-id"] 
;; cond-2
[?message :time {:$gte 0}]
[?message :conversation ?conversation] 
```
This would convert to a CTE which looked something like: 
```sql 
-- [?conversation :groups "foo"] 
WITH match_0_0 AS MATERIALIZED (
SELECT
-- ...
FROM
triples
WHERE 
(app_id = ?)
AND (vae = true)
AND (attr_id = ?)
AND ( value =  ?)
),
-- [?message :time {:$gte 0}]
match_0_1 AS MATERIALIZED (
SELECT
match_0_0.*,
--- ...
FROM
triples,
match_0_0
WHERE
(app_id = ?)
AND (ave = true)
AND (attr_id = ?)
AND (TRIPLES_EXTRACT_NUMBER_VALUE(value) >= ?)
AND (checked_data_type = CAST('number' AS …
```

[query-perf] push conds from WHERE clauses to JOIN clauses

---

.github/workflows/clojure.yml
server/dev-postgres/Makefile
server/docker-compose-dev.yml

Match tests with prod postgres version (or soon to be prod anyway).

Test with postgres 16

---

client/packages/core/src/Reactor.js

This should fix the reactor bug that Aphex reported in Discord: https://discord.com/channels/1031957483243188235/1314344673459965992
The basic issue is that we're too aggressive in deleting querySubs when we experience an error.
For the error in discord, we get a stacktrace that looks like:
```
Reactor.js:483 Uncaught TypeError: Cannot set properties of undefined (setting 'result')
at eval (Reactor.js:483:39)
at PersistedObject.set (PersistedObject.js:115:29)
at Reactor._handleReceive (Reactor.js:482:32)
at Reactor._wsOnMessage (Reactor.js:291:18)
```
I was able to replicate the error by forcing `queryOnce` to fail with a query that `useQuery` is subscribing to. We delete the `querySub` in the error handler and then we throw an error when we handle the `add-query` for the `useQuery` …

Better error handling for query errors in reactor

---

client/www/_emails/html/nov2024.html
client/www/_emails/markdown/nov2024.md
client/www/_emails/txt/nov2024.txt
server/src/instant/scripts/newsletter.clj

[Preview link for the newsletter](https://instant-www-js-nov-2024-newsletter-jsv.vercel.app/intern/emails/nov2024)

[Newsletter] Add November newsletter

---

server/src/instant/scripts/daily_metrics.clj

I realized the metrics job didn't run today. Turns out `chime-at` converts `ZonedDateTime` to `Instant`, this was causing an error when calling `date/numeric-date-str`

[Metrics] Chime fix

---

client/www/pages/docs/instaql.md

Updates the ordering doc to show how to order by arbitrary fields:

Add docs on ordering by arbitrary fields

---

client/www/pages/docs/modeling-data.md

[Docs] Fix typo in links

---

client/packages/cli/index.js

I realized I forgot about to update the docs links we generate for the schema.ts file. Went ahead and updated 🫡 

[cli] update docs links

---

server/src/instant/db/datalog.clj
server/test/instant/db/instaql_test.clj

**Context:** 
See #644 for the original root issue. 
When we made the query: 
```edn
{:conversations
{:$
{:order {:serverCreatedAt "desc"},
:limit 5,
:where
{:groups "---",
:messages.time {:$gte 1734485030665}}}}}
```
This broke our `joins-on-value?` check. That check was ultimately too brittle. In the case where we added groups, the join on `value` was actually from an earlier CTE: 
```sql
--- ...
match_0_3 AS MATERIALIZED (
SELECT
DISTINCT ON(order_val, entity_id) CAST(created_at AS BIGINT) AS order_val,
match_0_2.*,
entity_id AS match_0_3_entity_id,
attr_id AS match_0_3_attr_id,
value AS match_0_3_value_blob,
CASE
WHEN eav THEN CAST(value ->> 0 AS UUID)
ELSE null
END AS match_0_3_value_uuid,
created_at AS match_0_3_created_at
FROM
match_0_2
LEFT JOIN triples ON (
app_id = …
```

[bugfix] fix select-distinct-on

---

client/packages/cli/index.js
client/www/pages/docs/cli.md

A user asked us to support NUXT_PUBLIC_INSTANT_APP_ID. This does it : )

[cli] support NUXT_PUBLIC_INSTANT_APP_ID

---

client/sandbox/strong-init-vite/src/typescript_test_abstract.tsx
client/www/pages/docs/instaml.md

Added some docs for UpdateParams and LinkParams. 

[types][docs] Add docs for UpdateParams and LinkParams

---

server/src/instant/db/model/triple.clj

Postgres also allows stringified dates . Doing the same in clojure 

[time] allow json-parsed iso 8601 timestamps

---

server/src/instant/util/coll.clj

Remove debug log

---

server/resources/migrations/46_add_created_at_index_to_transactions.down.sql
server/resources/migrations/46_add_created_at_index_to_transactions.up.sql

What it says on the in! Adding this because the daily metrics job keeps timing out, with an index it can very quickly calculate the metrics!

Add created_at index on transactions

---

server/src/instant/reactive/session.clj

Follow up to https://github.com/instantdb/instant/pull/686, looks like we sometimes get a `null` string as the version.

Handle case when core version is "null"

---

server/src/instant/db/permissioned_transaction.clj
server/test/instant/db/transaction_test.clj

Consider: 
```
orgs 
profiles
handle ; unique
orgs.members <> profiles.org
```
Now imagine we have an _existing_ org and an _existing_ profile. 
If we write a lookup like so: 
```js
tx.profiles[tx.lookup('handle', 'stopa')].update({ fullName: "Stepanado" }).link({ orgs: orgId }  
```
We would get the error: "Record not found: attr",
This was because the link to `orgs` would generate: 
1. an :update check on org 
2. a :view check on profiles
The `:view` check would fail, because we passed in the `etype` as a keyword, while `ref-fn` expected it as a string. 
Passed in the `etype` as a keyword, that fixed it. 

[lookup-perms] make sure view checks work

---

client/www/pages/docs/users.md

Found this while going through repro!

[Docs] sm fix

---

server/src/instant/db/permissioned_transaction.clj

In our `view` objects, we converted the `etype` string to a keyword. 
Looking at how we use etype throughout permissioned-tx and beyond, it's generally treated as a string. 
I went ahead and looked at callsites (outside of permissioned-tx, check-results are mainly used for sandbox). Things look good, so let's push it

[sm] (keyword etype) -> etype

---

server/src/instant/jdbc/wal.clj
server/src/instant/reactive/invalidator.clj

Makes two changes to our replication to help us keep track of everything:
1. Sets the reporting status interval to 1 second (default seems to be 10 seconds) so that we get a more accurate view of our wal byte latency
2. Logs the size of the transaction in bytes in `invalidator/work`. I'm curious to see how the size of the transaction affects the latency.
Also removes some reflection warnings from wal.clj.

Add more replication debugging

---

server/.ebextensions/resources.config
server/docker-compose.yml

Remove a couple of variables while we figure out what is causing the deploys to go haywire.

Undo zgc and placement group

---

server/deps.edn
server/test/instant/reactive/session_test.clj

Updates clj-async-profiler version in prod

Update clj-async-profiler version

---

server/src/instant/reactive/store.clj

Bug fix for https://github.com/instantdb/instant/pull/737.
We can get in a situation where the instaql-query is removed from the store (via session closing or remove-query), but we are still in the process of running datalog queries for the query. In that case we throw a noisy error when trying to insert the subscription because we're referencing an instaql-query that doesn't exist.
Now we won't add a subscription to the datalog topics if we're running the query.

Only create a subscription if we're interested in the query

---

server/deps.edn

Upgrade some deps:
- next.jdbc (1.3.955 -> 1.3.981)
- postgresql client (42.7.2 -> 42.7.5)
- hikari (5.1.0 -> 6.2.1)
- honeysql (2.4.969 -> 2.6.1270)
I've been running them locally for a week or so and haven't noticed any issues.

Upgrade some db-related deps

---

client/www/_posts/conj.md
client/www/_posts/datalogjs.md
client/www/_posts/db_browser.md
client/www/_posts/next_firebase.md
client/www/_posts/seed.md
client/www/components/marketingUi.tsx
client/www/lib/posts.js
client/www/pages/essays/[slug].tsx
client/www/pages/essays/index.tsx

Supports multiple authors for our essays. Needed this for what's coming soon! 

[blog] support multiple authors

---

server/deps.edn
server/src/instant/db/cel.clj
server/src/instant/db/model/attr.clj
server/src/instant/db/transaction.clj
server/src/instant/reactive/store.clj
server/src/instant/util/logging_exporter.clj
server/src/instant/util/uuid.clj
server/src/tool.clj

Some simple performance optimizations

Simple performance optimizations

---

client/www/pages/docs/modeling-data.md

Wanted to tweak the grammar just a bit before launching

[Docs] sm cascade delete

---

client/www/_posts/pg_upgrade.md
client/www/components/marketingUi.tsx
client/www/pages/index.tsx

We need to re-phrase our rec to target typescript folks. Hiding it for now 

[hiring] hide the page

---

client/www/_posts/pg_upgrade.md

Thought this would be more pro

[essay] lowercase sql : } 

---

client/packages/core/src/Reactor.js
client/packages/core/src/authAPI.ts
client/packages/core/src/index.ts
client/packages/react-native/src/index.ts
client/packages/react/src/index.ts

Kosmik team mentioned they had a bug where they accidentally wrote `refreshToken` instead of `refresh_token`. 
I added some more types to the auth api, so these kind of bugs are easy to catch 

[client][types] add types to auth api

---

client/www/_posts/pg_upgrade.md

[essay] include how long the pause took.

---

server/flags-config/instant.schema.ts
server/flags-config/package.json
server/flags-config/pnpm-lock.yaml

Updates flags schema with welcome-emails

Update flags config

---

server/test/instant/reactive/session_test.clj

This reverts commit 93d7ebcc748b4ce7a423fad8f742e509db4bd18a.
Fixes the flaky test for now while we figure out why the set-presence is coming in out of order.

Revert "Maintain order of operations in session tests (#760)"

---

.github/workflows/js.yml

Stops using corepack and installs pnpm with the pnpm setup action instead.

Fix js build step

---

server/src/instant/storage/s3.clj

We could multiplex the uploads but figured temporarily allowing the bytes in memory will be fine since the migration should be less than 10 minutes

Enable uploading twice

---

server/src/instant/storage/s3.clj

Moved a bit too fast with the earlier PR, this should properly do the trick!

Remove with-open

---

client/www/components/dash/Billing.tsx
client/www/components/dash/auth/Apple.tsx
client/www/components/dash/auth/Clerk.tsx
client/www/components/dash/auth/Google.tsx
client/www/components/dash/auth/Origins.tsx
client/www/lib/auth.ts
client/www/lib/errors.ts
client/www/lib/hooks/useCurrentDate.tsx
client/www/lib/hooks/useTotalSessionsCount.tsx
client/www/pages/dash/oauth/callback.tsx
client/www/pages/index.tsx
client/www/pages/intern/overview.tsx
server/src/instant/dash/routes.clj
server/src/instant/machine_summaries.clj
server/src/instant/reactive/store.clj

[instant] add total session counts

---

client/www/pages/index.tsx

session-count on the home page

---

client/www/pages/intern/overview.tsx

Realized I had it sorted in asc order, but wanted desc

[overview] re-order active connections

---

client/www/components/dash/explorer/Explorer.tsx

Moved too fast on the cr fix. This is the right order!

sm files fix

---

client/www/pages/intern/overview.tsx

[overview] Add Active Apps

---

client/www/pages/intern/overview.tsx
server/src/instant/machine_summaries.clj
server/src/instant/reactive/session.clj
server/src/instant/reactive/store.clj

This adds origin info to our overview. Can be nice to look at currently active apps and play with them. 
@nezaj  @dwwoelfel @tonsky 
Not sure UI is amazing for this yet -- will play with it once I can see this with prod data

add origin info

---

.github/workflows/clojure.yml
server/Dockerfile-dev

Includes a fix for an annoying bug where the cache step can hang for a couple of minutes (https://github.com/DeLaGuardo/setup-clojure/pull/109)

Upgrade setup clojure action

---

client/www/pages/intern/overview.tsx
server/src/instant/dash/admin.clj
server/src/instant/dash/routes.clj

Adds the number of pro subscriptions we have to metrics!

[metrics] add pro subscriptions to metrics

---

client/www/_posts/pg_upgrade.md

Noticed a few grammar mistakes

[blog] grammar updates

---

server/src/instant/scripts/welcome_email.clj

Noticed welcome emails haven't been going out and realized the issue was due to `chime-at` passing in an argument to send-welcome-email.
I also switched to using `swap!` instead of `reset!` to be thread-safe

[Server] Welcome email fix

---

client/www/_posts/pg_upgrade.md
client/www/pages/intern/investor_updates.tsx

- re-ordered graph, so it matches how we send investor updates
- changed growth percentage to round to 1 decimal point, to match what we do in investor updates
- fixed some more grammar in our essay 

improve investor updates and grammar

---

client/www/pages/intern/overview.tsx

This displays the extra origins (cappted at 5) if you have over them. 
@dwwoelfel @tonsky @nezaj

Add alt tooltip to origins

---

client/www/pages/intern/overview.tsx

I have a hunch our `daily.error.body` code here through a 500 and borked our overview page on the Rasp Pi. Fixing by adding an or clause. 

fix potential bug in overview

---

client/pnpm-lock.yaml
client/www/components/AnimatedCounter.tsx
client/www/package.json
client/www/pages/index.tsx

https://github.com/user-attachments/assets/d3b7927f-4759-493b-9333-68929e57c30d
Thought this would be a good time to introduce [motion](https://motion.dev/). I used it for a digit counter animation

add animations to our counter

---

client/www/markdoc/partials/auth/useAuth.md
client/www/pages/docs/auth/magic-codes.md
client/www/pages/docs/index.md

**Before** 
**After** 
--- 
Apart from styling, made a few more changes:
1. We now autofocus
2. I made the inputs required, so you can't enter without filling something in 
3. Renamed components to EmailStep and CodeStep 
4. Added some more typescript types 

[docs] use tailwind for our magic codes example

---

client/www/pages/_devtool/index.tsx

Updated our devtool help page to link to docs. 

[small][devtool] link to docs

---

client/www/pages/_devtool/index.tsx

Did this for docs demo, and forgot to undo. 

[sm] My App -> app.title

---

client/www/components/dash/Onboarding.tsx

Feedback from a user: 
Added a sign out button in the onboarding phase. 

[dash] Add Sign out in Onboarding flow

---

server/src/instant/model/app_file.clj
server/src/instant/storage/s3.clj
server/src/instant/util/s3.clj

Used these to update content types for Clark! Will use them later to run through all our $files triples to make them in sync with s3

Add metadata update helpers

---

client/www/components/docs/Layout.jsx
client/www/components/docs/Search.jsx
client/www/components/marketingUi.tsx

This reverts commit 09e11e337aef18d960ad43d0de1c73e623f1332a.
I will add it back in on Monday -- noticed some inconsistencies on iphone

Revert "[docs] improve layout (#876)"

---

server/scripts/eb_deploy.clj

An additional check before running deploy:
```
[/ws/instant/server] ./scripts/eb_deploy.clj
Fetching application versions...
Getting db URL...
Checking prod db version...
[ERROR] Looks like you need to run DB migrations first
Current prod version: 54
Latest migration: 55
```

Check DB version before deploy

---

client/www/components/docs/Layout.jsx
client/www/components/docs/Search.jsx
client/www/components/marketingUi.tsx

Originally I deployed https://github.com/instantdb/instant/pull/876 , but found a few issues when checking with iphone. I reverted it. 
This undoes the revert, and fixes the issue (had to add a min-w-0 on a flex child)
@nezaj @tonsky @nezaj

[docs] new layout

---

client/packages/cli/src/index.js

I forgot to change the location we chose from localPermsFile. Thankfully this hasn't shipped to prod yet, so we _should_ be good. 
I also fixed some bugs when pulling into a fresh instance (had to add a `?`)

[perms] instant.schema -> instant.perms

---

client/scripts/publish_packages.clj

**Before**
Some packages depend on `@instantdb/*`. In a monorepo, we use `"workspace:*"` to refer to the local version. Buut, we can't publish packages this way. Before we publish, we need to change `workspace:*` to the actual version.
**Recently** 
I started noticing that publishing the client had issues. I am not 100% sure why this happened recently -- perhaps with some pnpm upgrade or something. 
The root cause _seemed_ to be us changing the `workspace:*` in dependencies. I would get an error like: 
```
error TS2307: Cannot find module '@instantdb/core' or its corresponding type declarations.
```
I had a hunch that this was because, since the `dependency` said $new-version, somehow pnpm run build-packages was having trouble resolving the package from local. 
**After**
I found that …

[publish-packages] remove set-dep-versions!

---

client/packages/core/src/Reactor.js
client/packages/core/src/index.ts
client/packages/react/src/InstantReactAbstractDatabase.ts
client/www/pages/docs/auth/magic-codes.md

We got an ask for one-off `getAuth` and seemed straight-forward / quick-win.

Add getAuth

---

server/src/instant/flags_impl.clj

Fixes the dummy session we create for flags so that it gets updated in the invalidator

Fix flags session

---

server/scripts/eb_deploy.clj

Follow-up to  #879
We now allow users to choose whether to ignore the mismatched DB versions or abort. Also do fetch to ensure commit that is deployed is presented locally

Warn users on deploy instead of blocking it

---

client/packages/core/src/Reactor.js
server/src/instant/model/rule.clj

[typo] prm -> prime, permissions

---

server/resources/migrations/56_nulls_first_indexes.down.sql
server/resources/migrations/56_nulls_first_indexes.up.sql
server/src/instant/db/datalog.clj
server/test/instant/db/instaql_test.clj

Improves pagination for namespaces with many objects by making better use of the index for sorting.
The main changes are
1. Don't materialize the ctes within a single pattern-group. The `materialized` was causing postgres to fetch all items from the namespace even though it would only need a single page if the query was organized better. By marking it `not materialized`, postgres can make better query plans. 
I've done some backtesting and I haven't found any queries that slowed down a bunch, but I'm still working on getting a wider range of queries to test.
2. Removes the join to get the entity_id for "undefined" values. We no longer need that now that we insert nulls: https://github.com/instantdb/instant/pull/869
3. Create the index with `nulls first` instead of `nulls last`. We fetch …

Make pagination use the index

---

server/src/instant/db/datalog.clj

Noticed some queries pop up that were slow after the pagination PR because of the change from `materialized` to `not materialized`. If one of the ctes returns very little data, then it would be better to materialize it. We can kind of estimate that a cte returns less data if it's matching on an indexed value. It's not 100%, but it is better overall in my backtesting.
We could improve this in the future by keeping our own counts for indexed attrs.
<details>
<summary>Backtesting against same queries from the pagination PR</summary>
Shows that it's not worse:
| :old-ms | :new-ms | :improvement | :same |
|---------|---------|--------------|-------|
|    1816 |    2029 |         -212 |  true |
|   19540 |   19679 |         -138 |  true |
|    8576 |    8606 |          -30 |  true |
|     210 | …

Materialize if we're filtering on an indexed constant

---

server/src/instant/admin/routes.clj
server/src/instant/db/instaql.clj
server/src/instant/storage/coordinator.clj
server/src/instant/storage/s3.clj

With docs nearly ready, and the PR for enabling storage for all https://github.com/instantdb/instant/pull/906, adding another PR to remove migration code!

[Storage] Remove files migration

---

server/deps.edn
server/dev-resources/hooks/pre-commit
server/test/instant/admin/routes_test.clj
server/test/instant/db/datalog_test.clj
server/test/instant/db/indexing_jobs_test.clj
server/test/instant/db/instaql_test.clj
server/test/instant/db/transaction_test.clj
server/test/instant/jdbc/sql_test.clj
server/test/instant/reactive/invalidator_test.clj
server/test/instant/reactive/session_test.clj
server/test/instant/reactive/store_test.clj

- Tests code is now linted too (and it even caught a bug!)
- pre-commit hook now correctly only checks sources from src/ and test/ and applies .clj-kondo config

Lint tests & filter sources to pre-commit hook

---

server/src/instant/flags_impl.clj
server/src/instant/gauges.clj
server/src/instant/grouped_queue.clj
server/src/instant/machine_summaries.clj
server/src/instant/reactive/ephemeral.clj
server/src/instant/reactive/invalidator.clj
server/src/instant/reactive/receive_queue.clj
server/src/instant/reactive/session.clj
server/src/tool.clj
server/test/instant/grouped_queue_test.clj
server/test/instant/reactive/invalidator_test.clj
server/test/instant/reactive/session_test.clj

Try fixed thread pool & less work under lock in put!

Simplify grouped queue 4

---

client/www/scripts/index-docs.mjs

[quick fix] /n -> \n

---

client/www/pages/docs/instaml.md

Got some feedback using lookups in link entity ids was hard to parse, making this more explicit!

[Docs] Add lookups in link section

---

server/test/instant/grouped_queue_test.clj
server/test/instant/reactive/session_test.clj

Make eftest exit normally by shutting down all grouped-queue pools

---

.github/workflows/js.yml
client/Makefile
client/package.json
client/pnpm-lock.yaml
client/www/package.json
client/www/scripts/index-docs.ts

I wanted to upgrade our script to use typescript. TS is especially useful in scripts. We rarely run these scripts, so some extra types to help gain context can be great. 

[index-docs] use typescript

---

client/packages/core/src/index.ts
client/packages/react/src/InstantReactAbstractDatabase.ts

`Reactor.getAuth` can return `null`.

Fix getAuth return type annotation

---

client/www/components/docs/Layout.jsx
client/www/lib/app.tsx
client/www/pages/dash/index.tsx

I realized that our docs app picker did not list apps in the same order as our dashboard. To fix, I extracted out the `createdAtComparator`, and made sure they have the same order.

[sm][docs] order app picker by created at

---

client/www/pages/docs/instaql.md

For consistency with the rest of the examples in the doc.

Update instaql.md docs: useQuery -> db.useQuery

---

client/www/pages/docs/instaml.md

[Docs] Update merge example

---

client/www/pages/docs/instaml.md

[Docs] Moar merge doc fix

---

client/www/components/dash/explorer/Explorer.tsx

This PR enables browser navigation for different namespaces, filters, and sorts for the explorer.
https://github.com/user-attachments/assets/42b8f989-a984-4e34-8e14-8a40f8a16c82

Make explorer deep-linkable

---

client/www/components/dash/explorer/Explorer.tsx

Realized it would be nice to deep-link pagination too in the explorer so adding that here!

[Explorer] Deep link pagination

---

server/test/instant/db/instaql_test.clj

Still trying to figure out how we can make it consistent

Disable the av index test because it's flaky

---

client/packages/admin/src/index.ts
client/packages/core/src/index.ts
client/packages/core/src/instatx.ts
client/packages/react/src/InstantReactAbstractDatabase.ts
client/www/pages/docs/instaml.md
client/www/pages/docs/storage.md
client/www/pages/index.tsx

Doing `db.tx` is the recommended way now so updating our docs and doc-strings to consistently reflect that!

[Docs] Standardize db.tx

---

server/src/instant/fixtures.clj
server/src/instant/util/io.clj
server/test/instant/db/instaql_test.clj

Fails tests if `warn-io` is triggered during the test. This would have prevented the bug fixed by https://github.com/instantdb/instant/pull/960
In order to make the test errors track the correct position in the file, I had to make all of the `with-X-app` functions into macros. That binds the `*file*` variable to the test file and we can search the stack trace when we encounter io to get the nearest line in the test file.

Fail tests on unexpected io

---

client/packages/cli/src/index.js

This pulls `onDelete: cascade` info when we do instant-cli pull schema 
@tonsky @nezaj @dwwoelfel

[cli] pull onDelete cascade info

---

server/src/instant/intern/metrics.clj

Thought it would be nice if we could keep the labels

[Metrics] Fix bar renderer

---

client/www/pages/docs/instaql.md
client/www/pages/docs/patterns.md

Updating this pattern now that we have select fields. Also thought it might be nice to explicitly call out in select fields that users still need to be aware of permissions

[Docs] Update split attributes pattern

---

server/src/instant/db/datalog.clj

Passes a single array with all attr ids instead of a big list of ORs. Uses fewer parameters, sends less data over the wire, and is the slightest bit faster for honeysql to generate.
Did some backtesting and didn't actually see any improvements one way or the other. This should help prevent the query planner from reverting back to the created_at index, though.

Use array param to pass attrs

---

client/www/components/dash/explorer/Explorer.tsx
client/www/components/ui.tsx

Got a user ask for this and thought it was another nice win.
https://github.com/user-attachments/assets/247d3e28-7e9b-4e53-b9fe-d9c8c7467769

[Explorer] Enable shift-click

---

client/www/pages/docs/backend.md
client/www/pages/docs/instaml.md
client/www/pages/docs/instaql.md

As I'm going through the llm prompt finding small doc improvements

[Docs] sm doc updates

---

client/www/components/dash/PersonalAccessTokensScreen.tsx
client/www/pages/labs/platform_demo.tsx

- Updated our platform demo so it shows how to create / delete apps, and how to push schema / perms 
- I removed the info about transfer requests, as we will be building out a way to connect to Instant

[platform] update our platform demo

---

client/www/pages/docs/permissions.md

- I realized our perm examples were not conistent:
- some showed { "todos" , while others omitted the json. some were invalid json 
- I sweeped and made everything consistent.
- Also changed up the ruleParams docs a bit 

[docs] update perm docs

---

server/src/instant/scripts/welcome_email.clj

I noticed our welcome emails didn't send today because it the script borked on an in-active recipient (we throw an error from `postmark.clj`) -- added logic to log when we can't send to someone and move on to the next

[Welcome Email] Handle errors on send

---

client/packages/react/src/InstantReactAbstractDatabase.ts
client/sandbox/react-nextjs/pages/play/ruleParams.tsx
server/src/instant/db/permissioned_transaction.clj
server/src/instant/util/async.clj
server/src/instant/util/tracer.clj
server/test/instant/db/transaction_test.clj

This fixes a bug, where ruleParams would fail if we created an entity. 
(Co-authored by @tonsky and me!) 

[rule-params] fix tx.foo[newId].ruleParams

---

client/www/_posts/sync_future.md
client/www/components/marketingUi.tsx
client/www/lib/posts.js
client/www/pages/essays/[slug].tsx

“Sync Engines are the future” blog post

---

client/www/pages/docs/instaql.md
client/www/pages/docs/patterns.md

Playing around with other LLM models and noticed they pick up on importing from core due to our docs. Most of the docs are react focused so figured we can standardize on this

[Docs] sm core -> react

---

server/src/instant/db/permissioned_transaction.clj
server/test/instant/db/transaction_test.clj

If a user had a rule like: 
```js
{ 
"books": { 
"allow": { 
"view": "data.id == ruleParams.knownBookId"
}
}
```
And wrote a transaction like: 
```js
tx.bookshelves[id].ruleParams({ knownBookId: bookId }).update({ ... }).link({ books: bookId })
```
This would lead to a failed transaction. 
**The reason?: view check did not receive any ruleParams** 
**Fix** I made the following change: 
Now, when we insert the `view` check, we also make sure to copy the ruleParams from the transaction that was causing it, onto that check. 
@tonsky @nezaj @dwwoelfel

[perms] handle ruleParams in the view check on link

---

server/.clj-kondo/imports/instaparse/config.edn
server/src/instant/admin/routes.clj
server/src/instant/model/app_user.clj
server/src/instant/system_catalog_ops.clj
server/src/instant/util/coll.clj
server/test/instant/admin/routes_test.clj

Let's let users get presence info from the admin API!
Added a `GET /admin/presence?room-type=A&room-id=B` endpoint. This: 
1. Gets presence info
2. Enhances user data with things like email, et al

[admin][rooms] get presence

---

server/src/instant/config.clj

Use www.instantdb.com instead of the bare domain for dashboard origin

Fix dashboard origin

---

client/www/components/DocsPage.jsx
client/www/pages/docs/auth.md
client/www/pages/docs/auth/apple.md
client/www/pages/docs/auth/clerk.md
client/www/pages/docs/auth/google-oauth.md
client/www/pages/docs/auth/magic-codes.md
client/www/pages/docs/backend.md
client/www/pages/docs/cli.md
client/www/pages/docs/devtool.md
client/www/pages/docs/emails.md
client/www/pages/docs/index.md
client/www/pages/docs/init.md
client/www/pages/docs/instaml.md
client/www/pages/docs/instaql.md
client/www/pages/docs/modeling-data.md
client/www/pages/docs/patterns.md
client/www/pages/docs/permissions.md
client/www/pages/docs/presence-and-topics.md
client/www/pages/docs/showcase.md
client/www/pages/docs/start-rn.md
client/www/pages/docs/start-vanilla.md
client/www/pages/docs/storage.md
client/www/pages/docs/teams.md
client/www/pages/docs/users.md

Testing some automated creation of `llms.txt`, and part of that involved adding descriptions to our docs. Also thought it would be nice to have custom social embeds similar to what @stopachka did for the essays

[Docs] Add description and custom social previews to docs

---

client/packages/admin/src/index.ts
client/packages/core/src/index.ts

Realized we hadn't added ruleParams to `query`. Added it here! 
@tonsky @dwwoelfel @nezaj

[admin] add ruleParamas to `query`

---

client/www/pages/docs/patterns.md

[Docs] Add CDN pattern

---

client/www/pages/dash/index.tsx

Uses a combobox for the apps select input to make it easier to search for an app.
Direct link to preview: https://instant-www-js-search-apps-jsv.vercel.app/dash
Filtered:

Make apps select box searchable

---

client/www/components/dash/Sandbox.tsx

Creates a separate local store for each sandbox so that you don't lose your work when switching between apps.

Separate sandbox value per app

---

server/deps.edn
server/resources/migrations/59_is_required.down.sql
server/resources/migrations/59_is_required.up.sql
server/src/instant/db/model/attr.clj
server/src/instant/db/model/triple.clj
server/src/instant/db/transaction.clj
server/src/instant/jdbc/sql.clj
server/src/instant/oauth_apps/routes.clj
server/src/instant/system_catalog.clj
server/src/instant/system_catalog_ops.clj
server/src/instant/util/test.clj
server/test/instant/db/transaction_test.clj
server/test/instant/jdbc/sql_test.clj

This PR only adds required attr to the schema and validates it during tx. Since no attrs will be marked as required at the start, this shouldn’t affect anything and is safe to merge. I suggest we merge this first to minimise merge conflicts later down the road

Add validation for required attrs

---

client/packages/admin/src/index.ts
client/sandbox/admin-sdk-express/src/index.ts
client/sandbox/strong-init-vite/src/typescript_tests_experimental_v2.tsx
client/sandbox/strong-init-vite/src/typescript_tests_experimental_v2_no_schema.tsx

Added our backend `fetch presence` api: 
```js
const presences = await adminDB.rooms.getPresence('chat', '123');
```
Docs will come in a separate PR

[client] adminDB presence

---

client/packages/react-native/src/index.ts

We got a request to export this so adding it here.
Looks like we export `InstantReactWebDatabase` in the react package too

[RN] Export InstantReactNativeDatabase

---

client/www/pages/docs/backend.md
client/www/pages/docs/patterns.md

Adds docs for `localId` and `fetchOpts`, and `adminDB.rooms`

[docs] localId + fetchOpts + presence

---

client/www/pages/docs/using-llms.md

I remember @stopachka mentioned an example would be nice so thought I'd add one in here

[Docs] Add example prompt

---

server/src/instant/dash/routes.clj
server/src/instant/postmark.clj

Set a custom domain for when we send magic codes for dashboard. 

[emails] custom domain for dash magic codes

---

client/www/components/dash/auth/Google.tsx

realized the copy for add and edit were different. abstracted it into a shared component. 

[sm] update nonce check copy

---

client/www/pages/docs/patterns.md

A user asked us about supporting composite keys. We don't support composite keys as first-class options, but you can use columns to make them work. I wanted to add a pattern showing how to do this. 

[docs] pattern for composite keys

---

server/resources/migrations/62_seed_ephemeral_app_creator.down.sql
server/resources/migrations/62_seed_ephemeral_app_creator.up.sql
server/resources/migrations/63_seed_homepage_app.down.sql
server/resources/migrations/63_seed_homepage_app.up.sql

this seeds: 
1. The ephemeral app creator user 
2. The homepage app

[instant] seed ephemeral app creator, homepage app

---

client/www/components/dash/auth/Google.tsx

I accidentally seeped some of the Google Sign In work I was hacking on in https://github.com/instantdb/instant/pull/1097 
Undoing in this PR (will open up a PR with the full google work in a follow-on) 

[bugfix] undo google code

---

client/www/pages/docs/auth/google-oauth.md

Did one more read-through on Google Oauth. Fixed a few grammar issues 

[docs] small grammar fixes

---

client/www/pages/hiring/ts-hacker.tsx

user reported hiring page was broken on mobile. fixed!

[bugfix] hiring page for mobile

---

client/www/pages/docs/patterns.md

A user asked us about including name and profile picture for google oauth. This is a pattern that lets them do it. 

[patterns] adding extra info from google oauth

---

client/packages/core/src/index.ts

This should fix: https://github.com/instantdb/instant/issues/1125

Use .js for .js file imports in index.ts

---

client/packages/core/src/instatx.ts

**Problem**
consider a chunk like: 
```js
const chunk = db.tx.posts[id()].update({ title: 'Foo' }); 
```
Today, if you write: 
```js
console.log(chunk)
// or 
JSON.stringify(chunk)
```
You'll see an empty object. 
**Solution** 
I added `__etype` and `__ops` onto the `target` part of our proxy. This makes it so now console.log will show the keys, and stringify will stringify them too: 

[client] make instatx introspectable

---

client/packages/core/src/Reactor.js
client/packages/core/src/index.ts
client/packages/core/src/utils/log.ts

Added a `verbose` flag to `init`. This lets us quickly toggle a db and see more logs.

[client] add `verbose` flag

---

server/src/instant/reactive/session.clj
server/test/instant/reactive/session_test.clj

Validates that the room key is a string.
Here's what it looks like when you provide something that's not a string:
Here's what it looks like when you provide null:
And here's what it looked like before:

Room key validation

---

server/src/instant/reactive/ephemeral.clj

Trying this, to see if it helps the deploy. 

[hz] change cluster name and instance-name

---

client/packages/cli/src/index.js

Users pointed out that if the CLI stopped with an error, we would still return an exit code with a value of 0. 
I updated our script, so when we fail, we return an exit code of 1. 

[cli] give proper exit codes when we return with an error

---

server/deps.edn
server/dev/user.clj
server/src/tool.clj

We can now use `#p` from the library

Bump clojure+, remove hashp

---

server/flags-config/instant.schema.ts

Fixes a a bad merge conflict resolution in the flags config's instant.schema.js

Fix merge conflict

---

client/www/pages/index.tsx

Noticed we had some dead code here so thought it would be nice to remove

[www] Remove dead konami code

---

server/src/instant/db/datalog.clj

Removes the hint where we aren't sure if postgres can make good use of the index.
There are a few places where we were telling postgres to use an index that wasn't efficient:
1. Exact matches on strings don't work well with the trgm index (it's better at `like`)
2. `is distinct from` (what we use with `not` to catch nils) doesn't seem to use the index very well. Postgres has to filter afterwards instead of putting it in the index condition.
Now we'll skip putting any hints for `:function` clauses and when we're matching on a string index. Hopefully postgres will chose the index if it makes sense.
This closed the gap for the 4 "bad" queries I was testing and preserved the improvement for the 3 "good" queries I tested. We'll see in the pg-hint-plan testing what other outliers there are.

More judicious use of index hints

---

client/packages/cli/package.json
client/packages/cli/src/index.js
client/pnpm-lock.yaml
server/src/instant/dash/routes.clj

Reported by Kosmik. Does not fix the issue but should print better reporting

Some help debugging CLI indexing jobs reporting

---

client/packages/platform/README.md
client/packages/platform/src/index.ts
client/sandbox/react-nextjs/pages/play/platform-sdk-demo.tsx

Includes docs for the client-only OAuth flow and for the PlatformApi.

Flesh out the readme for @instantdb/platform

---

client/www/pages/docs/using-llms.md

[Docs] Add copy button for MCP example

---

server/src/instant/oauth_apps/routes.clj

Adds a route to check if the platform OAuth token is still good.
This is useful to check if the token needs to be refreshed.
Returns JSON with `expires_in`, `scopes`, and `token_type`.

Add a route to get token info

---

client/www/pages/docs/backend.md

Noticed our example code didn't make sense so making a slight tweak!

[Docs] Update magic codes typo

---

server/src/instant/auth/oauth.clj

Possible fix for Issue [#1293](https://github.com/instantdb/instant/issues/1293)

[bugfix] Apple changed OpenID metadata

---

client/www/data/docsNavigation.js

What it says on the tin! Very easy win to make this more discoverable

[Easy][Docs] Move using llms higher up

---

client/sandbox/admin-sdk-express/src/index.ts
client/www/components/dash/Sandbox.tsx
server/src/instant/admin/model.clj

Support create on admin-sdk

---

server/src/instant/auth/oauth.clj

A continuation of #1294 that fixes web redirect oauth flow

Fix apple auth

---

client/www/components/dash/AuthorizedOAuthAppsScreen.tsx
client/www/components/dash/OAuthApps.tsx
client/www/pages/dash/index.tsx
client/www/pages/platform/oauth/start.tsx
server/src/instant/dash/routes.clj
server/src/instant/model/oauth_app.clj

Adds a user settings page that will show users the OAuth apps that they've authorized and allow them to revoke access.
Here's what it looks like:
https://github.com/user-attachments/assets/05b76b1d-0f22-4825-855e-f78bb758493b

Show users the oauth apps they've authorized

---

client/packages/core/src/instaml.js
client/sandbox/react-nextjs/pages/play/color.tsx

I notices that implicit attrs creation doesn't work with `create` op

Fix create not adding new attrs

---

server/resources/migrations/73_vae_uuids.down.sql

Need to drop the indexes before the function

Fix down migration

---

client/packages/cli/src/index.js

Per user request! Cleaned up the logic a little bit too to make it easier to get the fences to line up
**Before**
**After**

[CLI] Include etype in cli

---

server/src/instant/db/model/triple.clj
server/test/instant/db/model/triple_test.clj

Adds `day-of-week month day year` format to date parser.
Also adds some tests to check that what we parse matches up with what postgres parses.

Add Wed Jul 09 2025 format to date parser

---

client/packages/core/src/Reactor.js

This fixes a bug where we hold on to old mutations that have `add-attr` and then overwrite the attrs from the server with our old `add-attr` when we call `optimisticAttrs`.
You can sometimes hit the bug if you add a new attr to a namespace from the explorer and then try to modify the attr by e.g. indexing it. If we keep the `add-attr` mutation around for a query that hasn't seen a `refresh-ok`, then we'll apply the `add-attr` over the actual attr in `optimisticAttrs` and it will look like the attr hasn't been indexed.
The fix implemented in the PR does two things:
1. It filters out `add-attr/update-attr/delete-attr` that we have a newer versions of in `rewriteMutations`, if you provide a `processedTxId` to the function
2. It persists the result of `rewriteMutations` to `pendingMutations` …

Persist attr changes to pendingMutations

---

client/www/components/dash/explorer/EditRowDialog.tsx

Before (Production) & After (Local) Demo:
https://www.loom.com/share/d0ac4a58c41040339458942962acb664?sid=712d7aef-45d6-4a5a-924d-341bf1d3bee3

[www] Render `undefined` values as `null` in edit row dialog form

---

client/www/pages/pricing.tsx

Thought it would be nice to update the pricing page with the launch

[Pricing] Add platform to pricing

---

server/src/instant/db/permissioned_transaction.clj
server/src/instant/db/transaction.clj

Remove parent span to avoid sampling

---

server/flags-config/instant.schema.ts
server/src/instant/flags.clj
server/src/instant/reactive/session.clj

Added a flag so we can set custom handle receive overrides for specific apps. 

Make it possible to override config

---

client/packages/core/__tests__/src/store.test.js
client/packages/core/src/instaml.js
client/packages/core/src/store.js

fixes an error where deleting an object with a link to an entity with the same id recurses infinitely

fix core recursion error

---

client/www/pages/docs/patterns.md

[Docs] Add pattern for local vs prod app

---

client/www/pages/intern/overview.tsx
server/src/instant/intern/metrics.clj

Feels like we've been getting a burst of signups lately and wanted to add some metrics for us to see that.

[Metrics] Add signups to overview

---

server/scripts/clone_app.sql

Some fields from attrs were missing

Fix clone app script

---

client/www/pages/docs/modeling-data.md

We got some feedback that the docs where confusing about `unique` vs `indexed` -- hoping to clarify with this PR!

[Docs] Clarify index vs unique

---

client/sandbox/react-native-expo/app/index.js
client/sandbox/react-native-expo/app/play/ephemeral-demo.tsx
client/sandbox/react-native-expo/components/EphemeralAppPage.tsx

Thought it would be nice if we had this for React Native sandbox apps too
https://github.com/user-attachments/assets/d5896816-30e2-48ad-be41-4d5994d31d25

[Sandbox] Support ephemeral apps for react native

---

client/sandbox/react-nextjs/pages/play/order-flicker.tsx

https://github.com/user-attachments/assets/d833a435-6a12-4aaa-8986-1c064403aa7c

[Sandbox] Add repro for order flicker

---

client/packages/core/__tests__/src/utils/dates.test.ts
client/packages/core/src/utils/dates.ts
server/src/instant/db/model/triple.clj
server/test/instant/db/model/triple_test.clj

Adds support for another date format that postgres supports.

Add support for date format "8/4/2025, 11:02:31 PM"

---

client/packages/version/src/version.ts

Publishing date format changes from https://github.com/instantdb/instant/pull/1474

Publish v0.20.19 with fix for date format

---

client/pnpm-lock.yaml
client/sandbox/react-native-expo/package.json

Fixes typescript errors when trying to use react in the react-native playground package.

add @types/react to react-native-playground

---

client/www/pages/docs/auth.md

Following-up from #1463 , tweaking the auth docs to make it a little easier to follow

[Docs] Update auth docs

---

client/www/_posts/gpt_5_vs_opus_4.md
client/www/components/DemoIframe.tsx
client/www/pages/essays/[slug].tsx

@dwwoelfel @nezaj @tonsky @drew-harris

GPT-5 vs Opus 4.1 for Vibe-Coded Apps

---

client/www/_posts/gpt_5_vs_opus_4.md

Tweak essay

---

client/packages/version/src/version.ts

[tempfix] Bump version

---

server/src/instant/storage/s3.clj

This way we can flip to 100%. 

[tika] add a toggle for tika-enabled apps

---

client/www/components/dash/Sandbox.tsx
server/cljfmt.edn
server/flags-config/instant.schema.ts
server/src/instant/data/bootstrap.clj
server/src/instant/db/cel.clj
server/src/instant/db/instaql.clj
server/src/instant/db/model/attr.clj
server/src/instant/db/model/entity.clj
server/src/instant/db/model/triple.clj
server/src/instant/db/permissioned_transaction.clj
server/src/instant/db/permissioned_transaction_new.clj
server/src/instant/db/transaction.clj
server/src/instant/fixtures.clj
server/src/instant/flags.clj
server/src/instant/util/coll.clj
server/src/instant/util/date.clj
server/src/instant/util/io.clj
server/src/instant/util/test.clj
server/test/instant/db/cel_test.clj
server/test/instant/db/transaction_test.clj
server/test/instant/reactive/session_test.clj

See #1386 #1501 
Bug reports:
https://discord.com/channels/1031957483243188235/1404537793308524685
https://ui.honeycomb.io/instantdb/environments/prod/datasets/instant-server/result/6g4DbnoCvC2?tab=traces

Refactor permissioned transaction, take 2

---

client/www/lib/intern/llm-example/instant.schema.ts
client/www/lib/intern/llm-example/llm-rules-template.md

What it says on the tin! This should help reduce hallucinations and not hint the llm to use required

[LLM] Add option map and remove required

---

server/src/instant/reactive/ephemeral.clj

This should make us more resilient to issues where we can't connect to Hazelcast on startup.
Hazelcast was set to wait 5 minutes before giving up on joining the cluster, but we give up on startup after 1 minute. If we had an issue joining the cluster, then we would quit before hazelcast timed out, leaving the instance in a limbo state until eb decided to kill it.
Now we'll wait 2 minutes before giving up and we set all of the timeouts to lower values.
If the join timeout expires, then the instance will start its own cluster, which we can resolve by cycling the instances. While we're doing that, clients won't have a consistent view of presence.

Set hazelcast timeouts to expire before we give up on startup

---

client/www/pages/docs/auth/google-oauth.md

You probably forgot to change this in the docs 😊

Change clientId to clientName in signInWithIdToken in the docs

---

client/www/lib/intern/llm-example/llm-rules-template.md
client/www/scripts/gen-llm-rules.ts

Noticed we referenced `instant-rules` for the other editors/tools but this should be specific to Claude only

[Rules] Reference instant-rules for Claude only

---

client/packages/version/src/version.ts

Forgot to bump the version when merging #1584

bump version to v0.21.8

---

client/packages/core/src/rulesTypes.ts
client/www/components/dash/Perms.tsx

Report: https://discord.com/channels/1031957483243188235/1258878823529844766/1412446308492644494

Add link/unlink types to the dashboard editor

---

client/www/pages/docs/auth/clerk.md
client/www/pages/docs/auth/google-oauth.md
client/www/pages/docs/auth/platform-oauth.md
client/www/pages/docs/backend.md
client/www/pages/docs/common-mistakes.md
client/www/pages/docs/create-instant-app.md
client/www/pages/docs/index.md
client/www/pages/docs/patterns.md
client/www/pages/docs/presence-and-topics.md
client/www/pages/docs/storage.md

Asked Claude to do a sweep of our docs to fix typos and grammar issues!

[Docs] Fix typos and grammar

---

client/www/pages/docs/auth/google-oauth.md
client/www/pages/docs/auth/magic-codes.md
client/www/pages/docs/backend.md
client/www/pages/docs/common-mistakes.md
client/www/pages/docs/create-instant-app.md
client/www/pages/docs/devtool.md
client/www/pages/docs/instaml.md
client/www/pages/docs/instaql.md
client/www/pages/docs/modeling-data.md
client/www/pages/docs/patterns.md
client/www/pages/docs/permissions.md
client/www/pages/docs/presence-and-topics.md
client/www/pages/docs/storage.md
client/www/pages/docs/users.md

Noticed my previous pass wasn't as thorough. Did one more sweep and Claude caught a few more issues!

[Docs] More grammer fixes

---

client/www/pages/docs/using-llms.md
client/www/pages/tutorial.tsx

Got some feedback that the sse endpoint wasn't working the mcp does!

Update Zed config to use mcp endpoint

---

client/packages/version/src/version.ts

Bumping version to include new types for link/unlink! https://github.com/instantdb/instant/pull/1602

Bump version

---

client/packages/create-instant-app/template/rules/claude-rules.md
client/packages/create-instant-app/template/rules/cursor-rules.md
client/packages/create-instant-app/template/rules/other-rules.md
client/packages/create-instant-app/template/rules/windsurf-rules.md
client/www/lib/intern/llm-example/llm-rules-template.md

Found this helpful for appblox. Thought it would be nice to include here too. 

[small] add rules-of-hooks to instant rules

---

client/www/pages/index.tsx

Fix frontpage typo

---

client/www/components/dash/Perms.tsx
client/www/components/dash/TopBar.tsx
client/www/components/dash/org-management/RenameOrg.tsx
client/www/pages/dash/index.tsx
client/www/pages/dash/user-settings.tsx

mobile responsiveness

---

client/www/pages/intern/overview.tsx
server/src/instant/dash/routes.clj
server/src/instant/stripe.clj

Breaks down subscriptions by pro vs startup in the overview page.

Breakdown subscriptions by product in the overview page

---

client/packages/cli/src/index.js
client/packages/version/src/version.ts

Forgot to set an initial value for apps.

Fix cli when no orgs

---

client/www/pages/dash/index.tsx
server/src/instant/dash/routes.clj
server/src/instant/machine_summaries.clj

Somebody [mentioned it on Discord](https://discord.com/channels/1031957483243188235/1421062620810711050) and I thought it should be easy to implement and a fun idea. It was

Show active connection count on dashboard

---

client/www/components/dash/auth/Apple.tsx
client/www/components/dash/auth/Clerk.tsx
client/www/components/dash/auth/Google.tsx
client/www/components/dash/auth/LinkedIn.tsx

adds a background to all the auth dialogs so that they match the redirect origins panel and general patterns for the rest of the site. 
BEFORE: 
AFTER: <img width="645" height="804" alt="image" src="https://github.com/user-attachments/assets/3a8f92b5-2074-4492-8a56-821aed3aa2f9" />

fix auth card backgrounds

---

client/www/components/admin/AdminPage.tsx

fix dialog dark mode

---

client/www/pages/docs/using-llms.md

[Preview here](https://instant-www-js-add-expo-rules-docs-jsv.vercel.app/docs/using-llms#instant-rules)

Add expo rules to using-llms

---

client/www/components/ui.tsx

see https://github.com/instantdb/instant/pull/1788 for before and after images :)

fix the nav sidebar once and for all!

---

client/www/lib/muxVideos.ts

Updates cra into to remove --ai. 
@nezaj @dwwoelfel @drew-harris

Remove --ai from vid
