instantdb/instant

- README.md
Context: 
If you click the 'stars' button, it opens up a new tab unnecessarily. I wrapped it with an `a` tag. This makes a click no-op.
> [Readme] Wrap`stars` with links

- client/packages/core/src/Reactor.js
- client/packages/core/src/authAPI.js
- server/src/instant/runtime/routes.clj
Destroys the user's token on `auth.signOut()`.
Changes the signature of `signOut` to return a promise, so might require a version bump.
> Destroy token on app logout

- client/www/pages/tutorial.tsx
We got a light note from a user on HN: 
- Missing the word 'how' 
- The sentence 'Check out the walkthrough below on your left with the full code and preview on the right.' wasn't as clear on mobile 
I went ahead and: 
- Added 'how'
- Made it so in mobile it says 'Check out the walkthrough below, and the full code example right after.'
> Fix some grammar in the tutorial

- server/src/instant/reactive/session.clj
Logs the `cf-connecting-ip` for the request so that when we can see if errors for sessions are coming from multiple users or just the same user reconnecting.
> Log session origin for better error tracking

- client/packages/cli/index.js
- client/www/pages/docs/cli.md
- server/src/instant/dash/routes.clj
Adds 
- `npx instant-cli pull-schema <APP_ID>`
- `npx instant-cli pull-perms [APP_ID]`
- `npx instant-cli pull <APP_ID>` (pulls both)
Details
- Updates docs with more examples, replaces the "transitioning from dash" section
- A basic utility to grab the current prod attrs and best-effort write a `instant.schema.ts`.
- Accepts an app ID as an argument.
- Since we don't store type info in the db (yet!), everything's an `i.any()`.  Users will have to go and update them down the line when we support strong types.
To try it locally:
```sh
cd client/packages/cli
DEV=1 VERBOSE=1 ./bin/index.js pull-schema YOUR_APP_ID
DEV=1 VERBOSE=1 ./bin/index.js pull-perms YOUR_APP_ID
DEV=1 VERBOSE=1 ./bin/index.js pull YOUR_APP_ID
```
@nezaj @stopachka
> CLI pull v0

- server/src/instant/dash/routes.clj
`req->app-and-user!` defaults to `:owner`, we want to allow `:collaborators` to pull
> Relax role perms for CLI pull endpoints

- client/packages/cli/index.js
`pull` created an error.  We weren't setting `graph` as the default export in `instant.schema.ts`, therefore `push-schema` couldn't find it.
@stopachka
> Fix schema codegen

- server/src/instant/gauges.clj
- server/src/instant/reactive/invalidator.clj
- server/src/instant/reactive/session.clj
- server/src/instant/util/logging_exporter.clj
Adds metrics to track how long items are in the receive queue and in the worker queue.
Also tracks the receive-q length in instant.gauges. To support this without cyclic-dependency errors, you use `gauges/add-gauge-metrics-fn` to register a function that will run whenever the gauges are calculated and should return a list of `:path, :value` maps. It returns a cleanup function you can call on `stop`.
> Track how long things are queued

- client/www/data/tutorial-snippets/todos-add-react.tsx
- client/www/pages/tutorial-examples/1-todos-add.tsx
- client/www/pages/tutorial-examples/2-todos-edit.tsx
- client/www/pages/tutorial-examples/3-todos-attributes.tsx
Feedback from an Instant Hacker: 
> Hey there - really enjoying InstantDB - quick call out, on your [https://instantdb.com/tutorial](https://t.co/JPqEwHoxcs) page you may want to add in "use client"; at the top of the page.tsx example on the right. 
This makes sense; since we are explaining this is a NextJS app, it would be good to include the 'use client' directive. 
> [tutorial] add use client directive to the tutorial example code

- server/.clj-kondo/config.edn
- server/src/instant/reactive/session.clj
- server/src/instant/util/tracer.clj
- server/test/instant/reactive/session_test.clj
Keeps track of all the outstanding `event-fut` from `handle-receive` so that we can cancel them in `on-close`.
This will prevent races where a session joins a room after the on-close is called, leaving an orphaned session-id in the room that never gets removed.
Canceling all of the pending futures can be noisy, because any in-progress sql queries will throw interrupt exceptions. To prevent a bunch of errors from showing up in the logs, I added a new `tracer/with-exceptions-silencer` that we can use to prevent spans from being marked as exceptions. It will add a `silenced-exception` attribute so that we have some ability to debug if the silenced exceptions are causing problems.
> Cancel all pending operations in `on-close`

- server/Makefile
While running the docker compose application, if `docker-compose` command is not found, use `docker compose`.
> docker compose makefile improve

- client/packages/core/__tests__/src/instaml.test.js
- client/packages/core/src/instaml.js
- client/packages/core/src/instatx.ts
Fixes a problem where you can get an error when the attrs have not finished initializing before you call `transact` with a lookup (https://github.com/instantdb/instant/issues/42).
This change will optimistically generate an attr for the lookup if we don't have it locally. Just like the regular attrs, it will be
> Generate lookup attrs optimistically

- client/packages/core/src/utils/uuid.ts
Wraps the uuid generator with our own function so that users don't have to import `@types/uuid` to get a type for `id`.
Fixes https://github.com/instantdb/instant/issues/36
> Wrap `id` so that it exports the type

- client/packages/core/src/Reactor.js
If a user's token was revoked, we would never clear the `user` object out of localstorage so it would look like they were still logged in.
With this change, we will unset the current user if `init` returns a user not found error.
> Remove current-user when the token is bad on init

- client/www/components/ui.tsx
- client/www/lib/muxVideos.ts
- client/www/pages/index.tsx
There were to 'jittery' bugs:
- We didn't have widths on our logo and yc icon. This led to a horizontal jitter
- I also realized our blurup for the video was too dark. It's because it was using an image from the wrong thumbnailTime. I updated it. 
@nezaj @dwwoelfel @markyfyi @reichert621 
**Before**
https://github.com/user-attachments/assets/b7a06393-ee50-4e16-976d-2b8c2fd4eedc
**After**
https://github.com/user-attachments/assets/d68396f9-c357-4e46-ad7c-ccd3f8777b47
> [index] reduce jitter from SSR

- server/src/instant/db/model/attr.clj
Fixes a bug where duplicate `add-attr` tx-steps would cause the transaction to fail.
The bug was introduced yesterday when I fixed the problem with `lookup` not working until `init` finished: https://github.com/instantdb/instant/commit/ef8b6b5811b99cfb31480d7d6ea59dd4de5e90a3
Now we deduplicate those on the server.
> Fix bug where duplicated attrs would cause transaction to fail

- .gitignore
- server/src/instant/config_edn.clj
If you create a `server/resources/config/overlay.edn`, we'll merge the values there with the values we normally pick up from config. Useful for adding small local-only changes to the config.
> Add support for `config/overlay.edn` for local overrides

- client/packages/cli/index.js
`id` is implicit and managed at the system-level.  Users shouldn't have to define it in the schema file, and we shouldn't generate it for them, either. ;)
> [schema][cli] don't codegen id attr

- server/src/instant/dash/routes.clj
`id` attr is automatically generated, so omit adding it twice if the user explicitly defined it
> [cli][schema] Skip id attr name when applying schema

- client/www/components/dash/explorer/Explorer.tsx
Right now if you select a namespace in the dashboard explorer, and then refresh the page, it reverts to selecting the first namespace in the app db.
This PR adds a query param that persists the selected namespace id as `ns`.
> Persist selected namespace in dashboard explorer

- server/src/instant/db/instaql.clj
- server/src/instant/db/model/attr_pat.clj
Fixes the query validation error where the user expected a link in the query, but the attr is not a ref, e.g.
```
{users: { handle: {} }}
```
It also makes the server return a validation error in this case instead of treating it like a attr that hasn't been defined yet.
> Fix query validation errors

- client/www/pages/docs/showcase.md
Didn't add a title in the previous PR which rendered `undefined` in the head tag. It would be nice if we could default to the label in the docs navigation instead but can make a fix for that later
> [Docs] Add showcase title

- client/sandbox/react-nextjs/pages/play/stickers.tsx
- server/src/instant/core.clj
- server/src/instant/jdbc/wal.clj
- server/src/instant/reactive/invalidator.clj
- server/src/instant/util/logging_exporter.clj
Adds reconnect logic when the wal listener connection fails.
We don't want to miss any updates while the connection is down, so this PR switches our replication slot from temporary to non-temporary.
When the slots were temporary, they automatically got cleaned up when the connection closed. We need to make sure that we clean up old slots so that postgres can delete the wal logs.
There are two things we do to keep on top of inactive slots:
1. There is a new shutdown handler that will call `stop` on the invalidator, which will shutdown the wal listener and drop the slot. It works if you hit Ctrl+c locally, but I'll have to monitor to see if it actually works in elastic beanstalk.
2. There is a background process that will check for inactive slots every hour and drop them if they're still …
> Reconnect the wal listener on connection errors

- server/src/instant/db/datalog.clj
- server/src/instant/db/instaql.clj
- server/test/instant/db/instaql_test.clj
Allows a query like `{:users {:$ {:where {:id {:in []}}}}}` to succeed (with an empty set of join rows).
It would be more efficient to skip the trip to the db here, but I worry about how complicated that will make queries where a nested ref query has an empty `in` array or where there are multiple sibling top-level queries.
> Allow empty `:in` in the where clause

- server/src/instant/util/logging_exporter.clj
This should make it easier to search and view the logs in production because the exceptions won't span multiple separate log lines.
> Strip newlines when logging to stdout in production

- client/packages/core/__tests__/src/instaml.test.js
- client/packages/core/src/instaml.js
Fixes a bug on the client where we would add duplicate ref attrs if you tried to add the reverse and forward ref in the same transaction, here's a simple example:
```js
const userId = id();
const bookId = id();
db.transact([
tx.users[userId].update({}).link({books: bookId}),
tx.books[bookId].update({}).link({users: userId})
]);
```
We would try to create two ref attrs for that transaction, which would throw an error because two idents tried to be `users.books` (or `books.users`).
Now we use a reduce to build up the attrs and we don't run into that problem.
Fixes https://github.com/jsventures/instldraw/issues/3
> Fix for duplicate ref attrs

- client/www/pages/docs/auth.md
- client/www/pages/docs/auth/magic-codes.md
Been seeing asks for using auth with vanilla js and with clerk. We have examples of this in github and figured it may be nice to link to them from the docs
> [Docs] Add links for clerk and vanilla js

- .github/workflows/clojure.yml
Now that we're open source, the repo gets unlimited action minutes.
Runs the clojure tests on every push so you don't have to open a PR to see what the build thinks of your changes.
> Run clojure tests on every push

- client/www/components/dash/explorer/EditRowDialog.tsx
- client/www/components/ui.tsx
- client/www/lib/schema.tsx
- client/www/lib/types.ts
Makes a couple of changes to add/edit row:
1. If we don't have a value for the field, looks up the type from the attr's inferred types.
2. Adds an `id` field for the `Add row` dialog and prepopulates it with an id. There's a little `refresh` button you can click to get a new one or you can paste in your own. Will refuse to save with a handy error message if the uuid is invalid.
a. I set tabIndexes so that the first editable row would be the first thing selected instead of the id row
> Use inferred types to set default type for add row

- server/resources/config/dev.edn
Afaik we use the same instant-config app id in both dev and prod. I went ahead and updated the config dev.edn 
> [quickfix] Set instant-config-app-id for dev

- server/src/instant/reactive/ephemeral.clj
- server/src/instant/reactive/session.clj
- server/src/instant/util/tracer.clj
We've been getting more traffic since launch and blowing out our honeycomb usage. Most of the logs come from
* [refresh-rooms](https://ui.honeycomb.io/instantdb/environments/prod/datasets/instant-server/result/i3z8na4YC5s/a/5VpV3Zzwg51/Total-Traces?hideCompare)
* [set-presence for handle-receive/handle-event](https://ui.honeycomb.io/instantdb/environments/prod/datasets/instant-server/result/d1bgcGrq6Lo?hideCompare)
This PR increases the sample rate for these
> Increase honeycomb sample rate

- client/sandbox/vanilla-js-vite/src/main.ts
The final step in the example of the vanilla authn logic was missing an `await` inside the async function verifying the login code.
> Add missing await to authn example

- server/src/instant/reactive/ephemeral.clj
- server/src/instant/reactive/session.clj
- server/src/instant/util/tracer.clj
We reduced events from ~17M → ~12M [via sampling refresh-rooms and set presence](https://github.com/instantdb/instant/pull/109). The problem is `handle-receive` and `handle-events` [generate a ton of subtraces](https://ui.honeycomb.io/instantdb/environments/prod/result/bGk9tRFm9tk?hideCompare) for querying/book-keeping. So let's just wholesale increase the sample rate for all event types
> [Honeycomb] Increase honeycomb sample rate

- server/src/instant/db/dataloader.clj
- server/src/instant/util/exception.clj
Gives a better error when you call data.ref on a non-existent ref.
Fixes a bug where the get-ref dataloader wouldn't throw exceptions.
Before:
```json
{
"type": "permission-evaluation-failed",
"message": "Could not evaluate permission rule for [\"users\" \"create\"]. You may have a typo.  Go to the permission tab in your dashboard to update your rule.",
"hint": {
"rule": [
"users",
"create"
]
}
}
```
After:
```json
{
"type": "permission-evaluation-failed",
"message": "Could not evaluate permission rule for `users.create`. Record not found: attr. Go to the permission tab in your dashboard to update your rule.",
"hint": {
"rule": [
"users",
"create"
],
"error": {
"type": "record-not-found",
"message": "Record not found: attr",
"hint": {
"args": [
"users",
"creator"
],
"record-type": "attr" …
```
> Better cel errors for data.ref

- client/www/components/dash/Onboarding.tsx
- client/www/components/dash/Storage.tsx
Adds `loading` in a couple of places so that you can't double-click the button and can see that something is happening. Fixes #106
> Add loading to a couple of buttons

- client/packages/core/src/Reactor.js
- client/packages/core/src/WindowNetworkListener.js
- client/packages/core/src/index.ts
In a chrome extension service worker, `window` is not defined. But websockets, BroadcastChannel, and IndexedDB _still_ work. 
This means we can have a light lift and support chrome extensions. I updated our call in Reactor, to handle the chrome extension case.   I checked web, native, and a chrome extension to see that everything works. 
To check the chrome extension, I used this repo from tph: https://github.com/ayoung19/buzz-extension
We may want to extract out a basic chrome extension, and keep it in sandbox for development.
> [chrome-ext] Make Reactor run in a chrome extension

- server/src/instant/util/json.clj
Fixes encoding null and cel expression values to JSON so that the sandbox doesn't break on rules that return null.
> Encode more cel values to JSON

- server/src/instant/db/cel.clj
- server/test/instant/db/instaql_test.clj
If you do `user.isAdmin` in your rule, that will return a NullObject from cel and we'll evaluate that to truthy.
This change coerces NULL_VALUE to nil before we return from `eval-program!`
> Coerce NULL_VALUE to null in cel check

- client/www/components/dash/AppAuth.tsx
- client/www/pages/docs/auth/clerk.md
I updated `Sessions` and `API Keys` links to deep-link into Clerk's dashboard. Found a nice trick they used in clerk docs, which lets us go to the active app, on those specific pages! 
Reference on Clerk:  https://github.com/clerk/clerk-docs/pull/1512
@dwwoelfel
> [clerk] use clerk last-active links

- server/src/instant/admin/routes.clj
- server/src/instant/db/instaql.clj
- server/src/instant/db/model/attr_pat.clj
- server/test/instant/db/instaql_test.clj
Hunter from Palette pointed out a bug introduced by strong init. If you have queries with an attribute that doesn't exist, i.e: 
```
{goals: {todos: {}}
```
But `todos` doesn't exist, we _should_ return an empty array. 
But in the admin SDK, we added a change which would throw. 
This catches that specific throw. We do it in instaql.clj. I just moved the logic into attr_pat.clj, and use it in both places 
> [strong-init] add guarded ref attr pat in admin routes

- .github/workflows/clojure.yml
- server/docker-compose.yml
- server/refinery/config.yaml
- server/refinery/rules.yaml
- server/src/instant/config.clj
- server/src/instant/util/tracer.clj
Adds refinery to do honeycomb tail sampling for us.
Our configuration is set up to send all events that have an `error` property, and throttle all other events so that we send a max of about 30/second. That should keep us below our Honeycomb plan limits.
The refinery container sits next to the server container and we redirect all of our honeycomb API calls to the refinery container. Then the refinery container makes a decision on what to send based on the rules we defined in `server/refinery/rules.yaml`. More docs on those [here](https://docs.honeycomb.io/manage-data-volume/sample/honeycomb-refinery/sampling-methods/) and [here](https://github.com/honeycombio/refinery/blob/main/rules_complete.yaml).
We use a `EMAThroughputSampler` to set a target throughput for non-errors. It uses the …
> Add refinery for honeycomb sampling

- server/refinery/rules.yaml
Had the wrong environment, it should have been "prod" instead of "production".
Tested in production and it's sampling now.
> Fix the refinery sampler rules

- .github/workflows/js.yml
- client/packages/core/__tests__/src/instaml.test.js
- client/packages/core/src/instaml.js
- server/src/instant/admin/model.clj
- server/src/instant/db/model/triple.clj
- server/src/instant/jdbc/pgerrors.clj
- server/src/instant/util/exception.clj
- server/src/instant/util/string.clj
- server/src/tool.clj
- server/test/instant/admin/routes_test.clj
If the user has a unique ref attr with cardinality one, this allows them to use `lookup` to update an entity in the namespace using `forward-name.id` as the lookup key.
Here's an example:
If the `user_prefs` namespace has a unique link to `users`, then the developer can update `user_prefs` with:
```js
tx.user_prefs[lookup("users.id", userId)].update({new_pref: 'new-value})
```
Updated the backend to support this with the admin api.
I attempted to solve the problem where you can't create a new entity with a lookup set the lookup value at the same time, but could not find any easy solutions, so I just gave it a better error message. Now when you do:
```js
db.transact([
tx.users[lookup('handle', 'h')].update({handle: 'h'})
]);
```
It will throw a validation error with message: `"Updates with …
> Lookup by a ref attr

- client/packages/core/__tests__/src/instaqlInference.test.js
- client/packages/core/src/Reactor.js
- client/packages/core/src/instaql.js
- client/packages/core/src/schema.ts
- client/packages/core/src/store.js
- client/packages/core/src/utils/linkIndex.ts
- client/sandbox/react-nextjs/pages/play/checkins.tsx
To maintain type-safety, honor the specified schema and not the synced attrs when determining whether to return one/many results.
> String Init: Use schema instead of attrs when resolving cardinality

- client/packages/core/__tests__/src/instaml.test.js
- client/packages/core/src/instaml.js
- server/src/instant/admin/model.clj
- server/test/instant/admin/routes_test.clj
Allows `lookup` to succeed if the attr with a dot in it exists instead of assuming it's a ref lookup.
> Don't assume periods are refs in lookups if the attr exists

- client/www/pages/dash/index.tsx
- server/src/instant/dash/routes.clj
- server/src/instant/jdbc/pgerrors.clj
- server/src/instant/model/app.clj
- server/src/instant/model/app_member_invites.clj
- server/src/instant/superadmin/routes.clj
**1)** Added An endpoint to initiate transferring an app. This will send an email like so: 
**2)** A user can then login, and claim ownership of the app: 
**3)** The superadmin also has an API to _revoke_ access
Notes: 
1. Right now, only the superadmin api lets you create a 'creator' transfer. Eventually we could enhance our normal invitation flow to also allow this. 
> [superadmin] support for transferring apps 

- client/sandbox/cli-nodejs/instant.schema.ts
- server/src/instant/admin/routes.clj
- server/src/instant/dash/routes.clj
- server/src/instant/model/schema.clj
Refactoring our schema functions into a single namespace. This way we can use them in both `dash-routes` and `superadmin`
> [schema] move schema ops into a shared namespace

- client/www/pages/docs/strong-init.md
I guess `todos` namespace was forgotten in db.tx.
> Add missing todos namespace

- server/src/instant/db/cel.clj
- server/src/instant/db/instaql.clj
- server/src/instant/db/model/entity.clj
- server/src/instant/db/permissioned_transaction.clj
- server/src/instant/jdbc/sql.clj
- server/src/instant/model/rule.clj
- server/src/instant/util/coll.clj
- server/src/instant/util/io.clj
- server/test/instant/db/transaction_test.clj
_Easier to review with whitespace off https://github.com/instantdb/instant/pull/204/files?w=1_
We can get into a situation in `permissioned-transaction/transact!` where all of the db connections are in use, but we're waiting on a connection to fetch data for permissions before we can close our connection, leading to a deadlock. Eventually the connection will time out and things will proceed, but the db will be locked up in the meantime.
The solution is to use the connection we opened for all queries in the transaction, but we do a lot of parallel querying (`O(count(eids))`) to get permissions information and a single connection might hurt throughput. This PR adds pre-fetching so that we can only need to run 3 queries to get permissions (though we could get that down to 2 (or maybe even 1 …
> Use a single db connection for transact

- client/packages/core/src/Reactor.js
- server/src/instant/lib/ring/websocket.clj
- server/src/instant/reactive/session.clj
This PR: 
1. On the client, we make sure to close the previous websocket connection, when we are about to start a new one 
2. On the server, we started a ping-pong mechanism, where we detect idle connections and proactively kill them 
Kosmik reported a curious bug: If you went offline and went back online, you would get a phantom presence object. What happened?
The fundamental bug was this: tcp connections stayed 'active', _even when we went offline_. 
We assumed that the underlying websocket would close when we went offline. But this is not the case. Google Chrome does not close the socket automatically when you go offline. [1] 
What happens to idle TCP connections really depends on the machine [2]. Sometimes it can take minutes to close the connection.
I did two things in this PR: 
**1) …
> [phantom-presence] handle stray websockets

- client/packages/core/src/utils/object.js
- client/sandbox/react-nextjs/pages/play/patch.tsx
Fixes https://github.com/instantdb/instant/issues/54.  I added a util to the `patch` example to replicate the case outlined.
Our logic in `immutableDeepMerge` was plain wrong, and we weren't deleted properties that were "nulled" out.
> [core][merge] Fix client deep-merge null logic

- client/packages/core/src/Reactor.js
- client/packages/core/src/utils/PersistedObject.js
Fixes a bug where we were resolving query data before folding in pending mutations.  This was due to us resolving queries after loading cached query responses, but not waiting for cached mutations.
Context: https://discord.com/channels/1031957483243188235/1148284450992574535/1280807824334782484
> Fix muts offline bug

- server/src/instant/dash/routes.clj
Archil reported a bug, where they were not able to invite a team member to their app. 
This is because of a recent change to `accept-post`. I added the `:else` keyword to `condp` by accident. 
@dwwoelfel @markyfyi @nezaj
> [bugfix] fix the 'accept' bug for collaborators

- client/www/pages/docs/auth/clerk.md
The package name is `@clerk/nextjs` and not `@clerk/next`
> Fix Typo in Clerk Auth Docs

- client/packages/cli/index.js
- client/packages/cli/package.json
- client/packages/core/__tests__/src/instaqlInference.test.js
- client/packages/core/__tests__/src/schema.test.ts
- client/packages/core/src/schema.ts
- client/pnpm-lock.yaml
- client/sandbox/admin-sdk-express/src/with-schema.ts
- client/sandbox/cli-nodejs/instant.config.ts
- client/sandbox/cli-nodejs/instant.schema.ts
- client/sandbox/react-native-expo/app/play/colors-schema.js
- client/sandbox/react-nextjs/pages/play/color-schema.tsx
- client/sandbox/vanilla-js-vite/src/schema.ts
- client/www/pages/docs/cli.md
- client/www/pages/docs/patterns.md
- client/www/pages/docs/schema.md
- client/www/pages/labs/platform_demo.tsx
Change how we do app IDs in CLI/schema.
- Completely decouple schema.ts/`i.graph` from the concept of app IDs.  They're exclusively handled at a higher level in the CLI.
- Since we can no longer read an app ID from the schema, I modified the CLI to look for `process.env.INSTANT_APP_ID`.
- Update docs, examples, and error messages accordingly.
- Also add preliminary support for reading named IDs in `instant.config.ts`.  Users with multiple named apps can specify one in the CLI, e.g. `instant-cli pull dev`, where `dev` is a key in a map of names to IDs. **Note, I'm not documenting/announcing this feature until I get feedback from our core testers.**
Once we land this, I'll announce the breaking changes in Discord.
How to test:
cd into `sandbox/cli-nodejs` and try these out
1. Run a command …
> Env app IDs

- server/src/instant/lib/ring/websocket.clj
We get some IOExceptions, when trying to send a ping to a socket that becomes closed. 
Afaik this can happen due to a race condition: the socket closes while we are running a sendPingBlocking 
[Example trace 1](https://ui.honeycomb.io/instantdb/environments/prod/datasets/instant-server/result/2FA3CtCUCka/trace?source=query&trace_id=1d3131aa8fee0d361069181df4ad87ef)
[Example trace 2](https://ui.honeycomb.io/instantdb/environments/prod/datasets/instant-server/result/2FA3CtCUCka/trace/jbnpdnkjv4A?fields[]=s_name&fields[]=s_serviceName&source=query&span=080bc468fb0979b3)
I say we suppress these errors, as they are expected. Open to other ideas though. 
@dwwoelfel @markyfyi @nezaj
> [fix] suppress IOException errors on sendPingBlocking

- client/packages/cli/index.js
- client/www/pages/docs/cli.md
Enhancing CLI to support CI/automation.
1. Adds a `--print` flag to `login` so that a user can grab their auth token for later consumption.
2. Updates CLI actions to check for `INSTANT_CLI_AUTH_TOKEN`, similar to how we handle `INSTANT_APP_ID`.  This is useful for customers in build automation envs like Vercel or GHA.
> CLI env auth

- client/www/pages/docs/strong-init.md
**I am still not 100% sure** but I tried to make a few corrections in the `useQuery` code snippet.
- Add missing unclosed curly bracket `}` in the `useQuery`.
- Add "before" code and use `firstUser` instead of undefined `user` variable. 
- For "after" code, use `data.users` instead of undefined `user` variable. (I am still not sure if `data.users` will really return a single object instead of an array)
> Update useQuery code snippet

- .github/workflows/js.yml
- client/package.json
- client/packages/admin/src/index.ts
- client/packages/core/src/coreTypes.ts
- client/packages/core/src/helperTypes.ts
- client/packages/core/src/index.ts
- client/packages/core/src/instatx.ts
- client/packages/core/src/queryTypes.ts
- client/packages/core/src/schema.ts
- client/packages/core/src/schemaTypes.ts
- client/packages/core/src/utils/linkIndex.ts
- client/packages/react-native/src/index.ts
- client/packages/react/src/Cursors.tsx
- client/packages/react/src/InstantReact.ts
- client/packages/react/src/InstantReactWeb.ts
- client/packages/react/src/index.ts
- client/packages/react/src/init.ts
- client/packages/react/src/useQuery.ts
- client/sandbox/react-nextjs/pages/play/checkins.tsx
Take all of our schema-related types out of the `i` namespace.  This improves intellisense and autocomplete, and may help us bypass some tricky type resolution errors.
> De-namespace schema types

- client/packages/core/src/Reactor.js
- client/packages/core/src/presence.ts
https://discord.com/channels/1031957483243188235/1281153699179135027
```
Right now we only get peer ids for other users, which forces us to maintain our own user.peerId  to be able to properly do multiplayer.
This is because the same user can be connected with more than one client, so we can't rely on the user.id  for that matter.
Exposing the current user's peerId would allow to uniquely identify users no matter what
```
> Expose peerId in presence user and peers objects

- client/packages/core/src/Reactor.js
We don't cache `dataForResult` right now. This means that when we render in dev, we get: 
1. 1 call for dataForResult from notifyOne
2. 2 calls for `dataForResult`, when running `useQuery`
This is a very light cache for dataForResult; there's still going to be false positives [1]. _But_ this will remove the 2 unnecessary in dev, and 1 in prod. Here's how it looks from a flame graph: 
**Before**
**After** 
Lots moar coming! 
@nezaj @dwwoelfel @markyfyi 
[1] Eventually, we should really look into turning a bunch of our objects into observables. It would be _so_ cool if we could quickly derive whether a `dataForResult` is stale or not, based on whether it's dependents have changed.
> [perf][1] cache dataForResult

- client/packages/core/src/schemaTypes.ts
- client/sandbox/react-nextjs/pages/play/checkins.tsx
When resolving an entity extended with `.asType`, we ignore the attr defs.   This is annoying because it forces the user to define types in two spots.  This change modifies `.asType` to merge the provided generic with the entity's original attr def.
> Merge EntityDef::asType with attrs

- client/packages/core/src/Reactor.js
- client/packages/core/src/utils/PersistedObject.js
- client/packages/core/tsconfig.json
- client/packages/react-native/tsconfig.json
- client/packages/react/tsconfig.json
In our previous perf improvement, we lost one advantage: 
Consider the following scenario: 
1. We load everything from storage
2. Afterwards, we get a `useQuery`
In this scenario, there would be no data for `getPreviousResult`, since 1. would not have done a `notifyOne`. 
I circumvented this problem by making the cache a bit smarter. Now, we run the `dataForQuery` in _both_ `notifyOne` _and_ `getPreviousResult`. If those calls run on the same 'version' of querySubs and pendingMutations, they return from the cache.
**Before**
**After** 
(No change)
> Improve dataForResult cache

- client/packages/core/package.json
- client/packages/core/src/store.js
- client/pnpm-lock.yaml
Immer autofreezes objects. When the object is really large, this gets more and more costly. I switched us to mutative, which does not rely on auto-freeze. [They have a comparison about immer vs mutative here](https://mutative.js.org/docs/extra-topics/comparison-with-immer). 
I made a bunch of transactions in our perf tester. 
**Before** 
[many_tx_immer.json](https://github.com/user-attachments/files/17065226/many_tx_immer.json)
A single transaction ontop of the bench query on immer is about 8ms. As you add more pending transactions, it grows to about 40ms.
**After** 
[many_tx_mutative.json](https://github.com/user-attachments/files/17065227/many_tx_mutative.json)
Mutative is about 3ms on a single transaction. As I add more pending transactions, the size _seems to stay_ at 3ms! 
@dwwoelfel …
> Use mutative instead of immer

- client/packages/core/__tests__/src/data/zeneca/attrs.json
- client/packages/core/src/Reactor.js
- client/packages/core/src/instaql.js
- client/packages/core/src/store.js
**This PR makes queries ~2.7x faster** 
Say we had a query like `{ posts: {} }`. This would produce a datalog query like:
```clojure
[[?id :posts/id] 
[?id ?attr ?v]]
```
datalog would end up taking up to 25ms to finish this query. Likely this is because our join algo needs more tuning. Instead, I changed it so: 
1. datalog _only_ queries for eids. 
2. Once we have eids, we 'generate' the object manually
**Before**
**After**
**Note:** In both instances `query` is a bit contaminated by a react update. Afaik react starts rendering when we run `cb()`, and for some reason the profiler counts it as part of `query`. I am not sure why. For this demo I just made React return null, so we saw the results closer to what `query` is actually doing …
> [perf] improve local query perf 2.7x

- client/www/components/dash/explorer/EditRowDialog.tsx
[Two users](https://discord.com/channels/1031957483243188235/1148284450992574535/1286330010818576486) noted that when you use the schema editor we set booleans to true by default. We should actually set it to false by default so users don't accidentally turn it on when editing the row.
> [Dashboard] Set boolean default to false

- client/packages/cli/index.js
Provides a fix for #250.
I also thought it would be nice to let `-v` work for version. (previously you would have to use uppercase V, which was not consistent with our other options)
> [instant-cli] Update version command

- client/www/components/dash/explorer/EditRowDialog.tsx
[Alfonso](https://discord.com/channels/1031957483243188235/1148284450992574535/1285180253056143441) reported only positive numbers were allowed for numeric types. 
This PR adjusts the logic to 1) use a number input for numeric types and 2) improve our regex for to be more comfy for allowing negatives and decimals
> [Dash] Better numbers

- client/www/pages/docs/cli.md
[Felix](https://discord.com/channels/1031957483243188235/1148284450992574535/1287467897660116993) noted we have a typo in the docs about our environment variable name for Vite.
`VITE_PUBLIC_INSTANT_APP_ID` -> `VITE_INSTANT_APP_ID`
> [Docs] Correct vite env name

- client/packages/core/src/devtool.ts
- client/www/pages/_devtool/index.tsx
- Prominently display the app ID.
- Fixed the improperly-sized focus ring in Devtool toggler widget.
- Removed `Esc`'ing out of Devtool.   Toggle the popup with `ctrl+shift+0`.
- Richer error messages, including displaying the server error when `/dash` fails.
> Client Devtool UI polish

- client/packages/cli/index.js
- client/sandbox/cli-nodejs/instant.schema.ts
- server/src/instant/dash/routes.clj
- server/src/instant/model/schema.clj
- server/src/instant/superadmin/routes.clj
Adds some logic to our schema change planner to bail when a user defines a link twice.
```
~/instant/client/sandbox/cli-nodejs λ INSTANT_CLI_DEV=1 px instant-cli push -y 
Planning...
Failed to update schema.
Validation failed for schema
schema: Duplicate entry found for attribute: tags->posts. Check your schema file for duplicate link definitions.
schema: Duplicate entry found for attribute: posts->tags. Check your schema file for duplicate link definitions.
```
Also fixes a bug where we weren't bailing `push perms` when `push schema` failed.
> Add validation to check for duplicate attrs

- client/packages/core/src/index.ts
- client/packages/core/src/queryTypes.ts
Somehow, we're getting type errors in the `.d.ts` files generated in our builds, but not in the source `.ts` files. 😱  I'm still looking into how/why, but shipping a fix in the meantime.
> Fix errors in generated d.ts files

- client/www/components/dash/Sandbox.tsx
[[One of our users]](https://discord.com/channels/1031957483243188235/1287593736930463856/1287926659915452476) was using the sandbox to debug and was confused by the return of `transact.` In the sandbox we extract out the `tx-id` but in actual instaml we don't.
This change makes the sandbox `transact` return match more closely to the real `transact`
> [Dash] Make sandbox transact return more similar

- client/www/pages/docs/index.md
- client/www/pages/docs/init.md
I notice users in Discord still asking about types and schemas.  This patch makes an effort to surface awareness of these features in our onboarding docs.
> Surface advanced features in docs

- client/package.json
- client/packages/admin/package.json
- client/packages/react-native/package.json
- client/packages/react/package.json
- client/pnpm-lock.yaml
- client/sandbox/perf_1/package.json
- client/www/package.json
Cleaning up the root package.json.  There's a bunch of unused and unnecessarily-hoisted packages, I don't remember how they got there.
I removed the `lint` script, because we don't use it.
I also pushed `@types/node` down into the packages that need it.  This will help avoid potential TypeScript/bundler resolution confusion down the line.
I'm saving RN for another patch, because RN. 😅
> Cleanup root package.json

- client/packages/admin/tsconfig.json
- client/packages/core/tsconfig.json
- client/packages/react-native/tsconfig.json
- client/packages/react/tsconfig.json
- client/tsconfig.base.json
Utilizes [`extends`](https://www.typescriptlang.org/tsconfig/#extends) to share common config across our core client packages.  I wanted to do `www` and `sandbox` too but they were all pretty different.
> Extract base tsconfig from client packages

- server/src/instant/runtime/routes.clj
If our oauth flow redirects to an external app, the redirect will leave the redirecting window dangling. In the case of Google, the last page they redirect from is a loading page, so it looks like the google page is loading forever.
With this change, we'll show a landing page that automatically opens the external redirect url. It also has a button in case the user clicks "Cancel".
The page looks like this:
Confirmed that it doesn't modify the oauth flow for expo.
> Show a landing page if the oauth flow redirects to external app

- client/www/pages/dash/index.tsx
- server/src/instant/dash/routes.clj
- server/src/instant/db/model/attr.clj
- server/src/instant/model/app.clj
- server/src/instant/model/rule.clj
[One of our users](https://discord.com/channels/1031957483243188235/1148286343638687786/1288277649805938729) asked if we could make it easy to clear apps. This is especially useful if someone is prototyping on a paid app, since it's not easy for them to re-create an app from scratch.
One thing that was strange was that the explorer would be stale after clearing the data. I get around this by doing a reload, but I'd be open to a better solution, just wasn't sure how.
It might also be nice to offer some more checkboxes / configuration for what things you want to clear, but I figured this is decent solution for now and if folks need something more customizable they will let us know.
I also held off on adding this to the cli-helper, just wanted to make sure this actually meets his needs for …
> [Dash] Add clear app to admin

- client/www/pages/_devtool/index.tsx
- client/www/pages/dash/index.tsx
[Cam](https://discord.com/channels/1031957483243188235/1288277649805938729/1289306430880350240) mentioned that having clear app in the devtool would be the most useful place. So this PR stubs an Admin section in the devtool
Not all the Admin actions in the dashboard makes sense here, for example, you probably don't want to delete the app in the devtool.
It would probably be better to have the Admin page more configurable so you could select which pieces you want. That feels like a bigger lift right now, and if more admin features are requested in the dev tool, I think we can take on a more elegant solution then.
**Authorized View**
**Insufficent Role View**
> [Dev tool] Add clear app to devtool

- server/src/instant/util/tracer.clj
Each time we do `~span-opts`, it will evaluate the form. This change ensures we only evaluate the form once per call to `with-span!`.
> Only evaluate span-opts once

- client/www/pages/docs/schema.md
Either do 
```ts
export default i.graph();
const g = i.graph():
export default g;
```
> docs(schema-as-code): fixed syntax error in default export of i.graph

- client/packages/react-native/src/index.ts
[One of our users](https://discord.com/channels/1031957483243188235/1148284450992574535/1289917835321278514) noticed we don't export `lookup` in React Native.
Let's add it in!
> [React Native] Add lookup to rn

- server/README.md
- server/src/instant/db/permissioned_transaction.clj
- server/test/instant/db/transaction_test.clj
Fix for view checks that were causing problems for some users.
The problem happened when an object was created and linked in the same transaction. We would try to run the `view` check on an empty object, which would fail.
Now we'll only run the `view` check if the object already exists, counting on the `create` check to reject the transaction if the user isn't allowed to create it.
To prevent more problems for users, we just log the results of the `view` check for now. Once we have some confidence that everything looks ok, we can turn it on.
> Fix view checks, make them warn-only for now

- .github/workflows/clojure.yml
- server/README.md
- server/dev-postgres/Dockerfile
- server/src/instant/core.clj
- server/src/instant/jdbc/wal.clj
- server/src/instant/reactive/invalidator.clj
- server/src/instant/util/test.clj
- server/test/instant/reactive/invalidator_test.clj
Adds an integration test to make sure that the invalidator picks up changes to the triples table.
Inspired by this small bug that I luckily caught before deploying the users table pr: https://github.com/instantdb/instant/pull/280/commits/a27e2497c6c2345053910d9f3b37d331056a0d1a. It would have broken invalidation.
Makes a couple of small changes to the invalidator:
1. You can start and stop it without setting global state. There's a `start-global` and `stop-global` we now use in `instant.core` that keeps the previous behavior.
2. The `kick-wal` helper writes to the `config` table, which is more effective than `pg_notify`.
> Add test that the invalidator is working

- .github/workflows/clojure.yml
- server/README.md
Builds an uberjar in CI so that we don't get surprised by a failure after merging to main.
> Build uberjar as part of actions

- client/packages/admin/src/index.ts
- client/packages/core/src/helperTypes.ts
- client/packages/core/src/index.ts
- client/packages/core/src/queryTypes.ts
- client/packages/react-native/src/index.ts
- client/packages/react/src/index.ts
- client/sandbox/react-nextjs/pages/play/checkins.tsx
Users wanted a way to quickly pluck a single entity's type from their schema, so I made `InstantEntity`. 💥
```ts
type Checkin = InstantEntity<
DB,
"checkins"
>;
```
But it's easy to imagine many cases where you want the entity with some links, so `InstantEntity` accepts an optional 3rd param specifying a "subslice" of InstaQL links relative to the entity. 🎉 ✨ 
```ts
type Checkin = InstantEntity<
DB,
"checkins",
{
habit: {
category: {};
};
}
>;
```
> Instant Entity helper type

- client/sandbox/cli-nodejs/instant.schema.ts
- server/src/instant/model/schema.clj
The schema planner doesn't account for a sneaky invariant: what if the user has a link def, but in the _opposite direction_ of one in the database?  As in, the forward and reverse identities are swapped.  Right now, we catch this, but throw a misleading "check your schema file for dupes" error.  In this change, I add some code to check for this case, and throw a (hopefully) more informative error.
To repro - go to `sandbox/cli-nodejs/instant.schema.ts` and swap the `forward` and `reverse` props of one of the links.
> Improved error messaging for conflicting link defs in schema.ts

- client/packages/admin/src/index.ts
- client/packages/core/src/helperTypes.ts
- client/packages/core/src/index.ts
- client/packages/react-native/src/index.ts
- client/packages/react/src/index.ts
- client/sandbox/react-nextjs/pages/play/checkins.tsx
Exports a helper for users who require a DB type prior to initialization.  For example, when using a DI framework that defers initialization.
Context: https://discord.com/channels/1031957483243188235/1289204418515832903
> instant db from schema hepler type

- server/src/instant/db/permissioned_transaction.clj
- server/src/instant/flags.clj
- server/test/instant/db/transaction_test.clj
Enables view checks in permissioned-transaction behind a feature flag.
Everything is looking good in the logs so far, if something goes wrong we can disable it for individual apps while we investigate.
> Enable view checks behind a feature flag

- client/packages/core/src/Reactor.js
- client/packages/core/src/index.ts
- client/packages/react/src/InstantReact.ts
- client/sandbox/react-nextjs/pages/play/query-once.tsx
- client/www/pages/docs/instaql.md
Adds `queryOnce` to our suite of client SDKs.  `queryOnce` is basically `useQuery`, but returns a promise instead of registering a subscription.
- `queryOnce` is a hack on top of `subscribeQuery`/`add-query`.
- Along the way, I implemented "true" un-subscription, i.e. sending the `remove-query` op to the server when we no longer need to listen to a query.  I updated the current `subscribeQuery` flow with this, too.  Credit to @stopachka for the idea.
I added an example (`/play/query-once`) to demonstrate various cases:
- `queryOnce` in `useEffect` on init
- `queryOnce` on an existing live subscription (the `add-query-exists` case)
- `queryOnce` with a new query
I'll add docs/docstrings once we're happy with the implementation!
> Query Once

- client/www/components/ui.tsx
- client/www/pages/dash/index.tsx
I noticed a few spacing issues on the admin page. 
- Labels and inputs felt too tight. Changed gap-1 to gap-2 
- The subheading font size felt bigger than the heading. The monospace also felt jarring. Changed them to be sans, and same sizes. 
- There was not bottom padding in danger zone. Added it. 
**Before** 
**After**
> [spacing] change up the spacing on the admin page

- client/packages/core/src/Reactor.js
- client/sandbox/react-nextjs/pages/play/query-once.tsx
@stopachka pointed out that `queryOnce` calls that fired before `init-ok` were timing out.  This is because we silently failed sending them over WebSocket (due to the connection not being in an authenticated state) and never tried again once a connection was established.  This change enhances `_flushPendingMessages` to send events for every pending `queryOnce` like we do with subs.
> Fix over-eager queryOnce case

- client/www/pages/docs/instaql.md
I liked that we included `pageInfo` but I thought it would be nicer to be more explicit that you would use `pageInfo` in a paginated case. The way the docs were written prior to this change may have given the impression that `pageInfo` is necessary for `queryOnce`
> [Docs] Add more context to query once

- client/www/data/tutorial-snippets/todos-update-delete-instant.tsx
- client/www/pages/tutorial-examples/2-todos-edit.tsx
- client/www/pages/tutorial-examples/3-todos-attributes.tsx
Just noticed tutorial's delete cases are broken because of typo `tx.message` instead of `tx.messages`
reproduction video and details: https://discord.com/channels/1031957483243188235/1148284450992574535/1291236006921637930
> fix: breaking typos in tutorials

- server/README.md
- server/src/instant/db/model/attr.clj
Handles simultaneous add-attr transactions that create the same attributes.
If we have multiple database transactions that are adding the same attrs, one of the transactions can fail with "Record not unique ident".
With this change, we'll do an upsert on the `id` and only throw if one of the fields on the ident or attr is different.
> Handle simultaneous add-attr

- .github/workflows/clojure.yml
- server/README.md
- server/src/instant/dash/ephemeral_app.clj
- server/src/instant/dash/routes.clj
- server/src/instant/db/cel.clj
- server/src/instant/db/instaql.clj
- server/src/instant/db/permissioned_transaction.clj
- server/src/instant/model/rule.clj
- server/src/instant/superadmin/routes.clj
- server/src/instant/util/date.clj
- server/src/instant/util/storage.clj
- server/test/instant/db/instaql_test.clj
- server/test/instant/db/transaction_test.clj
Adds support for `auth.ref` for querying off of the `$users` namespace in permissions rules.
This will allow for more flexibility in permission rules and make it easier to implement role-based permissions.
If you had a `capabilities` namespace with an `action` attr that linked to `$users`, you would protect the `tasks` ns with something like:
```json
"tasks": {
"allow": {
"view": "'view_tasks' in auth.ref('$user.capabilties.action')"
}
}
```
Also creates a new `CelMap` `deftype` so that we can store metadata like `ctx` and `etype` outside of the data in the map. `->cel-map` takes two arguments, the metadata and the object, then automatically cycles the object through ->json and <-json.
> Auth users ref

- server/src/instant/reactive/invalidator.clj
We were passing attr ids as uuids, which caused the invalidator to fail when it tried to call `UUID/fromString` on them.
> Fix $users invalidation

- client/packages/cli/index.js
I notice when starting a new project it may be easy to `npx instant-cli pull <APP_ID>`, edit some schema, and then be surprised that `npx instant-cli push` doesn't work, This is because you also need to create a `.env` file for `push` to know the app id, which I kind of expected the cli would handle for me if I already pulled earlier.
Figured we can just prompt the user if they want to create a `.env` file
> [CLI] Add .env file if it doesn't exist

- client/packages/core/src/Reactor.js
I think this was just a copy/paste typo because `roomId` isn't defined at this part of the file. I think the reason we didn't see an error is because of the weird way switches bleed into eachother in js.
> Fix roomId

- client/packages/react/src/Cursors.tsx
- client/www/pages/examples.tsx
- client/www/pages/examples/3-cursors.tsx
Adds ontouch handlers to `<Cursors>` so that they work on mobile.
When people look at the examples page on their phones, the cursors examples don't do anything.
Also tells the browser to load the iframes lazily, which should help shorten the delay for page interactivity. Lighthouse gave the old page a 68 in performance and the new a 75, so there's some evidence it helps.
Try it on your phone: https://instant-www-js-touch-jsv.vercel.app/examples?app=61daa7fa-fc4c-40a6-a9e4-6f1569a9f252#3-cursors
> Make cursors work with touch on mobile

- server/src/instant/data/resolvers.clj
- server/src/instant/db/model/triple.clj
- server/test/instant/db/transaction_test.clj
Cam reported a bug, where he was seeing 'stray' entities in instaql results. 
The root cause was the following:
If you have a `boards` namespace, and a `nodes` namespace. If the link was: `[boardId :boards/nodes nodeId]`. 
When a `node` was deleted, the link was not cleaned up. 
Looking into it, I realized there was a stray conditional. 
Added a test, and removed the stray conditional.
Once landed, will write a quick script to delete stray entities 🫡
> [delete-entity] fix automatic deletes on the value side

- server/docker-compose.yml
The switch to host mode made us unable to resolve `refinery` as an endpoint. Switching it to localhost makes it work.
> Fix refinery url

- server/src/instant/db/permissioned_transaction.clj
- server/src/instant/flags.clj
- server/test/instant/db/transaction_test.clj
There was an error when we tried to report the status of the view check in the trace. We were running it in admin-mode when it was disabled, so it was returning a map. When I flipped the flag to run it for real, it returned a boolean instead.
I think we can push forward with the view check, as it seems to be working as designed.
> Remove view check flag

- server/src/instant/reactive/ephemeral.clj
We have a worker that applies updates to the ephemeral store to hazelcast so that the transition from atom -> hazelcast will be smooth.
It can get backed up and throw `too many puts` errors, so this adds some extra workers.
Temporary until hazelcast is the default.
> More hazelcast sync workers

- server/src/instant/discord.clj
- server/src/instant/jdbc/wal.clj
- server/src/instant/stripe.clj
Sends wal alerts directly to the errors discord channel and `@` instanteam when we send it.
Adds an `agent` to send the messages in the background.
We now have the ability to do mentions in discord messages, so this also adds an `@instanteam` mention for new paying users and churns.
> Send wal alerts directly to discord

- client/packages/core/__tests__/src/instaml.test.js
- client/packages/core/src/instaml.js
- server/src/instant/admin/model.clj
- server/test/instant/admin/routes_test.clj
This handles adding optimistic attrs when a lookup is used in the link position.
If you use a lookup in a link before the attrs are loaded:
```
tx.users[userId].link({posts: lookup('number', 10)})
```
Then the request will fail with an attribute is not unique error.
> Optimistic attrs for lookups in the link value position

- client/packages/cli/index.js
One of our users put up a PR to increase the timeout of the CLI https://github.com/instantdb/instant/pull/318
I figured instead of making this an extra option, we can just cap it to 5 minutes, which is what Chrome uses https://github.com/nodejs/undici/issues/1373
Tested this with a local backend to ensure timeouts are respected!
> [CLI] Increase default timeout for CLI

- server/refinery/rules.yaml
We're just over the threshold at the current 30/second rate, lowering it to 25/second may nudge us under.
> Lower refinery goal throughput

- server/src/instant/jdbc/wal.clj
- server/src/instant/reactive/invalidator.clj
- server/test/instant/reactive/invalidator_test.clj
Updates the wal listener to use format_version 2 in wal2json. It produces one JSON object per tuple instead of one per transaction.
This should put less strain on the db connection when there is a very large update.
Before when there was a transaction, we would have something that looked like:
```js
{change: [
{table: "triples",...},
{table: "triples",...},
{table: "transactions", ...}]}
```
Now we'll get a stream of changes for one transaction:
```js
{action: "B"}
{action: "U", table: "triples", ...}
{action: "U", table: "triples", ...}
{action: "U", table: "triples", ...}
{action: "C"}
```
Our `produce` function is now stateful and will collect all of the changes between the "B" and the "C" to collect the set of changes for the invalidator.
> Wal2json v2

- server/src/instant/core.clj
- server/src/instant/health.clj
- server/src/instant/jdbc/wal.clj
Adds a page that will return a 500 if the wal unexpectedly restarts and isn't able to recover.
Each time the wal is interrupted, we'll set a flag in config for the machine to indicate that the wal is unhealthy. If we're able to restart, then we'll remove the flag. But if we restart a few times, then we'll stop removing the flag and leave it as unhealthy. In that case, someone will have to manually reset the config flag.
A new page at `/health/system` will return a 500 whenever the config flag is tripped.
> Health page for the wal

- server/deps.edn
- server/src/instant/jdbc/wal.clj
- server/src/instant/reactive/ephemeral.clj
- server/src/instant/util/aws.clj
- server/src/instant/util/hazelcast.clj
- server/src/instant/util/uuid.clj
- server/test/instant/util/hazelcast_test.clj
Uses a single map in hazelcast for all of the rooms.
In the previous PR https://github.com/instantdb/instant/pull/333, I mentioned that I wasn't sure if one big map or a map per room was best. Now that we've had it in production for a bit, I think one big map will be better. It turns out that creating the listeners on the map is expensive and can cause the virtual thread to park. If we do one big map, then we only have to create listeners once for the big map instead of every time a new room is joined.
The downside is that our listener fires for every change to any room, even if our instance doesn't have any sessions subscribed to the room. To reduce the impact, we don't ask for values in our listener, just the keys, so less data is transferred.
To make the updates efficient, we use merge …
> Use one map for all rooms in Hazelcast

- client/README.md
- client/packages/core/src/Reactor.js
- client/packages/core/src/utils/log.ts
- client/sandbox/react-nextjs/pages/play/query-once-toggle.tsx
- client/sandbox/react-nextjs/pages/play/query-once.tsx
Made a series of different changes, to help us get queryOnce over the finish line. Some were quality-of-life fixes, some small bugs, and one bigger change. 
I could have separated this as separate PRs, but thought they were reasonable to have in one holistic PR. Here are the changes:
**1) Remove wrapping around our `log` util**
We had a nifty `log` util, which we used sparingly in Reactor. One problem with it was that when you used it, you would not get the correct line numbers. 
This was because we wrapped `console.log`, so all the invocations would report `'log.js'`. 
Instead of _wrapping_ console.log, I now expose it directly. This maintains the correct line numbers. 
I also updated our flag from `loggingEnabled` to `__instantLogging`. This is mainly because `loggingEnabled` was too …
> [query-once] finish line

- client/packages/core/__tests__/src/Reactor.test.js
- client/packages/core/src/Reactor.js
Small PR that adds more verbose logging in Reactor. I am doing this to try to better debug the issue that a few of our apps are facing, where queries don't seem to return. 
> [reactor] add more logging to send and receive

- client/packages/core/src/Reactor.js
We got some reports of queries that never seem to end. From reading logs, I think it's because `add-query` and `remove-query` are not happening in a causal order. Undoing our `remove-query` change; Once we ship #361, we can put this back. 
> [hotfix] undo `remove-query`, until we ship #361

- client/packages/core/src/Reactor.js
This reverts commit 6f735d2ec86c214931707cd52983d5abfa8df000.
It did not seem to be the actual race condition causer. Looking more deeply
> Revert "[hotfix] undo `remove-query`, until we ship #361 (#365)"

- client/packages/core/src/Reactor.js
In our authhello example, I noticed a time where a query gets stuck in a loading state. 
Without refreshing the page: 
1. Log in 
2. Log out
3. Log back in 
This happened because:
- In `notifyOne`, we exit early whenever we see a result that has already been in our cache
- But logging in and out, we never cleared our cache
I am not 100% sure this is the root cause. There may be other situations where our cache backfires and prevents us from notifying a cb. This is a clearly broken case, so first fixing it.
> [bugfix] clear dataForQuery cache when changing users

- server/src/instant/runtime/routes.clj
We put the app-id in the state param. When we move the `app_oauth_redirects` in the `triples` table, we'll need to know which app to fetch the redirect from. This lets us figure out which app to use.
Two other small changes:
1. Replaces `(UUID/randomUUID)` with `(random-uuid)` in the route ns
2. Changes our cookie-handling logic a bit to add a prefix to the cookie value. On localhost, clerk was overwriting the `__session` key. In order to know which cookie is ours, we now add a `instantdb_` prefix to the value.
> Add app-id in the oauth state param

- server/src/instant/grouped_queue.clj
- server/src/instant/reactive/session.clj
Reference: https://paper.dropbox.com/doc/Receive-Q-Causal-Order-RAfjwje81o6jWqDT6jLie
Since we removed the transaction lock, there’s a race condition: if you send two transactions txA, txB, txB can finish before txA. 
```
// Client: 
txA { name = "Alice" }
txB { name = "Bob" } 
// Expected result: 
{name: "Bob"} 
// Got: 
{name = "Alice" }
```
Created a `grouped-queue` abstraction, so we can maintain causal order for events, and used it inside session. 
`grouped-queue` takes a `group-fn`. Each enqueued item goes through a `group-fn`. We make sure that only _one_ item can run for a particular group at a time. We also distribute work into the queue more fairly. 
Right now we group the following events:
- (`transact`) by session-id 
- (`set-presence` `join-room` `leave-room` `broadcast`) by …
> Use a grouped-queue in session

- server/src/instant/admin/model.clj
- server/src/instant/admin/routes.clj
- server/src/instant/dash/routes.clj
- server/src/instant/data/bootstrap.clj
- server/src/instant/db/cel.clj
- server/src/instant/db/instaql.clj
- server/src/instant/db/model/attr.clj
- server/src/instant/db/model/attr_pat.clj
- server/src/instant/db/model/triple.clj
- server/src/instant/db/permissioned_transaction.clj
- server/src/instant/flags_impl.clj
- server/src/instant/model/schema.clj
- server/src/instant/reactive/invalidator.clj
- server/src/instant/reactive/query.clj
- server/src/instant/reactive/session.clj
- server/src/instant/superadmin/routes.clj
- server/src/instant/util/test.clj
- server/test/instant/admin/routes_test.clj
- server/test/instant/db/instaql_test.clj
- server/test/instant/db/transaction_test.clj
- server/test/instant/reactive/invalidator_test.clj
- server/test/instant/reactive/session_test.clj
Adds a cache for attrs so that we don't have to fetch them on every operation.
They are automatically invalidated when we see the attrs get updated in the wal and we also manually invalidate them when we make changes to the attrs.
> Add an lru cache for an app's attrs

- server/src/instant/admin/model.clj
- server/test/instant/admin/routes_test.clj
Returns a nicer error when we can't parse the lookup value.
We were throwing 500s when someone encoded `undefined` in the lookup value. Now we'll throw a validation error.
> Better error for invalid lookup

- server/src/instant/reactive/session.clj
- server/test/instant/reactive/session_test.clj
We started getting some false alerts when we added this top-level log. I also realized we don't sample it. 
Looking at the previous version of [`session.clj`](https://github.com/instantdb/instant/blob/cbf4653a23158433f1292343e267c36d19ad83af/server/src/instant/reactive/session.clj), I realized our highest level log was handle-receive. So, I updated the code to be similar to that. 
Moving forward i'll look into removing our custom logic for sampling in clojure, as now have refinery. With that, I'll also try to flatten the number of 'handle-x' functions we have in session.clj 
> [bugfix] remove top-level process-receive-q-entry

- server/src/instant/jdbc/wal.clj
Saves us the manual work of clearing out the config.
> Set wal healthy on shutdown

- server/refinery/rules.yaml
- server/src/instant/reactive/session.clj
Previously, we had an in-house, 'poor-man's' sampler. This led to some child events being lost. Now that we have refinery, we don't need to sample at the event level. Instead, we can use refinery rules and sample at the trace level. 
Moved our current use of sampling into refinery.
> move our sampling to refinery

- client/packages/core/src/Reactor.js
pls 🙏🏾
This would be thus also be returned in `db.auth.signInWithToken` which would be very convenient and helpful 
I noticed that `user` from `db.useAuth` doesn't sync immediately after calling `db.auth.signInWithToken`, causing issues with our React Native navigation that depends on `user` from `db.useAuth`
in any case it seems like an oversight not to return `res`
> Return res (which would include res.user) from signInWithCustomToken

- server/src/instant/reactive/ephemeral.clj
- server/src/instant/util/logging_exporter.clj
Stops logging the gauge properties. They're adding a lot of extra log volume.
> Quieter logs

- client/www/pages/docs/storage.md
- server/src/instant/db/cel.clj
A user pointed out that we should include a trailing slash for our storage permission rule. This PR updates the docs and also adds the string extensions for CEL
Note: The string extension is not needed for this example, but I thought it might be useful to add this in since it's part of our current version of CEL. Separately I notice we're currently on `0.5.2` of cel-java but the latest is [0.8.0](https://github.com/google/cel-java/tags) which includes some improvements / additional extensions. May be good to upgrade/test in a separate PR
> [CEL] Add strings extensions

- server/src/instant/model/app.clj
Most apps have been migrated, this will make it the default for new apps
> Make users-in-triples the default for an app

- client/packages/admin/src/index.ts
- client/sandbox/admin-sdk-express/src/with-schema.ts
One of our users reported `getUser` borks when there's a `+` in email. This is due to us not encoding the query string [[SO]](https://stackoverflow.com/a/6855723)
> [Admin SDK] Encode getUser for admin sdk

- client/www/pages/dash/index.tsx
- client/www/pages/docs/users.md
- server/src/instant/model/rule.clj
Also makes it easier to edit the view rule for users. If you don't provide a `create`, `update`, or `delete` rule, we won't throw an error. We'll only throw an error if you set it to something that isn't `"false"`.
> Update docs for users table, make it easier to edit view rule

- client/packages/core/package.json
- client/packages/core/src/utils/hash.ts
- client/packages/core/src/utils/weakHash.ts
- client/pnpm-lock.yaml
- client/www/package.json
`object-hash` has a dependency on `crypto` which has caused folks issues in environments like [[Cloudflare](https://discord.com/channels/1031957483243188235/1280983629270487080/1290051152737472542)]
We only use `object-hash` for creating a unique value for our queries but we can use something else.
I looked into a few hashing alternatives and asked claude to come up with something. Based on the results this seemed like the fastest algo. You can see benchmarks here https://github.com/nezaj/hash-benchmarks
> [Core] Remove object-hash

- client/www/pages/docs/users.md
One of users got confused because the cli tool would complain that we were trying to modify `$users` table. Re-pulling the schema fixed it for him, but he noticed that the default `$users` schema did not match what was in the docs.
> [Docs] Fix  $users

- client/www/pages/dash/index.tsx
Uses the new `hide` functionality for copyable inputs to hide the admin token by default:
> Hide the admin token

- client/packages/core/__tests__/src/instaml.test.js
- client/packages/core/src/instaml.js
On the backend, we already ignored the `id` inside a tx-step arg: 
https://github.com/instantdb/instant/blob/main/server/src/instant/admin/model.clj#L180-L181
We did not do the same on the frontend. This meant that if a user did something like: 
```javascript
tx.posts[idA].update({id: idB})
```
This would lead erroneous results. 
Fixing at least from the client, so it's not possible to send data like this
> [client] Make sure we ignore id key in instaml

- client/www/components/dash/Sandbox.tsx
- server/src/instant/admin/routes.clj
- server/src/instant/model/rule.clj
daformat noticed that the 'rules' pain in sandbox shows the 'semi-compiled' view of rules:
```cel
cel.bind(...)
```
I added a special `display-code` parameter, which 
- a) shows the version of the code before we add `binds`
- b) shows the pretty-printed code for system tables
> [sandbox] add a `display-code` variable to `program`

- server/src/instant/scripts/metrics.clj
The migration skewed our metrics, a simple fix is to just ignore transactions for that day, this may filter out some legitmate apps/devs that should be active, but not in a meaningful way
> [Metrics] Filter out migration date for analytics

- server/src/instant/db/instaql.clj
- server/src/instant/util/instaql.clj
- server/test/instant/db/instaql_test.clj
A user pointed out that responses in admin were not coming in serverCreatedAt order. 
This makes it happen. 
Note: 
Right now we assume that we only order by serverCreatedAt. Eventually, this will either become unnecessary due to our instaql CTE update. But in case it's not, we'll need to update the logic when we allow for ordering by other keys. 
> [admin] order admin responses

- server/src/instant/db/instaql.clj
Pulls out `:display-code` from permissioned-node in the query
> Send display-code to frontend for queries

- server/src/instant/reactive/ephemeral.clj
It turns out running the hz background sync in multiple threads was a bad idea because the events are handled out of order and then we set presence after they've left the room.
This puts the background updates in a single queue and handles them from one background worker. I'll be watching `instant.ephemeral.hz-ops-q.size` to make sure the queue isn't getting overwhelmed (if it does there's a feature flag that we can flip).
> Do background hz updates in a single thread

- server/src/instant/core.clj
- server/src/instant/reactive/ephemeral.clj
Hazelcast is shutting down on its own when it sees the sigterm signal, but that happens before we're finished shutting down the server. It leaves a trail of errors as the sessions close and can't update hazelcast. 
After this change, we'll wait to gracefully shutdown hazelcast until after the undertow server shuts down.
> Handle hazelcast shutdown on our own

- client/packages/core/src/Reactor.js
- client/packages/core/src/index.ts
- client/sandbox/react-nextjs/pages/play/authsync.tsx
If you await `db.auth.signIn*`, you would expect that afterwards the system would be logged in. But Clark noticed this was not the case. A basic repro: 
```javascript
function App() {
const { isLoading, user } = db.useAuth();
const [calledSignIn, setCalledSignIn] = useState(false);
const [result, setResult] = useState<any>(null);
useEffect(() => {
if (calledSignIn && !result) {
setResult({ calledSignIn, user }); // Problem: `user` won't exist, when `calledSignIn` is already true
}
}, [user, calledSignIn]);
return (
<button
onClick={async () => {
const ret = await getToken();
await db.auth.signInWithToken(ret.token);
setCalledSignIn(true);
}}
>
Sign in
</button>
);
}
```
This is because we did not await on `this.changeCurrentUser`. Adding an await fixed the issue 
> [client] make sure that auth is finished after awaiting db.auth

- .gitignore
- client/Makefile
- client/www/_emails/html/oct2024.html
- client/www/_emails/markdown/oct2024.md
- client/www/_emails/txt/oct2024.txt
- client/www/lib/emails.js
- client/www/pages/intern/emails/[slug].tsx
- client/www/pages/intern/emails/index.tsx
- server/src/instant/scripts/newsletter.clj
Adds tooling for sending out broadcast emails!
This PR contains three things
1. Preview tool for emails located at `intern/emails`
2. Adds content for the october newsletter
3. Adds a server scripts `newsletter.clj` with instructions on how to send out newsletters
> Add newsletter

- server/src/instant/reactive/session.clj
If a session disconnects just as they join the room, we can end up with data for the session in the ephemeral state that will never go away.
This change removes the session from the store before we remove the ephemeral state.
> Remove session from store before clearing ephemeral state

- server/src/instant/reactive/ephemeral.clj
- server/src/instant/util/hazelcast.clj
For some reason running `hz-util/merge!` isn't having the expected effect in production. 
The `merge!` function should call the `.merge!` method on the record, which will apply the update to the hazelcast map. It works locally, but it's not removing the session in production. I'm not sure why it's not working--it might have something to do with reflection, even though there aren't any reflection warnings.
Now instead of putting the merge helper on the record, we just define a new function. Not sure why I didn't do that in the first place, because it's a lot cleaner.
I'm not 100% sure this will work, since I haven't been able to replicate the issue locally, but it seems like a good place to start.
> Fix bug with hazelcast operations

- server/src/instant/reactive/ephemeral.clj
- server/src/instant/util/hazelcast.clj
- server/src/instant/util/uuid.clj
- server/test/instant/util/hazelcast_test.clj
Seeing a weird issue in prod where sessions aren't being removed because the key isn't recognized as being in the map. I haven't been able to replicate it locally, but it's possible that there is some inconsistency in how the map key is serialized. 
This PR writes our own serializer/deserializer for the room-map keys. Hopefully that will make hazelcast recognize the key.
> Custom serializer for hazelcast room keys

- client/packages/core/__tests__/src/instaql.test.js
- client/packages/core/src/datalog.js
- client/packages/core/src/store.js
Forgot to add handling for `$in` to match `in` on the client.
> Fix $in on the client

- client/www/pages/docs/cli.md
In our docs page, we explictly wrote: `npm i -D instant-cli`. This will end up pinning a specific version of the cli to this app. 
However, we don't really want this to be the default experience. The default experience should be to use npx instant-cli. 
The downside of this is that we will have to worry more about backwards compatibility, but it is a better experience for the user. 
> [docs] show npx instead of npm i for isntant-cli

- client/www/components/dash/Billing.tsx
- client/www/lib/auth.ts
- client/www/pages/dash/index.tsx
- server/src/instant/dash/routes.clj
The [Kosmik](https://discord.com/channels/1031957483243188235/1258878823529844766/1303025195992350856) team mentioned how not being able to see app/storage usage is a schlep for them. Figured we can lower the role requirement for seeing the admin page.
I also felt like we should start adding friendly error messages. 
**Before**
**After**
> [Dash] Enable billing page for admins

- client/www/_posts/conj.md
- client/www/lib/posts.js
- client/www/lib/videos.js
- client/www/styles/globals.css
Adds Stopa's conj talk to our essays page. Added a video extension to our markdown parser to make this work
> [Blog] Add conj video

- client/sandbox/strong-init-vite/instant.schema.ts
**Context:** 
We used a lot of inference to generate the `Schema` type. When you infer types though, they tend to auto-expand in intellisense, so you get these kind of inscrutable types like so: 
**Before** 
This is a [known issue](https://github.com/microsoft/TypeScript/issues/45954) in Typescript. 
However, there's a "trick" we can do. Typescript doesn't expand interfaces. So if we 'cast' our graph to an interface, the types look a lot better: 
**After** 
**Related Stackoverflow: https://stackoverflow.com/questions/79164542/how-can-i-mask-a-generic-type-for-intellisense**
--- 
Right now, I'm just doing this manually in our strong-init playground. If we end up liking this, I'll make this a part of the instant.schema.ts generation. For now, there's still more parts where the types look …
> [experiment][strong-init-sandbox] export a `Graph` interface in instant.schema.ts

- client/packages/admin/src/index.ts
- client/packages/core/src/coreTypes.ts
- client/packages/core/src/helperTypes.ts
- client/packages/core/src/index.ts
- client/packages/core/src/queryTypes.ts
- client/packages/react-native/src/index.ts
- client/packages/react/src/InstantReact.ts
- client/packages/react/src/InstantReactExperimental.ts
- client/packages/react/src/InstantReactWeb.ts
- client/packages/react/src/useQuery.ts
- Removes `WithCardinalityInference` from normal init flows
- Removes InstantGraph checks in normal init flows
> [2][in-progress][strong-init] de-complect normal-init from strong-init

- client/packages/react/src/useQuery.ts
Fixes a bug in the dashboard where we don't resubscribe to queries after an update to `apps`. Could also impact users, but they're unlikely to hit this bug because it requires calling private methods (`db._core.shutdown()`).
If the user were to call `db._core.shutdown()` (like we do in the dashboard's `useEffect`), then any calls to useQuery when you reconnect with `init` won't trigger the `useEffect` in `useQuery` and we won't send the subscription to the server.
> Depend on the InstantClient instance in useQuery hook

- client/www/pages/docs/presence-and-topics.md
We are using an incorrect prop name `currentUserColor` in docs whereas the [correct prop name is `userCursorColor`](https://github.com/instantdb/instant/blob/ff52fb3024a7c1c3e3e37498ecd23280b7fa8834/client/packages/react/src/Cursors.tsx/#L20).
Also, adding `className="h-full w-full"` helps us understand styles/classes need to be applied to the `Cursors` element to make it visible.
> [DOCS] Cursors prop name correction

- client/www/pages/docs/presence-and-topics.md
App used to crash as `myPresence` was `undefined`
Now it shows an `App loading...` indicator until user presence is fetched
https://github.com/user-attachments/assets/22772b28-c0e4-4531-b760-3cff74603daf
> [DOCS] show loading until user's presence is obtained

- server/src/instant/auth/jwt.clj
- server/src/instant/auth/oauth.clj
- server/src/instant/util/exception.clj
Use `ex/throw-oauth-err!` in `verify-jwt` so that we return a 400 with a good error message instead of a 500.
> Don't throw 500s on invalid JWT tokens

- server/src/instant/flags_impl.clj
- server/src/instant/reactive/ephemeral.clj
- server/src/instant/reactive/invalidator.clj
- server/src/instant/reactive/receive_queue.clj
- server/src/instant/reactive/session.clj
- server/src/instant/runtime/routes.clj
- server/src/instant/util/logging_exporter.clj
- server/test/instant/reactive/session_test.clj
This should prevent a slow session from tying up the queue.
When we do `set-presence`, we'll put one `refresh-presence` in the receive-q for each session instead of immediately doing a broadcast. This makes `set-presence` finish much faster. If one of the sessions subscribed to the room is slow, then they won't slow down the set-presence broadcast for everyone in the room. 
We also drop `refresh-presence` events if there are multiple in the queue for a session and room, further preventing a slow session from clogging things up. Also acts as a relief valve for sessions that are getting overloaded.
cc @stopachka @nezaj
> Send refresh-presence through receive-q

- server/src/instant/reactive/ephemeral.clj
Follow up to https://github.com/instantdb/instant/pull/457.
Now that we're putting `refresh-presence` messages on the receive-q instead of broadcasting them, we can do that work directly in the map listener. It lets us remove a bunch of the core.async complexity from the hazelcast code.
> Simplify hazelcast now that we're using receive-q for refresh-presence

- client/packages/core/src/index.ts
- client/packages/react-native/src/index.ts
- client/pnpm-lock.yaml
- client/sandbox/strong-init-vite/package.json
- client/sandbox/strong-init-vite/src/typescript_tests_experimental.tsx
- client/sandbox/strong-init-vite/src/typescript_tests_normal.tsx
I added two new files: 
- typescript_tests_normal.tsx
- typescript_tests_experimental.tsx
These go through a full flow of rooms, queries, transactions with db's in `core, react, and react-native`. 
While doing this, I realized we had a typescript error in our current implementation, for core and React. We were inferring `RoomSchema` in the wrong argument position. 
Fixed, so that rooms come with typehints again in core and react-native.
> [strong-init] add a few typescript tests in strong-init sandbox, and fix bugs

- client/sandbox/strong-init-vite/src/typescript_tests_experimental.tsx
- client/www/pages/docs/strong-init.md
- Our schema helper example was really tough to read. I made a small improvement, so it at least looks a bit nicer. There's a lot more to do with the docs (i.e instead of `myTable`, using actual examples, and fixing this up in general, but for now just starting off simple with the visual improvement)
- I also started to use these examples in our strong-init sandboxes 
**Docs: before**
**Docs: after** 
> [strong-init] schema helpers: fix up docs and update our strong-init sandbox

- server/src/instant/jdbc/sql.clj
- server/src/instant/util/exception.clj
- server/src/instant/util/http.clj
Sets a default query timeout of 30 seconds. This should only affect admin queries because client queries coming through the websocket already have a 5 second timeout.
If the requests takes longer than 30 seconds, we'll return a 429 that looks like:
```js
> await adminDb.query({posts: {}}).catch(e => console.log(e))
{
status: 429,
body: {
type: 'timeout',
message: 'The query took too long to complete.',
hint: null
}
}
```
> Set a default query timeout of 30 seconds

- client/www/pages/docs/instaql.md
Adding a note so folks aren't surprised when `limit/offset/order/etc` don't work for nested queries
> [Docs] Pagination and order limited to top-level namespace

- client/sandbox/react-nextjs/pages/play/hazelcast-broadcast.tsx
- server/src/instant/reactive/ephemeral.clj
- server/src/instant/reactive/session.clj
- server/src/instant/util/hazelcast.clj
- server/src/instant/util/logging_exporter.clj
This updates broadcast to work across multiple instances.
Some of the room's sessions may be on other physical machines when we broadcast a message to everybody in the room. We use a hazelcast topic to notify those other sessions that they need to broadcast the message.
Two changes to make this work:
1. Similar to https://github.com/instantdb/instant/pull/457, we send `:server-broadcast` events through the receive-q instead of doing a single `rs/try-broadcast-event!`
2. In `:client-broadcast` we first notify any sessions that are on the same machine, then we send a message through a hazelcast topic with the list of remote session ids and the data to broadcast. The listener on the topic will put a `:server-broadcast` event on the `receive-q` for the sessions that it has locally.
There is a …
> Make broadcast work with multiple instances

- client/packages/cli/index.js
- client/www/components/dash/explorer/EditNamespaceDialog.tsx
- client/www/components/dash/explorer/EditRowDialog.tsx
- client/www/components/dash/explorer/Explorer.tsx
- client/www/lib/indexingJobs.ts
- client/www/lib/types.ts
- server/resources/migrations/38_uniqueing.down.sql
- server/resources/migrations/38_uniqueing.up.sql
- server/src/instant/dash/routes.clj
- server/src/instant/db/indexing_jobs.clj
- server/src/instant/db/model/attr.clj
- server/src/instant/db/model/attr_pat.clj
- server/src/instant/jdbc/sql.clj
- server/src/instant/model/schema.clj
- server/src/instant/superadmin/routes.clj
- server/src/instant/util/exception.clj
- server/test/instant/db/indexing_jobs_test.clj
- server/test/instant/db/instaql_test.clj
- server/test/instant/db/transaction_test.clj
Uses the background indexing jobs for adding/removing index and uniqueness.
Here's what setting and removing `indexed` from the explorer looks like
https://github.com/user-attachments/assets/1926295e-20d3-4842-9455-2ac6c36b5808
Uniqueness is similar, with helpful errors if the attribute has duplicate values. Clicking on the "multiple entities with value X" link will go to the explorer with all entities with that value present.
https://github.com/user-attachments/assets/fbe82ed9-42ec-44a2-b8ca-ef370d287782
If you have data that's too big to index, you'll also get an error:
https://github.com/user-attachments/assets/49b78e56-c51b-451b-954e-b8ad1c9eedf3
Updating from the cli is similar
https://github.com/user-attachments/assets/a261a193-2d33-479c-a8ee-f8bc0a6c413b
TODO before deploying:
> Index process

- client/packages/admin/src/index.ts
- client/packages/core/src/index.ts
- client/packages/core/src/queryTypes.ts
- client/packages/core/src/schemaTypes.ts
- client/packages/react-native/src/index.ts
- client/packages/react/src/index.ts
- client/packages/react/src/init.ts
- client/sandbox/strong-init-vite/src/helpers.ts
- client/sandbox/strong-init-vite/src/typescript_tests_experimental.tsx
- client/sandbox/strong-init-vite/src/typescript_tests_experimental_v2.tsx
- client/sandbox/strong-init-vite/src/typescript_tests_experimental_v2_no_schema.tsx
- client/sandbox/strong-init-vite/src/typescript_tests_normal.tsx
Previously, strong-init _required_ that a `schema` was passed in. This now makes `schema` optional. 
There's two benefits to this. First, users will still be able to hack as soon as they install instant, without having to define a schema first. Second, it makes upgrading from normal init easier: if they don't define a schema, the behavior is the same as old init.
There's some cool typescript trickery going on, but the big insight was to default our `Schema` type parameter, to an 'UnknownSchema`, which had the correct settings for links. More on this in the [stackoverflow discussion](https://stackoverflow.com/questions/79187112/what-is-the-idiomatic-way-to-make-a-generic-type-optional)
> [strong-init-v2] make schema optional

- server/src/instant/model/schema.clj
Fixes `No matching clause: :check-data-type` errors
> Use filtered tx-steps for plan

- server/src/instant/model/rule.clj
- server/src/instant/reactive/invalidator.clj
Similar to https://github.com/instantdb/instant/pull/373, caches rules so that we don't have to fetch them repeatedly.
They are automatically invalidated when we see the rules get updated in the wal and we also manually invalidate them when we make changes to the rules.
> Add an lru cache for an app's rules

- server/.clj-kondo/config.edn
- server/src/instant/db/model/attr.clj
- server/src/instant/model/app.clj
- server/src/instant/model/instant_user.clj
- server/src/instant/model/rule.clj
- server/src/instant/reactive/ephemeral.clj
- server/src/instant/reactive/invalidator.clj
- server/src/instant/reactive/session.clj
- server/src/instant/util/cache.clj
- server/src/instant/util/coll.clj
- server/test/instant/db/instaql_test.clj
Improves the caching of attrs and adds caching to `app/get-by-id` and `instant_users/get-by-app-id`.
When all is cached, reduces the number of queries we run for `:init` from 2 to 0 when the user isn't logged in, and 4 to 1 when we need to look up the user by their auth token.
We were fetching attrs a lot more often than we needed to because the `query-op` gets passed a conn-pool that it uses when it calls `attrs/get-by-app-id`. That was causing us to bypass the cache. With this PR we'll stop bypassing the cache if the passed in conn is `aurora/conn-pool`.
We fetch the app creator by the app id, so the cache needs to be evicted when either the app's creator changes or the instant_user changes. This PR introduces a novel lru cache that allows you to evict based on data in the cached item. …
> Faster init through better caching

- server/src/instant/reactive/session.clj
I'm worried about how many threads we're creating to run the receive workers.
This PR runs the workers in virtual threads.
We already perform the `handle-receive` work in a virtual thread, so this should be fine. The new stuff that happens in a virtual thread will just be the `.poll` on the LinkedBlockingQueue.
> Run receive worker in a virtual thread

- client/packages/core/src/Reactor.js
When we call `useSyncPresence` in the typing indicator example, we're dropping the `publishPresence` command because `this._presence` is empty. Now we set it so that we'll call the initial setPresence after joining the room.
Before the grouped queue improvements, this might have raced on the server and caused a "you haven't joined the room yet" error. But now that we handle events in order, it should be fine.
Before:
After:
> Initialize presence on join room

- server/.clj-kondo/hooks/defsql.clj
- server/deps.edn
- server/src/instant/jdbc/sql.clj
- server/src/instant/reactive/session.clj
- server/test/instant/jdbc/sql_test.clj
This fixes a problem where the postgres connection gets killed when we call `future-cancel` on handle-receive timeouts. 
If the database is overloaded and it causes a bunch of handle-receives to time out, we can get into a feedback loop where canceling the query causes the connection to get killed, putting additional wear on the database when we recreate the connection.
With this PR, we keep track of the in-progress queries and cancel them before we call `future-cancel` on the handler.
There's a dynamic var `*in-progress-stmts*` that you can bind to an atom with a set in it. If bound, the `defsql` handler will put a `Cancelable` in the set while the query is active. You can call `sql/cancel-in-progress` to cancel all of the in-flight queries. We do just that in `session/handle-receive` …
> Graceful shutdown of queries on timeout

- client/scripts/publish_packages.clj
If you provide a regular version when publishing an experimental tag:
```shell
$ make publish-experimental
(Experimental Build) Building + Publishing Packages...
When publishing the `experimental` tag, the version must contain the tag (e.g. v0.1.2-experimental.0).
You provided v0.15.1
make: *** [publish-experimental] Error 1
```
If you provide a tagged version when publishing to the main branch:
```shell
$ make publish             
Building + Publishing Packages...
Version should match format v0.1.2, but you provided v0.15.1-experimental
make: *** [publish] Error 1
```
> Warn on bad versions in make publish and publish-experimental

- server/refinery/rules.yaml
- server/test/instant/db/indexing_jobs_test.clj
It seems like the default is false https://docs.honeycomb.io/manage-data-volume/sample/honeycomb-refinery/sampling-methods/#useclustersize
This might help us keep under the rate limit.
> Use cluster size in refinery sampler

- client/packages/admin/src/index.ts
- client/packages/core/src/coreTypes.ts
- client/packages/core/src/helperTypes.ts
- client/packages/core/src/index.ts
- client/packages/core/src/instatx.ts
- client/packages/core/src/queryTypes.ts
- client/packages/core/src/schema.ts
- client/packages/core/src/schemaTypes.ts
- client/packages/react-native/src/index.ts
- client/packages/react/src/DoNotUseInstantReactWeb.ts
- client/packages/react/src/InstantReact.ts
- client/packages/react/src/InstantReactAbstractDatabase.ts
- client/packages/react/src/InstantReactWebDatabase.ts
- client/packages/react/src/index.ts
- client/packages/react/src/init.ts
- client/packages/react/src/useQuery.ts
- client/sandbox/react-nextjs/pages/play/strong-todos.tsx
- client/sandbox/strong-init-vite/instant.schema.v2.ts
- client/sandbox/strong-init-vite/src/App.tsx
- client/sandbox/strong-init-vite/src/typescript_tests_experimental.tsx
- client/sandbox/strong-init-vite/src/typescript_tests_experimental_v2.tsx
- client/sandbox/strong-init-vite/src/typescript_tests_experimental_v2_no_schema.tsx
- client/www/pages/docs/strong-init.md
This PR: 
Promotes`do_not_use_init_experimental` PR into the latest `init_experimental`. 
The main changes:
- `schema` is now optional in `init_experimental`
- This makes upgrading from `init` to `init_experimental` much easier
- `cardinalityInference` is no longer an option
- If `schema` is provided, cardinality inference is on. If it is not, cardinality inference is off
- Better intellisense
- We are more careful about how we write our types, so the intellisense looks better
**Will strong-init users experience a breaking change?**
`i.graph` returns an InstantSchemaDef now, so they _will not_ experience breaking changes from a different `graph` type. 
However, if some users wrote `init_experimental({ schema, cardinalityInference: false })`, we will not respect the cardinality inference. …
> [init] merge into init_experimental

- client/packages/admin/src/index.ts
- client/packages/core/src/index.ts
- client/packages/core/src/schemaTypes.ts
- client/packages/react-native/src/index.ts
- client/packages/react/src/index.ts
- client/sandbox/strong-init-vite/src/typescript_tests_normal_as_experimental.tsx
In normal init, folks could previously provide types as shapes, like so: 
```typescript
const db = init<Schema, Rooms>(...)
```
With `init_experimental`, this will no longer work. The current solutions are either to go untyped: 
```typescript
const db = init_experimental({ appId } );
```
Or, to upgrade to the schema object: 
```typescript
ocnst db = init({ appId, schema })
```
However, it can be cumbersome to create this schema object. When we upgrade users to strong init, it would suck to force them into a breaking change. 
I added a helper type, called `BackwardsCompatibleSchema`. This takes in the old `Schema` and `Rooms` shape, and creates an `InstantSchemaDef` type, which behaves _just_ as the Rooms and schema types did before. 
> [strong-init] support shapes for backwards compatibility

- client/packages/core/__tests__/src/Reactor.test.js
- client/packages/core/__tests__/src/instaml.test.js
- client/packages/core/__tests__/src/instaql.test.js
- client/packages/core/__tests__/src/store.test.js
- client/packages/core/src/Reactor.js
- client/packages/core/src/instaml.js
- client/sandbox/react-nextjs/pages/play/missing-attrs.tsx
Previously, if a user creates an object that didn't exist before, we would make our best guess and create the object for them. 
This was useful, but would sometimes create surprising results if you used non-standard links. For example, for `posts.owner`, our guess would assume that `owner` was the namespace. 
Now that we pass in a schema in strong init, we can use the schema to help user create missing attrs. 
For missing object attrs:
1. We use the `schema` to decide if they need to be indexed or unique 
For missing ref attrs: 
1. We use the schema to set the forward identity, reverse identity, cardinality, indexed, unique 
If a missing attr is _not_ in the schema:
This is likely a mistake, and we throw a validation error
> [client][strong-init] use schema to help our attr generation

- client/packages/admin/src/index.ts
- server/src/instant/admin/model.clj
- server/src/instant/admin/routes.clj
- server/test/instant/admin/routes_test.clj
Previously, we would do our best guess to generate attrs, when a transact came in. 
However, in the case of strong init, it doesn't really make sense to do that. The user already has an explicit schema. 
In this case, we throw an error, letting the user know that the there was an unknown attribute
> [admin-sdk][strong-init] throw on missing attrs 

- client/packages/cli/index.js
See: https://github.com/instantdb/instant/issues/496
when instant couldn't find the app id, we would not actually show the error message. Instead, we'd throw a js error: 
```bash
file:///Users/stopa/projects/instant/client/packages/cli/index.js:1106
noAppIdErrorMessage
^
ReferenceError: Cannot access 'noAppIdErrorMessage' before initialization
at getAppIdWithErrorLogging (file:///Users/stopa/projects/instant/client/packages/cli/index.js:1106:7)
at pushSchema (file:///Users/stopa/projects/instant/client/packages/cli/index.js:584:23)
at Command.<anonymous> (file:///Users/stopa/projects/instant/client/packages/cli/index.js:72:5)
```
Hoisting it up so we actually show the error 
> [cli] Hoist up `noAppIdErrorMessage`

- client/packages/cli/index.js
`commander` has some rough support for global options, but they work in a weird way. Once you enable global options, this is how they work: 
**Calling from root: global options show up as local options**
If you write `npx instant-cli -h`, global options will show up as `options`: 
This is a bit confusing, but happens because in the context of the root command, these options are _not_ global. 
**Calling from a subcommand, all _but_ `-h` show up as global options**: 
If you wrote `npx instant-cli login -h`, you would see: 
Here, it _almost_ works as we'd like. Except, the `help` command shows up under `options`, rather than `global options`. 
It was a bit annoying that in `npx instant-cli -h`, the "options" section was prominently the first thing. These were all global flags, and likely not …
> [cli] support global options

- client/packages/cli/index.js
- Made our subheadings dimbold.
- Updated our helper text for `[ID]` to be `[app-id]` 
Small changes but aesthetically more pleasing imo: 
**Before** 
**After** 
> [cli] Add styling to subheading in help

- server/Makefile
- server/refinery/.ebextensions/resources.config
- server/scripts/eb_deploy.clj
- server/scripts/manual_deploy.sh
- server/scripts/prod_ssh.sh
- server/scripts/prod_tunnel.sh
- server/scripts/yourkit_tunnel.sh
The old elasticbeanstalk environment is stuck in an invalid state, so this updates us to use a new one.
The new environment is already running and everything looks good.
Deployment strategy:
1. Reduce number of instances in old env to 1 and wait for connections to drain
2. Update cloudflare to use the new environment
3. Reduce number of instances in old env to 0 and wait for connections to drain
4. Terminate old environment
There will be a split brain on session state while sessions transition to the new environment, but no worse than it was when we were on a single instance.
> New elastic beanstalk environment

- client/packages/cli/index.js
- client/sandbox/strong-init-vite/instant.schema.ts
Our error messages were a bit meh for two reasons: 
1. Sometimes the message was written in a rushed way 
2. We didn't have any syntax highlighting, so it didn't look visually different from stdout in the terminal. 
Updated our error messages with an `error` helper, that adds some syntax highlighting. I also updated a few of the messages. 
> [cli] improve error messages

- client/packages/cli/index.js
Had a stray `null &&` in there, which I was using to test error messages. 
> [bugfix][cli] remove null && 

- client/packages/cli/index.js
- client/packages/cli/src/util/fs.js
- client/packages/cli/src/util/packageManager.js
**Context** 
When we generate files for the user, we need some instant module to exist. This is because in schema.ts for example, we need to generate an import statement like: 
```typescript
import { i } from '@instantdb/react'
```
Previously: 
1. We only detected instantdb/react or instantdb/core. 
2. We would fail if they weren't there
This PR makes the CLI more helpful, by: 
1. Detecting react, core, react-native, and admin
2. If none are detected, prodding the user to choose one and installing it for them.
> [cli] if no instant module found in package.json, prompt to install one

- server/src/instant/db/instaql.clj
- server/test/instant/db/instaql_test.clj
Fixes a bug where we could apply the permission check for a different namespace if two objects in the different namespaces shared an eid.
Now we group the permission checks by etype and eid, ensuring that we run the correct permission check for each entity.
> Distinguish between etypes on permission checks

- client/packages/admin/src/index.ts
- client/packages/core/src/queryTypes.ts
- client/sandbox/strong-init-vite/src/typescript_tests_normal_as_experimental.tsx
When we returned a query result type, it would look something like:
This is not _too_ helpful, as it doesn't actually show what the result would look like. 
I added a `Expand` type, which tries to convert this to it's most concrete form: 
This is a bit experimental, as I am not 100% sure how this will interact with other types in the real world. 
However, I thought, let's ship it and get some feedback. 
> [strong-init][experimental] Expand

- client/packages/cli/index.js
`instant-cli init` used to _only_ handle the case where a user wanted to create a brand new app. 
But most of the time, users already created an app in the dashboard. For this case, they would have to know that the right command would be to call `instant-cli pull` with an app id param. 
Instead, I updated the `instant-cli init` flow, so we ask the user if they want to create a new app, or import an existing one. 
**Future work**
- In `instant-cli pull`, if no app id is provided, we should just prompt the user for an app id, like here
- In `instant-cli init`, we should try to detect the app id. If we do, we should ask them if they want to import that app
**Here's how things look:**
> [cli] Handle existing apps in `instant-cli init`

- client/packages/cli/index.js
Previously, we prompted for an app id. That's kind of a sadder experience though. Instead, we now fetch apps and let the user select:
> [cli] prompt for an app selector rather than pasting an id

- client/packages/cli/index.js
Previously: 
- If we couldn't detect an app id, we would exit and print an error.
Now:
- We use `detectOrCreateApp`, so in case we can't detect an app, we prompt the user to provide one, or create one for them.
Made these changes for `push,push-schema,push-perms,pull,pull-schema,pull-perms` 
Aside: 
- This whole `ok: true`, `withErrorLoggin` business is def a schlep. Noting for a future refactor, to use exceptions a la instant.exception on the backend  
> [cli] detect _or_ create apps in push/pull commands

- server/src/instant/data/bootstrap.clj
- server/src/instant/db/model/attr_pat.clj
- server/src/instant/fixtures.clj
- server/test/instant/db/instaql_test.clj
Most of the changes here are to make testing against apps with checked types easier.
The change that fixes the bug is in `attr_pat` where we don't try to validate the type when we're passed in a placeholder symbol (which cel's data.ref does).
> Fix data.ref with checked types

- client/packages/cli/index.js
- server/src/instant/dash/routes.clj
- server/src/instant/model/instant_cli_login.clj
Previously, there were a few bugs with our `instant-cli login` flow: 
1. Once we entered the waitForAuthToken phase, we couldn't ctrl + c out of the program
1. This was because we had a try catch over the fetch json, which swallowed everything
1. If a user clicked 'Deny' on the dashboard, the system would not exit
1.  This was because there was no difference between a) a missing login request, a claimed one, or an expired one
I updated our backend, so we return more descriptive errors when we are waiting for authentication. If we are simply waiting for user input, we recurse. But, if there's any other error, we now exit. 
I also removed the high-level try catch. 
> [cli] Make sure `instant-cli` login responds to `deny`

- client/packages/cli/index.js
- client/packages/cli/package.json
- client/pnpm-lock.yaml
Previously, the files we generated would be a bit off with formatting:
- Keys would be written out as strings, even rather than as symbols
- Spacing was off
Added prettier to the CLI. This makes it so we print a formatted file
> [cli] use prettier to autoformat our exported files

- server/deps.edn
- server/src/instant/util/tracer.clj
Compresses honeycomb traces with gzip. Should help us to transfer a lot less data between our instances. 
Tested locally talking both to the honeycomb API and a local refinery instance.
> gzip honeycomb traces

- client/packages/cli/index.js
**Context** 
Previously, we had a separate flow, where if you used `init` and chose to create an app, we would make some empty files for you. 
However, those files had a few issues: 
1. The default state was filled with data that wasn't actually in the production app. This felt a bit confusing
2. There wasn't _much_ explanation. For example, the `rules` file just had some example rules, but nothing more
We also had unique behavior when pulling an app: 
1. If there were no perms in an app, we would not create a perms file 
**This PR** 
Now, whether you 'create' an app or not, we will go through the same `pull` flow. 
In this new pull flow, we detect: 
1. If the schema does not have any entities defined, we add a comment explaining what they are 
2. If the schema does not have links …
> [cli] merge all `pull` file creation into one path

- client/packages/core/src/Reactor.js
- client/www/pages/docs/instaql.md
We get a lot of people in the discord who are confused about query errors because all they see is "Validation failed for query" in the error message. This passes along the hint so that they can identify the problem.
**Before**
```json
{
"message": "Validation failed for query"
}
```
**After**
```json
{
"message": "Validation failed for query",
"hint": {
"data-type": "query",
"input": {
"comments": {
"$": {
"where": {
"someField": {
"$gt": 50
}
}
}
}
},
"errors": [
{
"expected?": "indexed?",
"in": [
"comments",
"$",
"where",
"someField"
],
"message": "The `comments.someField` attribute must be indexed to use comparison operators."
}
]
}
}
```
> Include hint in query error

- client/www/pages/docs/instaql.md
Adds docs for query operators.
Direct link to preview: https://instant-www-js-operators-docs-jsv.vercel.app/docs/instaql#comparison-operators
> Add docs for query operators

- server/flags-config/instant.perms.ts
- server/flags-config/instant.schema.ts
- server/src/instant/config.clj
- server/src/instant/flags.clj
- server/src/instant/reactive/session.clj
Moves [drop-refresh-spam](https://github.com/jsventures/instant/pull/1138) to a flag so we can easily turn it on and off.
> Move drop-refresh-spam to flag

- client/packages/admin/src/index.ts
User reported that this type was missing. It's not longer _strictly_ necessary to export it, as all other types just take the Schema, but it's good to have. 
https://discord.com/channels/1031957483243188235/1280983629270487080/1310893036401856523
> export InstantAdminDatabase

- client/sandbox/react-nextjs/pages/play/storage.tsx
- server/resources/config/dev.edn
- server/resources/config/prod.edn
- server/src/instant/config.clj
- server/src/instant/config_edn.clj
- server/src/instant/storage/s3.clj
Still working on the storage PR but felt wanted to ship this separately to users earlier. 
Created a an IAM user specifically for S3 privileges and supply it's credentials for generating signed urls
> [Storage] Add storage user

- client/packages/admin/src/index.ts
- client/packages/cli/index.js
- client/packages/core/src/index.ts
- client/packages/react-native/src/index.ts
- client/packages/react/src/index.ts
- client/sandbox/strong-init-vite/instant.perms.ts
Previously, rules had no type information. This made it a bit annoying to write it out, because you would get no intellisense. 
I made an `InstantRules` type, which helps with autocomplete when writing out the rules. 
> [cli] Add a type helper to rules

- client/packages/cli/index.js
This ended up printing twice in the push case. 
Removing.
> [cli][sm] remove extraneous printDotEnvInfo

- server/src/instant/admin/routes.clj
- server/src/instant/dash/routes.clj
- server/src/instant/runtime/routes.clj
If we wrap the `GET` or `POST` with the middleware, then it gets applied before any route matching is applied.
https://github.com/weavejester/compojure/blob/master/src/compojure/core.clj#L185
If I'm reading how `defroutes` works correctly, we try every handler until we get a match, so my middleware could run on every request (depending on ordering of the routes).
Also fixes how we wrap cookies. Tested the oauth login locally.
> Fix how we do per-route middleware

- server/src/instant/reactive/session.clj
My reasoning: 
Looking at aurora, we seem to have some queries that take a long time to complete just inside postgres. If our timeout on the server is lower, I worry we'll just exhaust the db, constantly asking it for these expensive queries, failing, and asking again. 
I wonder what will happen if we increase the timeout. 
> [experiment] increase handle-receive timeout to 30s

- server/README.md
- server/resources/migrations/41_primary_keys.down.sql
- server/resources/migrations/41_primary_keys.up.sql
Drop the deprecated_triples table and add a `uuid` primary key to `instant_subscriptions`.
Doesn't require any code changes, postgres will automatically insert a random uuid as the id for the existing rows and for new rows.
> Add primary keys to all tables

- server/src/instant/db/datalog.clj
Right now it's hard to correlate our slow queries on postgres, to the originating datalog queries. 
Added a quick app-id, query-hash to the beginning of every one of our queries, which we can use as variables to correlate
> [server] add unique identifiers to d/query-nested

- client/www/components/docs/Layout.jsx
- client/www/pages/docs/permissions.md
- server/src/instant/model/rule.clj
- server/test/instant/db/instaql_test.clj
I think `"$default"` is more consistent with other places where you have “special case” things. Also easier to google/ask questions about
> $default permissions

- server/test/instant/db/instaql_test.clj
Fixes merge conflict in test. `aurora/conn-pool` -> `(aurora/conn-pool)`
> Fix merge conflict

- client/packages/core/src/index.ts
- client/packages/react/src/InstantReactAbstractDatabase.ts
One of our users inquired about `useConnectionStatus` for `init_experimental` and realized needed to integrate this into the `init_experimental` branch -- excited for init/init_experimental to become one soon!
> [SDK] Add useConnectionStatus for init_experimental

- server/src/instant/db/model/triple.clj
Small improvement for lookups--make sure we're looking at the `av` index when we search for the triple value.
*Note* I discovered we don't handle reverse link lookups properly, so we'll probably have to update this to use the `vae` index on reverse lookups. I'm surprised nobody has complained about this, but I guess they're only looking up in the forward direction or they gave up on lookups.
> Make sure we use the `:av` index on lookup triples

- server/src/instant/jdbc/wal.clj
Prevent the wal cleanup from deleting replication slots that we're using for syncing the database.
Uses the `wal2json` plugin as the indicator that these are our invalidator's slots.
> Only delete slots that use wal2json to prevent killing replication slots

- server/src/instant/db/datalog.clj
- server/src/instant/db/instaql.clj
We forgot to call `hsql/format` on the query, so the hash was including the variables in it.
This PR does the hash on the instaql forms, replacing the specific values in the where clause with their type. For example:
```clj
{:users {:$ {:where {:name "Daniel"}}}}
=> {:users {:$ {:where {:name :string}}}}
```
That way we can more easily figure out which query generated the hash.
If we're calling datalog/query from outside instaql, then we'll fall back to calling `hash` on the result of the parametrized  first arg from `(hsql/format query)`.
> Extend the query hash

- client/packages/cli/index.js
- client/packages/core/__tests__/src/instaml.test.js
- client/packages/core/__tests__/src/instaql.test.js
- client/packages/core/__tests__/src/instaqlInference.test.js
- client/packages/core/__tests__/src/schema.test.ts
- client/packages/core/src/schema.ts
- client/sandbox/admin-sdk-express/src/with-schema.ts
- client/sandbox/cli-nodejs/instant.schema.ts
- client/sandbox/react-native-expo/app/play/colors-schema.js
- client/sandbox/react-nextjs/pages/play/color-schema.tsx
- client/sandbox/react-nextjs/pages/play/missing-attrs.tsx
- client/sandbox/react-nextjs/pages/play/operators.tsx
- client/sandbox/react-nextjs/pages/play/query-like.tsx
- client/sandbox/react-nextjs/pages/play/strong-todos.tsx
- client/sandbox/strong-init-vite/instant.schema.ts
- client/sandbox/vanilla-js-vite/src/schema.ts
- client/www/pages/docs/cli.md
- client/www/pages/docs/patterns.md
- client/www/pages/docs/schema.md
- client/www/pages/docs/strong-init.md
- client/www/pages/docs/users.md
- client/www/pages/labs/platform_demo.tsx
This PR: 
- Deprecates `i.graph` in favor of `i.schema`
- Uses `i.schema` throughout our codebase
- Updates cli's `pull` schema to create a file with `i.schema` rather than i.graph
**Some stuff punted** 
I am punting a few pieces of work in strong init, for a future release: 
1. Better format for links
a. I was not 100% sure it would be a good idea to remove link names. They indeed aren't necessary, but it would make migrating from i.graph more cumbersome, and it's not clear to me that `links: Array<link>` is the better approach. I think we can look into this as a separate project later
2. Better typing for `where`
a. @dwwoelfel (and our users) pointed out that right now `where` does not use type info. I think we _can_ make it use type info. I'm thinking we ship this as a separate unit of …
> [strong-init][cli] make i.schema the default

- client/packages/cli/index.js
- client/sandbox/strong-init-vite/instant.schema.ts
**Context** 
We write `rooms` schema inside schema.ts. However, the backend doesn't currently store this schema. 
This could lead a problem, where if the user does a `pull` and chooses to overwrite, they will lose their `rooms` info. 
**Fix** 
We keep the existing schema file, and re-create the 'rooms' section if it's possible.
**Longer-term** 
It's still not 100% ideal, the user would lose comments, or if they wrote particular types, like: 
```typescript
i.entity<MyTypeOverride>(...)
``` 
In the future, we may want to use something like https://github.com/benjamn/recast to modify the code as an ast. But for now, this already an improvement.
> [cli] persist `rooms` info across pulls

- client/packages/cli/index.js
- client/sandbox/strong-init-vite/instant.schema.ts
- server/src/instant/model/schema.clj
- I realized we can set the checked types for when we create attrs too
- I also fixed up a few bugs in cli (we were printing json twice in verbose mode), and had a bug in `attrRevName`
> [cli][schema] use checked-types when creating new attrs, show rev ident

- server/resources/migrations/43_specify_public.down.sql
- server/resources/migrations/43_specify_public.up.sql
We're having an issue during restore and during logical replication where postgres can't find the inner function in the `triples_value_valid_value` check. 
It seems to be an issue with the search_path--I can fix it by adding `SET search_path = public;` to the top of the dump file. I found [this on the mailing list](https://www.postgresql.org/message-id/flat/D2B9F2A20670C84685EF7D183F2949E2373D64%40gigant.nidsa.net#8132cc2fa455dd1f1bb02c63cdd04678) that basically says this is the expected behavior and you shouldn't set the search path.
To fix it, we can just specify `public.our_function` when calling functions inside of functions.
I did a `pg_dump --schema-only` on production and copied all functions that use internal functions and prefixed those with `public` for the `up` migration. The …
> Qualify internal pg function calls with schema

- server/src/instant/db/datalog.clj
- server/src/instant/db/model/attr_pat.clj
- server/src/instant/db/model/triple.clj
- server/test/instant/db/instaql_test.clj
I noticed a curious error in prod: 
https://ui.honeycomb.io/instantdb/environments/prod/datasets/instant-server/result/r4cm97gTDzi/trace/aAmj4xsbSfo?fields[]=s_name&fields[]=s_serviceName&span=432079d52cf13865
It was something along the lines of: 
```bash
clojure.lang.ExceptionInfo: [instant-exception] SQL Exception: undefined-function {:instant.util.exception/type :instant.util.exception/sql-exception, :instant.util.exception/message "SQL Exception: undefined-function", :instant.util.exception/hint {:table nil, :condition :undefined-function, :constraint nil}, :instant.util.exception/pg-error-data {:sql-state "42883", :condition :undefined-function, :table nil, :constraint nil, :server-message "operator does not exist: timestamp with time zone = character varying", :detail nil}
``` …
> Coerce date data types when we use equality comparisons too

- server/refinery/rules.yaml
We tried using `name` as a sample key but this wasn't working as expected -- refinery was concatenating the span names of the parent traces. Found this in the [refinery docs though](https://docs.honeycomb.io/manage-data-volume/sample/honeycomb-refinery/sampling-methods/#fieldlist)
> As of Refinery 2.8.0, the root. prefix can be used to limit the field value to that of the root span. For example, root.http.response.status_code will only consider the http.response.status_code field from the root span rather than a combination of all the spans in the trace. This is useful when you want to sample based on the root span’s properties rather than the entire trace, and helps to reduce the cardinality of the sampler key. 
So now we use `root.name` instead of `name` -- @dwwoelfel also suggested we …
> [Refinery] use DynamicSampler

- server/.clj-kondo/hooks/defsql.clj
- server/src/instant/jdbc/failover.clj
- server/src/instant/jdbc/sql.clj
- server/test/instant/db/datalog_test.clj
Adds a script that will run a check that all of the data in the primary is also in the replica.
Right now it takes about an hour or two to run--as the db grows, we may have to do a spot check instead of checking everything.
> Add script to check data on replica

- server/Makefile
- server/deps.edn
- server/src/instant/scratch/backtest.clj
I originally wrote this thinking we would spin up a prod db instance. But I realize this is not needed, and can be done in comments. 
In which case, no need for a separate command. 
> remove run opts for backtest

- server/Makefile
- server/scripts/prod_connection_string.sh
Updates the db connection string script. To update in the future, we'll just need to update the `cluster_id` var in the script.
> [db-upgrade 3/3] Update connection string helper to point to new db

- server/resources/migrations/44_add_daily_app_transactions.down.sql
- server/resources/migrations/44_add_daily_app_transactions.up.sql
- server/src/instant/config.clj
- server/src/instant/core.clj
- server/src/instant/scripts/daily_metrics.clj
- server/src/instant/scripts/metrics.clj
- server/src/instant/util/date.clj
This PR does two things 1) speeds up our monthly metrics job and 2) sends us a daily ping with active apps and devs.
**speeding up metrics**
I realized we could speed up our monthly metrics query by changing how we calculated daily app transaction counts. I also thought it would be nice to save these counts to a table to make our metrics generation even faster. Generating the metrics and bar charts is pretty instant now.
**daily metrics ping**
Stopa mentioned earlier that he wanted a more frequent feel for number of users/apps. I played around with sending images to discord, but they get cut off in the previews which makes it less fun to look at. Figured it would be nice to just send some plan numbers in a separate discord channel
**Next steps before merging**
> [Metrics] Add daily metrics job

- server/src/instant/scripts/daily_metrics.clj
Ran this in prod and noticed some small bugs in populating `daily_app_transactions` -- ran this and all looks well, and indeed generating prod metrics takes <1s now
> [Metrics] Minor fixes

- server/src/instant/reactive/query.clj
- server/src/instant/util/logging_exporter.clj
Removes one span entirely. I don't think the `collect-instaql-results-for-client` span was really helpful for anything.
Stops logging a few more spans to cloudfront in production:
- handle-refresh/send-event!
- store/record-datalog-query-finish!
- store/record-datalog-query-start!
- store/swap-datalog-cache-delay!
- store/bump-instaql-version!
- store/add-instaql-query!
> Send less log data to cloudfront in production

- client/www/components/dash/explorer/Explorer.tsx
- server/src/instant/model/schema.clj
We weren't making ids unique when they were generated from a cli push or when you created a new namespace from the UI. This PR fixes both.
> Set the `unique?` flag on attrs when they're created

- server/src/instant/jdbc/failover.clj
Accidentally incremented the wrong tx-id when reseting the seq, so we were never going to complete the db swap.
The good news is that we rolled back with minimal issues (there were a few handle-receive timeouts for in-progress queries).
> Fix the db swap script

- server/src/instant/db/model/triple.clj
Kosmik reported slow delete transactions. 
Looking into this, I realized it was because we compared to `value-md5`: 
```
;; Delete ref triples where we're the value
:vae
[:= :value-md5 [:md5 [:cast [:to_jsonb id] :text]]]
```
This worked, but would end up in a scanning all app triples. This is because our `vae` index actually works on the jsonb value, rather then the md5 value. By switching to the jsonb value, we could now use the `v` based indexes. 
```clojure
(time
(do
(permissioned-tx/transact!
ctx
(admin-model/->tx-steps!
ctx
(map (fn [sticker-id]
["delete" "stickers" sticker-id])
sticker-ids)))
:done))
;; Before 
; eval (current-form): (time (do (permissioned-tx/transact! ctx (admin-model/->tx-step...
; (out) "Elapsed time: 15090.590791 msecs"
:done
;; After
; eval (current-form): …
```
> [delete-entity] make delete-entity use vae index for lookups

- server/scripts/prod_tunnel.sh
I wanted to ssh into prod to diagnose some query issues. I noticed that prod_tunnel.sh was failing, as we now have multiple instances. 
I updated the script to grab the first instance. 
> [script] nab the first instance from prod_tunnel.sh

- client/packages/core/src/Reactor.js
- client/packages/core/src/utils/PersistedObject.js
- client/sandbox/react-nextjs/pages/play/pending-transactions.tsx
Previously, transactions had 3 phases in the lifetime
**1. pending**
The transaction was created, but hasn't been processed by the server. 
We apply it right away to all queries.
**2. ok**
The server said this transaction was `ok`. We record this information, because we don't want to send it again.
**_However_, we can't delete the transaction from the queue yet**. 
Why? Because this transaction has not fully been reflected in active queries.
**3. refresh -> delete**
The server has refresh queries. At this point, we can delete pending mutations. 
The kosmik folks reported an edge case, where queries were missing pending mutations. This is because we were too eager about _when_ we removed pending transactions. We removed them _even_ during add-query-ok, which mean some queries may not have …
> [mutations] apply mutations after transact-ok

- server/src/instant/scripts/daily_metrics.clj
Metrics had an off by one issue where the job runs at date X but we only have date for date X - 1. This PR fixes that, I also removed an unused transaction count and figured we should just run this on the weekdays to not ping #team on the weekends
> [Metrics] Daily metrics sm

- client/www/pages/docs/schema.md
AppSchema type export, as described in https://biomejs.dev/linter/rules/use-export-type/ or https://typescript-eslint.io/rules/consistent-type-exports/ (was giving me an error in VSCode with Biome plugin)
> Docs: AppSchema type export

- server/resources/migrations/45_remove_entity_id_from_indexes.down.sql
- server/resources/migrations/45_remove_entity_id_from_indexes.up.sql
@stopachka found that this improves the performance of some queries that use the `ave` indexes with nested loop joins when there are multiple `e` in the index. The loop causes postgres to do a bunch of inefficient index scans, slowing down the query. When we take the `e` out of the index, postgres no longer tries to use it in a nested loop.
More context on the underlying issue in @stopachka's stackoverflow post: https://dba.stackexchange.com/questions/344103/postgres-graph-query-gets-slow-because-of-a-nested-loop-join
Ran a backtest and we see some major improvements for a few queries and basically no change for the rest of the queries:
Deployment process:
1. Add all indexes concurrently:
```sql
create index concurrently triples_string_trgm_gist_idx_no_e on triples using gist (
app_id, …
```
> Remove entity_id from some indexes

- server/src/instant/db/datalog.clj
- server/test/instant/db/instaql_test.clj
Uri noticed an error when running a query like: 
```edn
{:items
{:$
{:order {:serverCreatedAt "desc"},
:limit 5,
:where
{:foo.bar {:$gte 5}}}}}
```
Because of the `foo.bar`, it was possible to get multiple instances of `item` entity ids repeating. When we updated the select statement to insert an `order-by` to the query, we could end up over-filtering. 
This is because of the CTE had:
```
entA
entA
entA 
entB 
```
With a `LIMIT` of 3, we would just return `entA`. 
To fix this, I updated `add-page-info`, to include a `select-distinct-on`
> make sure we run `distinct-on` when paginating

- client/packages/cli/index.js
- client/packages/core/src/index.ts
- client/packages/react-native/src/cli.ts
- client/pnpm-lock.yaml
- client/sandbox/react-native-expo/instant.perms.ts
- client/sandbox/react-native-expo/instant.schema.ts
- client/sandbox/react-native-expo/package.json
- client/www/components/dash/Perms.tsx
- server/src/instant/model/rule.clj
Made a series of tweaks to CLI, from what I noticed from the user session with Zack. 
1. `npx instant-cli init` now detects expo, and shares the env var for expo (EXPO_PUBLIC...) 
2. We fixed a bug where if the user had no rules, we generated a perms file with an erroneous semicolon. 
3. Added instant-cli to react-native-expo, so we can test it there too.
4. Made `$default` an allowed key in InstantRules.ts, and in Perms Editor
5. Made it so `$default` is no longer a reserved name on the backend
I realized that CLI has been broken for react-native. The main reason, was that when we ran `loadConfig`, we would evaluate `instant.schema.ts` and `instant.perms.ts` in a node environment. 
Inside the file, we would improve from our library like so:
```ts
import { i } from …
```
> Suite of cli and perms bugfixes

- client/www/pages/docs/start-rn.md
When doing our user session with Zack, I realized that our RN starter was outdated. Mainly: 
1. Expo now creates typescript files by default
2. Expo has a router, so the `App` file is now inside a subdirectory
I also felt like our demo colors app could use a bit of a spruce-up. I added some background on our text, and made the default color white.
> [docs] update rn starter

- .github/workflows/js.yml
- client/package.json
- client/packages/core/__tests__/src/instaql.bench.js
- client/packages/core/package.json
- client/turbo.json
Could potentially help us catch performance regressions. Outputs in the test output: https://github.com/instantdb/instant/actions/runs/12303534856/job/34339091865
> Add a benchmark to the tests

- client/packages/cli/index.js
**Context**
When existing apps pull schema, we're going to write out all attributes as `any`. 
This is a bit frustrating as an upgrade experience, as now developers need to manually update every column with it's actual type. 
**Potential solution** 
Well, one thing we _do_ have is inferred types. This PR makes it so if we detect an attribute that has just _one_ inferred type, then we choose that when someone writes `pull` schema. 
**Some tradeoffs in doing this** 
Mainly, it's a bit surprising that we _use_ the inferred type.
1. The user will have to write `push` schema, to actually enforce these types. The user may not know this 
a. Perhaps it's not too big a deal though, as eventually they _will_ write push schema and see it. 
2. What if the user _intentionally_ wanted to leave an …
> [cli] use inferred-types when using pull schema

- server/src/instant/flags.clj
- server/test/instant/reactive/session_test.clj
It's already the default in prod (through the config), this will make it the default in dev also.
Updates some of the tests to also test hazelcast. 
Note for later: to do a true end-to-end test of Hazelcast, we'd need to spin up multiple instances of the instant server and check that the data syncs between them.
> Make hazelcast the default

- client/packages/core/__tests__/src/instaql.test.js
- client/packages/core/src/instaql.js
- client/packages/core/src/queryTypes.ts
- client/www/pages/docs/instaql.md
- server/src/instant/db/datalog.clj
- server/src/instant/db/instaql.clj
- server/src/instant/db/model/attr_pat.clj
- server/src/instant/reactive/store.clj
- server/test/instant/db/instaql_test.clj
Adds support for `ilike`, which is just like `like`, but it's case-insensitive.
Example:
```javascript
const query = {
goals: {
$: {
where: {
'todos.title': { $ilike: '%stand%' },
},
},
},
};
const { isLoading, error, data } = db.useQuery(query);
console.log(data)
{
"goals": [
{
"id": standupId,
"title": "Perform standup!",
},
{
"id": standId,
"title": "Stand up a food truck.",
}
]
}
```
> Add support for case-insensitive like

- server/src/instant/db/model/attr.clj
- server/src/instant/reactive/query.clj
- server/src/instant/reactive/store.clj
The spam filter is preventing the `useSchemaQuery` on the dashboard from catching changes to attributes.
When you add a namespace or index an attr, you won't see the changes on the dashboard until you refresh.
The PR fixes that problem by embedding the attrs into the query hash we use to determine if the query result changed.
> Don't filter spam if the attrs changed

- client/packages/cli/index.js
- client/sandbox/react-native-expo/instant.perms.ts
- client/sandbox/react-nextjs/pages/play/stickers.tsx
- client/www/pages/docs/permissions.md
@laurentpayot Noticed there was an error in our `isOwner` example where indeed an un-authed user could pass the `isOwner` example. Updating all references to these
> [Docs] Fix permissions typos

- server/src/instant/db/datalog.clj
- server/test/instant/db/instaql_test.clj
Consider the following schema: 
```javascript
entities: {
conversations: i.entity({
// ...
}),
messages: i.entity({
// ...
}),
},
links: {
messageConvo: {
forward: { on: 'messages', has: 'one', label: 'conversation' }, 
reverse: { on: 'conversations', has: 'many', label: 'messages' }
},
},
```
Say I create 3 convos, with 10 messages each.
If I query:  
```edn
{:conversations {:$ {:limit 2 :where {:messages.time {:$gte 0}}}}}
```
**I will get _1_ result back, rather then 2** 
This is because the datalog query looks something like: 
```
[?m :time (> t)] 
[?m :convo ?c] 
```
When we add our `order` information, we actually add it to `[?m :convo ?c]`: 
```sql
WITH match_0_0 AS MATERIALIZED (
SELECT
entity_id AS match_0_0_entity_id,
attr_id AS match_0_0_attr_id,
value AS match_0_0_value_blob, …
```
> fix distinct-on with limit

- client/packages/cli/index.js
- client/packages/cli/package.json
- client/packages/cli/src/toggle.js
- client/pnpm-lock.yaml
From user sessions with Zack and Cam: 
When users were prompted to open a browser, create an app, etc, they were surprised that the default answer was 'No'. They pressed enter, and saw their CLI session end. 
**I made two changes:**
1. I updated it so the default answer is 'yes' for non-destructive questions
2. I introduced a new kind of toggle, which visually shows the 'yes' or 'no' answer, so it's clearer what is selected: 
> Make our Y/N prompt a toggle, and make default answer yes for non-destructive questions

- client/packages/core/src/queryTypes.ts
- client/sandbox/strong-init-vite/src/typescript_tests_backwards_compat_date.tsx
Nacho mentioned type issues when he put `Date` in his schema. 
I made an example with a `Date` type, and realized that our `Expand` utility broke out the type: 
I updated `Expand` to exclude builtin types, and my hope this will make Nacho's upgrade seamless. 
> [types] Expand should ignore builtins

- client/packages/admin/src/index.ts
- client/packages/core/src/index.ts
- client/packages/core/src/instatx.ts
- client/packages/core/src/schemaTypes.ts
- client/packages/react-native/src/index.ts
- client/packages/react/src/index.ts
- client/sandbox/strong-init-vite/src/typescript_test_abstract.tsx
https://github.com/instantdb/instant/issues/493 
Uri mentioned issues trying to create generic functions for creating entities. 
I looked deeper into his repro, and the underlying issue was: 
```typescript
Omit<Entity<T>, 'id'>
```
Since technically `InstaQLEntity` can include links, this was not matching up with `UpdateParams`.  Perhaps we can hint better to typescript, that since we gave an empty object, `Entity` would have no links, and that _should_ pass for `UpdateParams`. 
For now I just exposed `UpdateParams` directly, and added Uri's example in our playground. 
> [types] add UpdateParams and LinkParams

- server/src/instant/db/model/triple.clj
- server/src/instant/reactive/invalidator.clj
I saw a [few bugs](https://ui.honeycomb.io/instantdb/environments/prod/datasets/instant-server/result/iNdPFYRibPW?tab=traces) in our logs, with the error: 
```bash
class java.time.Instant cannot be cast to class java.lang.Number (java.time.Instant and java.lang.Number are in module java.base of loader 'bootstrap')
```
In datalog, we convert values for checked-data-type = date into java.time.Instant 
```edn
topicFromQuery [:ea eid aid java.time.Instant<...>]
```
When we generate `topics-for-triple-insert`, we keep the underlying number value: 
```edn
topicFromInvalidator [:ea eid aid 1735658560430]
```
This means that when we run `match` on the topic, this causes a type mismatch 
I went ahead and updated `topics-for-triple-insert`, to convert dates to java.time.Instant
Right now I realize …
> [invalidator] fix topic error from date insert

- client/packages/core/src/schemaTypes.ts
- client/sandbox/strong-init-vite/instant.schema.v2.ts
- client/sandbox/strong-init-vite/src/typescript_tests_experimental_v2.tsx
Uri pointed out an issue in https://github.com/instantdb/instant/issues/459 
If you have a `messages` entity like so:
```javascript
messages: i.entity({
content: i.string(),
createdAt: i.date().optional(),
}),
```
Then using `InstaQLEntity`: 
```typescript
type CoreMessage = InstaQLEntity<AppSchema, "messages">;
const mWithOptionalFieldWorks: CoreMessage = { 
id: '1', 
content: 'hello',
};
```
You end up having an error, because typescript _expects_ `createdAt` to be present, even though it's optional 
I updated how we resolved attrs, so that instead of generating: `createdAt: Foo | undefined`, we generate: `createdAt?: Foo | undefined`
> [ts] make optional fields work if the key is ommited

- client/packages/core/src/clientTypes.ts
- client/sandbox/strong-init-vite/src/typescript_tests_experimental_v2.tsx
Uri mentioned that the typing for `useAuth` was incorrect: 
https://github.com/instantdb/instant/issues/471
In the case where isLoading: false and error: null, `user` should be typed as `User | null` rather than `User | undefined` 
> [ts] improve the AuthState type

- server/src/instant/jdbc/failover.clj
- server/src/instant/jdbc/sql.clj
- server/src/instant/reactive/query.clj
- server/src/instant/reactive/session.clj
- server/src/instant/reactive/store.clj
- server/src/instant/util/logging_exporter.clj
- server/test/instant/jdbc/sql_test.clj
- server/test/instant/reactive/store_test.clj
This prevents in-progress datalog queries from getting cancelled when there are multiple sessions waiting on the query.
Previously, we could get into a situation like this:
1. user-1 opens a session and runs query-a
2. user-2 opens a session and runs query-a
3. user-1 closes their session
4. we cancel all in-progress queries, including query-a
5. user-2 gets an error for query-a because the query was cancelled
This PR moves the query execution to a separate call stack where it won't get canceled if the parent is canceled. 
To keep the behavior where we cancel queries that exceed the `handle-receive-timeout-ms`, we add another future that is in the call stack. If it gets canceled and there are no other threads waiting on the query, then it will cancel the query.
> Protect datalog cache from early cancellation

- server/src/instant/db/datalog.clj
- server/src/instant/db/instaql.clj
- server/test/instant/db/instaql_test.clj
Generalizes @stopachka's fix in https://github.com/instantdb/instant/pull/647 to work with ordering on arbitrary fields.
With this change we'll use the symbol map to look up the entity id that we need to use as our secondary ordering key. We could look it up from the page-pattern, but I passed it in directly (as `eid-sym`) to make things a little more explicit.
> Ordering fix

- server/src/instant/db/datalog.clj
- server/src/instant/db/model/attr_pat.clj
- server/src/instant/db/model/triple.clj
- server/src/instant/util/instaql.clj
In postgres, we can save date values as strings:
```
SELECT triples_extract_date_value('"2025-01-03"');
```
However, we weren't able to parse "2025-01-03" in java. We would get: 
```
; (err) Text '2025-01-03' could not be parsed at index 10
```
This is because we used `java.time.Instant/parse`. I updated our codepath, so we now handle _both_ date time parsing, and date parsing. 
> Support ISO 8601 date formats, not just date time

- server/src/instant/gauges.clj
- server/src/instant/util/logging_exporter.clj
We're seeing some odd spans in `invalidator/work` where there are long pauses between calls to `invalidator/send-refresh!`. It should be very fast, so I'm wondering if we might be hitting a gc pause there: https://ui.honeycomb.io/instantdb/environments/prod/datasets/instant-server/result/cvi3aghpm6F/trace/xWunNWZ1aNq?fields[]=s_name&fields[]=s_serviceName&span=e1c074bcfec331e2
With this change, we'll both log the gc events and update the gauges on any gc event. 
If garbage collection is causing the pauses, then we should should see an increase in the `gc.count` attribute between the two spans. We wouldn't see that before because we only collect the gauges every second.
> Log when the garbage collector runs

- server/src/instant/db/datalog.clj
- server/test/instant/db/datalog_test.clj
- server/test/instant/db/instaql_test.clj
We can already write queries that have lookups in the `e` position: 
```edn
[[handle-aid "stopa"] :users/email ?email]
```
However, we _cannot_ write lookups in the `v` position: 
```edn
[?bookshelf :bookshelves/owner [handle-aid "stopa"]]
```
We particularly need this in cel.clj, as we write a query with ids in the `v` position.
I added support for lookups on the `v` side of our query. 
There are two things of note:
**How we detect lookups in the `v` side** 
Technically, a user _could_ have any jsonb value on the `v` side (However, afaik we don't allow jsonb values in where clauses). Still, we detect a lookup by specifically checking that it is: a) a vector b) first element is a uuid and c) it is count 2. 
**adding a av check** 
Previously, our lookup subquery did a search for entity_id, …
> [lookups] support lookups in the `v` portion

- server/src/instant/gauges.clj
Setting `name` in attributes overrode the `name` field, so we weren't seeing any "name=gc" events.
> Don't override name in gc span

- server/src/instant/config.clj
- server/src/instant/util/tracer.clj
I think this might fix the issue identified in https://github.com/instantdb/instant/pull/670, where we see random pauses in between spans.
[According to the docs](https://docs.oracle.com/en/java/javase/20/docs/api/java.base/java/net/InetAddress.html#getHostName()), `getHostName` can do some i/o.
We might be pausing in `with-span` while we look up the hostname. The hostname shouldn't ever change, so it's better to just calculate it once in the delay, and then always use the same value.
> Calculate hostname once

- server/resources/migrations/47_add_replica_id_to_daily_metrics.down.sql
- server/resources/migrations/47_add_replica_id_to_daily_metrics.up.sql
We had another migration on 12-06 and wanted to delete some inflated data from this metrics table but got an error due to no replica id being set. This PR enables it!
> Add replica id to metrics

- server/src/instant/reactive/session.clj
We saw a spike in timeouts after the increase. Need to figure that out before increasing.
> Reset the number of receive-workers

- client/Makefile
- client/pnpm-lock.yaml
- client/pnpm-workspace.yaml
This lets us call `replace-images` for the newsletter without needing a separate `npm install` step.
> Tell pnpm where to find the replace-images folder

- client/packages/core/src/Reactor.js
- client/packages/core/src/utils/object.js
- server/Makefile
- server/deps.edn
- server/dev-resources/circleci_test/config.clj
- server/dev/user.clj
- server/docker-compose.yml
- server/flags-config/instant.perms.ts
- server/flags-config/instant.schema.ts
- server/src/instant/config.clj
- server/src/instant/core.clj
- server/src/instant/flags.clj
- server/src/instant/flags_impl.clj
- server/src/instant/reactive/ephemeral.clj
- server/src/instant/reactive/session.clj
- server/src/instant/runtime/routes.clj
- server/src/tool.clj
- server/test/instant/reactive/invalidator_test.clj
- server/test/instant/reactive/session_test.clj
- server/test/instant/test_core.clj
Uses editscript to compute a diff between the old and new presence data and sends a diff to the client instead of sending the full presence object.
> Send diffs for presence

- server/src/instant/reactive/session.clj
Some older clients won't send the `version` field
> Fixes `Invalid semver version null` errors

- server/src/instant/core.clj
- server/src/instant/jdbc/wal.clj
- server/src/instant/reactive/invalidator.clj
Tracks two latency metrics for the invalidator:
1. Queries the database every minute to calculate the difference in bytes between the last available wal entry and where our replication subscription is on the log. We'll send that metric with the rest of the `gauges`.
2. Calculates the number of milliseconds between when we process a transaction in the invalidator and when that transaction was created in the database.
There are still a lot of steps where latency could be introduced, but this gives us a little more insight into the system.
> Track some wal latency metrics

- server/src/instant/util/logging_exporter.clj
Removes a few noisy fields from the logs we send to cloudwatch and a few spans that aren't very useful.
> Reduce the number of logs we generate

- server/src/instant/reactive/session.clj
Still needed to check if the `version` was nil.
> Hopefully the last semver fix

- client/www/components/docs/Layout.jsx
> fix: logick for next link in bottom article nav

- server/src/instant/db/datalog.clj
- server/test/instant/db/datalog_test.clj
- server/test/instant/db/instaql_test.clj
A user mentioned that some of his queries got slower. The query looked something like: 
```edn
{:conversations 
{:$ {:order {:serverCreatedAt "desc"}, :limit 100, 
:where {:groups "...", :messages.time {:$gte ...}}}, 
:messages {}}}
```
After investigating, the problem was like so: 
`messages` expanded out to about 16000 entities. When we tried to resolve permissions, we would do a batched query, which would include all 16K uuids. 
When datalog generated the list of `:or` conditions,  it would take postgres about a minute and a half, just to parse the query. 
Changing the condition to an `IN` improved the perf to under 5 seconds. 
> [datalog] use `IN` for value comparison

- client/www/components/dash/explorer/Explorer.tsx
- client/www/lib/hooks/explorer.tsx
In addition to free-form searching for string-indexed attributes, we also support exact search and (for indexed numbers or dates) `<`, `>` comparison attrs:
https://github.com/user-attachments/assets/4a98b790-7418-44d5-9d2c-00a7dbd8b092
Potential improvements:
It might not be obvious to people what the `:` operator means? If we gave them some examples using real data, e.g. show `pageCount:100, pageCount>100` in the dropdown, maybe that would help? It was a little too complex for me to tackle just now.
We're pretty permissive in the parsing. For example, if you type `number: number:hello number:100`, we'll ignore the incomplete `number:` and the invalid `number:hello` and just show you `number = 100`. Some better error handling so that we could show you where the query is invalid would be …
> Support exact matches and <, > in filter input

- .github/workflows/clojure.yml
- server/.ebextensions/resources.config
- server/src/instant/reactive/ephemeral.clj
Removes the placement group so that we can try deploying into another availability zone.
Tested in staging and it did appear to deploy an instance without a placement group.
> Remove placement group

- client/www/pages/docs/permissions.md
The current permission examples for the `$default` namespace don't work since the rules are incorrectly defined as `boolean`. InstantRules requires permissions to be defined as `string`.
Updated the example to ensure compatibility and prevent confusion.
> docs(permissions): fix InstantRules not typed as string

- server/src/instant/db/datalog.clj
- server/src/instant/db/instaql.clj
- server/src/instant/db/model/attr_pat.clj
When we do an `$isNull` query, we put something like `{:$isNull {:attr-id aid}}` in the value position. The pattern looks something like `[?e aid {:$isNull {:attr-id aid}}}]`.
When we choose the triples index to look at, we use the `av` index if we have a constant value for an indexed attr. Normally a non-constant is a symbol, e.g. `?v` in `[?e aid ?v]`. We saw a map for `$isNull` instead of a symbol, so we thought it was a constant value and we used the `av` index where the value wasn't actually known.
Now we'll check for `$isNull` before we say something is a constant.
> Don't treat isNull as a constant

- server/src/instant/grouped_queue.clj
- server/src/instant/util/async.clj
I noticed that our traces for `invalidator/work` were including a lot of extra spans past the end of the top-level trace. This happens because we start the worker in an `on-add` callback to `grouped-queue/put!`, so it was inheriting the parent span from the bindings.
Now we have a new type of virtual future that doesn't propagate bindings. That gives our workers a bit more isolation. I also gave them their own virtual thread executor--doesn't do much now, but it would let us more thoroughly "shutdown" a grouped-queue in the future.
Much easier to review with whitespace off: https://github.com/instantdb/instant/pull/709/files?w=1
> Run the receive-queue workers without bindings

- server/src/instant/gauges.clj
- server/src/instant/util/logging_exporter.clj
- server/src/instant/util/tracer.clj
The main change here is to have each machine send gauges every 30 seconds instead of attaching them to each span. In my testing, that reduces the time it takes to build a span by about half.
The downside is that we'll get a little less granularity on the gauge metrics, but the upside is that the spans create faster and we'll be sending much less data.
There are also some other smaller performance improvements in the logging tracer: 
1. Use a batch processor in prod for the logging exporter (flushes at least every half second)
2. Remove all reflection warnings
3. Use String.replace instead of a regex to remove newlines in prod
4. Use a StringBuilder to build the attrs string
> Send gauges periodically instead of on each span

- server/src/instant/scripts/daily_metrics.clj
What it says on the tin. This should give enough time for the daily job to run and calculate new activity for mulitple days (e.g. for monday computing friday, sat, and sun metrics).
> [Metrics] Increase metrics job timeout

- server/src/instant/db/model/attr_pat.clj
- server/src/instant/db/model/triple.clj
Also makes it easier to add new formats, just add another function to the `date-parsers` list.
> Add another date format for triples

- server/src/instant/reactive/invalidator.clj
- server/test/instant/reactive/invalidator_test.clj
Updates the invalidator to use the grouped queue. This should do two things to give instant users a better experience:
1. Each app gets its own logical queue, so it should isolate apps a bit more so that all apps don't slow down invalidation if one app dumps a ton of transactions in the queue
2. Records in each app's queue are combined. If an app sends a ton of updates faster than they can be processed, then we'll generate less load on the system when we handle their transactions.
The per-app isolation is still incomplete because the store-conn will be a bottleneck and we don't have any queuing in transact. It should still be a big improvement, as long as we don't run into too much contention on the store-conn.
> Use the grouped queue in the invalidator

- server/src/instant/db/datalog.clj
This was causing postgres to use a nested loop with a join filter that caused it to filter many more rows than it needed to. I think the ave index allows it to be faster because the entity_id is in the index.
I was hoping the typed indexes would help with the sorting, but we may have to restructure the queries to get that benefit.
Did a back test (searching for queries that included "order") and didn't see any queries that got much worse, but many queries got much better.
<details>
<summary>Explains</summary>
With the type check:
```
CTE Scan on match_0_1  (cost=17.34..17.36 rows=1 width=200) (actual time=2587.296..2587.366 rows=100 loops=1)
CTE match_0_0
->  Index Scan using vae_index on triples  (cost=0.56..8.59 rows=1 width=117) (actual time=0.045..4.422 rows=1221 loops=1)
Index Cond: …
```
> Remove type-where in paginated queries

- server/src/instant/storage/s3.clj
- server/src/instant/util/storage.clj
Right now the storage tab only fetches the first 1k files from s3 for an app. This caused some confusion when files weren't showing up [[Discord]](https://discord.com/channels/1031957483243188235/1329216151288414352)
This PR adds pagination logic for instances when there are >1k files in a path.
> [Storage] Paginate storage tab

- client/www/components/docs/Fence.jsx
- client/www/components/ui.tsx
Noticed this error from react: 
Made a quick update so we don't spread the key. 
> [sm] fix react warning on fences

- server/src/instant/db/transaction.clj
- server/src/instant/lib/ring/websocket.clj
- server/src/instant/reactive/invalidator.clj
- server/src/instant/reactive/session.clj
- server/src/instant/util/e2e_tracer.clj
Tracks the latency between when we created the transaction and when we execute a step in the invalidation pipeline.
This will let us create a metric we can use to track the experience of "click on checkbox in one window and watch it update in another window" and create alerts if it's too slow. 
It's not perfect, because we don't know when the trace is fully finished, but tracking it on send-refresh or json-delivered is pretty close.
I attempted to do this with Honeycomb's derived columns, but there doesn't appear to be any way to calculate the difference between a span's timestamp and the root timestamp.
> Attach latency_ms to e2e events

- server/deps.edn
- server/docker-compose.yml
We're currently using g1c and see 30-50ms pauses every ~45 seconds.
This switches us to zgc, which should reduce the number of stop-the-world pauses.
We'll be able to look at the `gc` events to see how many pauses we get.
> Use the zgc garbage collector

- server/.ebextensions/resources.config
We disabled the placement group while we were transitioning to a different az.
Let's see if this drops the presence latency.
> Put us back in the placement group

- .github/workflows/clojure.yml
- server/src/instant/config.clj
- server/src/instant/core.clj
- server/src/instant/jdbc/sql.clj
- server/src/instant/util/aws.clj
- server/src/instant/util/crypt.clj
- server/src/instant/util/tracer.clj
A few changes to make it easier to track down problems in the database:
1. The instance_id is logged on every span
2. The process_id in prod includes the instance_id. This makes it easy to get back to the instance from the replication slot name and the application name
3. Adds a log before and after each startup step in instant.core. When we have issues during startup, this makes it a lot easier to track down which step is causing the issue.
4. Annotate every sql query with its span_id and trace_id by prepending it with a comment. It looks like this:
> More logging

- client/packages/react/src/InstantReactRoom.ts
We had a few instances where we would return functions that didn't have stable values. This would cause consumers to re-render unnecesarily. I looked over the our hooks and added `useCallback` and `useMemo` in places that could keep stable values.
> Add memoization in db.rooms hooks

- server/src/instant/reactive/ephemeral.clj
- server/test/instant/reactive/session_test.clj
I had a flaky test run because hazelcast was slow to start. I found this stackoverflow post explaining how to start Hazelcast in standalone mode: https://stackoverflow.com/a/65594539/361969
Now Hazelcast starts in ~50ms for tests instead of ~3 seconds.
> Faster hazelcast startup in tests

- server/src/instant/grouped_queue.clj
- server/src/instant/reactive/invalidator.clj
I noticed a lot of time is spent waiting in `handle-receive` for simple things like `:refresh-presence` or `:server-broadcast` and I have a hunch that it's because the invalidator is doing a lot of cpu-heavy work in the virtual threads. Then the virtual thread we create to call `handle-receive` gets blocked waiting for the cpu-heavy task to finish.
This PR makes the invalidator queue use a fixed set of workers, each inside a future. It seemed as fast as the virtual thread version in my testing, as long as the number of threads wasn't too high.
> Use threads for cpu-heavy invalidator workers

- server/src/instant/util/logging_exporter.clj
This will make it easier to track down the log from the span attrs we add to the query (added in #725)
> Log the span id in prod

- .github/workflows/clojure.yml
- server/.ebextensions/sysctl.config
- server/deps.edn
- server/docker-compose.yml
- server/scripts/aws_tunnel.sh
- server/src/tool.clj
Adds what we need to enable clj-async-profiler in production (following the instructions at https://clojure-goes-fast.com/kb/profiling/clj-async-profiler/production/).
Tested in staging and all looks ok.
> Enable clj-async-profiler in production

- server/src/instant/reactive/store.clj
I noticed a lot of time spent doing datalog store operations when looking at the profiler in production.
This improves some of the store operations by replacing `d/find` with `d/datoms` in a few places.
We also store a ref to the `instaql-query` in the `:subscription` entity instead of storing the instaql query itself. That lets us skip an expensive check in `add-instaql-query!` where we have to look up subscription by session-id and query. Now we can just look them up by the instaql-query entity id, since it already has the session-id in it.
> Faster store operations

- server/resources/migrations/48_add_dap_primary_key.down.sql
- server/resources/migrations/48_add_dap_primary_key.up.sql
I am testing aurora blue-green deployments again, to remind us of what the weird error was with replication slots. 
Right now I am getting the error: 
> Invalid configuration
> Creation of blue/green deployment failed due to incompatible parameter settings. See https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/blue-green-deployments-creating.html#blue-green-deployments-creating-preparing-postgres to help resolve the issues, then delete and recreate the blue/green deployment.
The only bullet we don't hit right now is: 
> Make sure that all tables in the DB cluster have a primary key. PostgreSQL logical replication doesn't allow UPDATE or DELETE operations on tables that don't have a primary key.
I know we had written: 
```sql
ALTER TABLE daily_app_transactions
REPLICA IDENTITY …
```
> [primary-key] add dap primary key

- server/test/instant/reactive/session_test.clj
We were getting some extra puts on the websocket channel stub and it was blocking the puts on our test. 
Updated the put to be non-blocking. To make sure we pull the message we're interested in off of the channel, the `blocking-send-msg` test function takes the expected op and it will keep polling the channel until it finds the message it's looking for (or until a timeout).
> Fix flaky session tests

- server/src/instant/core.clj
Fixes an issue where we are sending too many spans to Honeycomb because all of the `invalidator/work` spans have the same parent.
> Don't let init have child spans

- server/src/instant/core.clj
- server/src/instant/util/http.clj
Cleans up the http logs a bit:
1. Wraps the stripe route middleware in `compojure.core/wrap-routes` so that it doesn't get applied to all routes (we were logging some things twice)
2. Adds a `:route` field to the span that has the actual route (e.g. `/apps/:app_id` instead of `/apps/a349ea6b-8e4d-4fb8-a563-a7130f015137`)
3. Log app_id from the route params
4. Don't log preflight requests
5. Don't log the body
> cleanup http logs

- server/src/instant/config.clj
- server/src/instant/reactive/receive_queue.clj
- server/src/instant/reactive/session.clj
- server/src/instant/util/async.clj
- server/src/instant/util/logging_exporter.clj
- server/src/instant/util/tracer.clj
- server/test/instant/util/async_test.clj
We're seeing it take a long time to start a virtual future in prod, but starting a regular future is still fast.
I'd like to experiment with using fewer virtual futures as a quick bandaid. This will hopefully make ephemeral state a lot faster because it shouldn't have to hit a single vfuture.
On 1/3 of the instances, this will use `thread` for both the receive queue workers and for wrapping `handle-receive`.
> Test fewer vfutures in the receive queue

- server/deps.edn
We're seeing a lot of virtual thread pinning that lines up with when we upgraded the postgres driver in https://github.com/instantdb/instant/pull/742
I want to downgrade and see if they go away.
Stack trace looks like this:
```
VirtualThread[#3897183]/runnable@ForkJoinPool-1-worker-43 reason:MONITOR
java.base/java.lang.VirtualThread$VThreadContinuation.onPinned(VirtualThread.java:199)
java.base/jdk.internal.vm.Continuation.onPinned0(Continuation.java:393)
java.base/java.lang.VirtualThread.park(VirtualThread.java:596)
java.base/java.lang.System$2.parkVirtualThread(System.java:2648)
java.base/jdk.internal.misc.VirtualThreads.park(VirtualThreads.java:54)
java.base/java.util.concurrent.locks.LockSupport.park(LockSupport.java:369)
java.base/sun.nio.ch.Poller.poll(Poller.java:178) …
```
> Downgrade postgres driver back down to 42.7.3

- client/packages/core/__tests__/src/data/zeneca/attrs.json
- client/packages/core/__tests__/src/instaql.test.js
- client/packages/core/__tests__/src/store.test.js
- client/packages/core/src/schemaTypes.ts
- client/packages/core/src/store.js
- client/www/components/dash/explorer/EditNamespaceDialog.tsx
- client/www/components/ui.tsx
- client/www/lib/schema.tsx
- client/www/lib/types.ts
- client/www/pages/docs/modeling-data.md
- server/deps.edn
- server/src/instant/db/model/attr.clj
- server/src/instant/db/model/triple.clj
- server/src/instant/db/permissioned_transaction.clj
- server/src/instant/db/transaction.clj
- server/src/instant/jdbc/sql.clj
- server/src/instant/model/schema.clj
- server/src/instant/reactive/ephemeral.clj
- server/src/instant/system_catalog_migration.clj
- server/src/instant/util/coll.clj
- server/src/tool.clj
- server/test/instant/db/transaction_test.clj
> :on-delete :cascade

- server/src/instant/config.clj
Seeing better metrics with the fewer vfuture instances from https://github.com/instantdb/instant/pull/748
Leaving the flag for now in case something unexpected happens.
> Always use fewer-vfutures

- client/www/components/dash/explorer/EditNamespaceDialog.tsx
- Using the `forward attr name` in the description text
- Changed up the layout a bit, so "Cascade Delete" is on it's own line. 
> [sm] use forward attr in cascade delete dialog

- client/packages/core/src/Reactor.js
- server/src/instant/reactive/session.clj
- server/test/instant/reactive/session_test.clj
If we get a null query, we'll throw a noisy exception. This PR turns it into a normal error and notifies the client.
It seems like this can happen with `queryOnce`.
> Fix for null query

- client/www/components/dash/explorer/EditNamespaceDialog.tsx
Since we changed the dialog label to use the forward-attr-name, it became a bit more confusing: 
Does unlinking also cause cascade-delete?
To remove the confusion, reverting to use the namespace name instead:
@tonsky @dwwoelfel @nezaj
> [namespace-dialog] change the grammar for cascade-delete

- server/src/instant/nrepl.clj
Adds middleware to our nrepl to log activity so that we have an audit trail. 
Only turned on in production. Logs to honeycomb and to stdout.
> Add record middleware to nrepl

- server/src/instant/model/schema.clj
Makes sure that we don't treat changing the reverse link from nil -> nil as duplicating the reverse link.
Fixes a bug users are having doing schema push.
> Fix schema push

- client/www/_posts/pg_upgrade.md
Clarifies that the bottleneck is websocket connections, not pg connections 
> [essay] include a note on websockets

- server/test/instant/reactive/session_test.clj
More correct approach than #740
> Maintain order of operations in session tests

- client/www/_posts/pg_upgrade.md
A user asked: wouldn't 'stop the world' also take a few seconds? 
I wrote a minute because I imagined the stop the world approach to be more manual. If we automated it, the function would get very close to what we already wrote for zero downtime. I updated the essay to mention this. 
> [essay] be more explicit about stop the world

- server/src/instant/jdbc/wal.clj
Fixes bug creating the wal connection introduced in https://github.com/instantdb/instant/pull/772
The password wasn't getting url-encoded in the jdbc-url, which was causing the connection to fail. We don't need the password in the url since we set it in the properties, so we can just dissoc it from the spec before passing to `jdbc-url`.
> Fix wal connection

- client/www/_emails/html/welcome_feb_2025.html
- client/www/_emails/markdown/welcome_feb_2025.md
- client/www/_emails/txt/welcome_feb_2025.txt
- server/resources/migrations/49_add_user_flags.down.sql
- server/resources/migrations/49_add_user_flags.up.sql
- server/src/instant/core.clj
- server/src/instant/flags.clj
- server/src/instant/postmark.clj
- server/src/instant/scripts/welcome_email.clj
We sent a few emails to users yesterday to figure out the burst in signups and it was nice to get some feedback!
Figured we'd do well with sending some automated emails. We may want to tweak our strategy in the future but for now the idea is this:
Monday -> Friday we'll send out an email to users who signed up between 2 days ago and the previous day. This way we email people after they've tried us for at least 24 hours.
I also added a flag in our config app to turn this off and just the limit (right now set to 50) for the amount of emails we send
> [Emails] Send welcome email

- client/www/pages/intern/graphs.tsx
- server/.clj-kondo/.gitignore
- server/.clj-kondo/config.edn
- server/.clj-kondo/hooks/with_prod_conn.clj
- server/.gitignore
- server/src/instant/dash/routes.clj
- server/src/instant/intern/metrics.clj
- server/src/tool.clj
Previously, we needed to run a script to generate graphs. 
**Previous Steps** 
The previous steps used to be: 
```
1. Run `make dev-with-prod` to connect to prod data
2. Run `generate!` at the bottom generate metrics
3. Run `open resources/metrics/*-usage.png` in the terminal from the /server directory to view the metrics
```
**New Steps**
Now, **you no longer need to run `make dev-with-prod`**
To get the latest version, you can always load instantdb.com/intern/graphs 
If you want to customize the graph, you run instant locally and run the `save-pngs` comment
> [graphs] move graphs to a page

- server/src/instant/aurora_config.clj
- server/src/instant/config.clj
- server/src/instant/jdbc/aurora.clj
- server/src/instant/jdbc/wal.clj
Does two things:
1. Renames `username` to `user` so that it works properly with jdbc connection urls
2. Query-decodes password when we get it from the connection string. Then we set the password directly because `next-jdbc/jdbc-url` won't url-encode its params.
> Fix handling of database connection strings

- server/deps.edn
- server/src/instant/reactive/store.clj
transact! on store-conn takes suspiciously long time. One hypothesis is that it’s contention on lock. This metric will allow us to check it
> Monitor transact steps perf

- client/www/pages/pricing/index.tsx
A user mentioned that "Most Popular" didn't make sense, as obviously the Free tier was the most popular. 
Updated it to say "For teams"
> [pricing] most popular -> for teams

- client/www/pages/intern/investor_updates.tsx
- server/src/instant/core.clj
- server/src/instant/dash/routes.clj
- server/src/instant/intern/metrics.clj
Small changes as I get back into our dashboard work. 
I thought we should have a standalone page for investor updates. This way it's always easy to see MoM growth at the end of the month, paste it into our email, etc. 
1. Changed the route to be called investor_updates
2. Added MoM growth metrics at the top
> [investor-updates] graphs -> investor updates

- server/flags-config/instant.schema.ts
- server/src/instant/flags.clj
- server/src/instant/reactive/session.clj
- server/src/instant/session_counter.clj
- server/src/instant/util/async.clj
For unknown reason, just spinning up vfuture takes significant time on prod. Local dev machine:
Prod:
Times varies greatly, but it’s usually between 70 and 250 ms just to start a virtual thread!
Since spinning up real threads is faster (although more resource-intensive), we can try switching to agent thread pool & physical threads to try to improve latency
> Remove vfuture-pmap

- server/test/instant/reactive/session_test.clj
Let’s try to get this right. Using Github CI because it only reproduces itself on Github CI
> Maintain order of operations in session tests. Take 2 #760 #785

- server/src/instant/intern/metrics.clj
Added two kinds of calculations for our dashboard: 
`rolling-actives` reports how our `Monthly Active` stats change day-by-day. Here's how the function works: 
1. We generate a series of `analysis_dates` between `start-date` and `end-date` (inclusive) 
2. For each`analysis_date`, we calculate actives going back `window-days`. 
So if `window-days` is 30 days, each `analysis_date` reports monthly stats for a 30 day window, where the end is that date. 
The goal for this is to get a sense of how our MAU number is changing over time. 
```sql
WITH date_series AS (
SELECT
CAST(
GENERATE_SERIES(
DATE_TRUNC('day', CAST('2025-01-01' AS DATE)),
DATE_TRUNC('day', CAST('2025-01-30' AS DATE)),
INTERVAL '1 day'
) AS DATE
) AS analysis_date
),
excluded_emails (email) AS (
VALUES …
```
> [overview] rolling actives, month-to-date actives

- server/src/instant/core.clj
- server/src/instant/intern/metrics.clj
- server/src/instant/machine_summaries.clj
- server/src/instant/util/hazelcast.clj
For our `overview` field, I wanted to get a ~live view of how many connections we are supporting.  Ideally we'd have a table below that we can scroll through, to see all active apps. 
Since we have multiple machines, we can't just get this info in memory
We use Hazelcast's [ExecutorService](https://docs.hazelcast.com/imdg/4.2/computing/executor-service), run a `summarize` function across all machines, and return the result together. 
> [overview] machine summarizer

- server/src/instant/db/transaction.clj
I noticed after rebasing/merging deletes weren't being blocked in tx. Realized the shape of the tx-steps changes slightly so updated the code to correctly prevent updates and deletes.
> Prevent files deletes in tx

- server/test/instant/reactive/session_test.clj
Fixes the `join-room` test, where `refresh-presence` might get delivered before `join-room-ok`.
Example of a failing run here: https://github.com/instantdb/instant/actions/runs/13125160638/job/36619894359
> Fix another flaky test

- client/www/pages/dash/index.tsx
We got a few reports that clearing/deleting apps don't give feedback. Noticed it does take some time in prod so figured we can add a loading state to make it clearer to the user.
https://github.com/user-attachments/assets/232b8da3-9b45-4ab9-be10-ff7487e71ebc
> [Dash] Add feedback for clear and delete app

- client/www/components/ui.tsx
- client/www/pages/dash/index.tsx
- client/www/pages/intern/overview.tsx
- server/src/instant/dash/routes.clj
- server/src/instant/intern/metrics.clj
- server/src/instant/scripts/daily_metrics.clj
This adds an Overview Dashboard for us. 
(See screenshots in Team Discord) 
Some things we show: 
1. Rolling Actives
2. Month-To-Date Actives vs Target
3. Number of active connections (refreshed every minute)
4. Connections grouped by app
One bugfix for Month to Date Actives
1. Previously, the "real data" line would expand to the end of the month. Now we only show real data until the day we are looking.
> [overview] overview dashboard

- server/deps.edn
- server/src/instant/admin/routes.clj
- server/src/instant/dash/routes.clj
- server/src/instant/storage/s3.clj
- server/src/instant/util/s3.clj
Replaces amazonica with the aws-jdk 2 for s3 operations. Uses the aws crt client for uploads, which is supposed to have high throughput: https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/crt-based-s3-client.html
A couple of incidental changes:
1. I pass the `content-type` from the `req` to `upload-stream-to-s3` in dash. This gave me better content type when I was uploading from the dashboard.
2. I pass along the `content-length` field from the `req`, which allows us to use an optimized upload path when we know the content-length ahead of time.
> Use the s3 aws jdk 2

- server/deps.edn
- server/src/instant/util/aws.clj
Removes the last Amazonica dependency in favor of the aws java sdk 2.
> Remove amazonica

- client/www/components/dash/explorer/Explorer.tsx
When you first arrive on the Explorer, even for a new app, you'll land on the `$files` namespace and never see the NUX for creating your first namespace.
Now we'll default to the "create your first namespace" explainer on new apps, and the first user-namespace on apps that have created namespaces:
> Show the first user namespace instead of the system namespace

- client/www/components/dash/explorer/Explorer.tsx
- client/www/pages/_devtool/index.tsx
- client/www/pages/dash/index.tsx
dww pointed out that it's weird to see `$files` if you can't use them yet. We already pass an `isStorageEnabled` check to the frontend so figured for now we can just hide the namespace until we fully launch
> Hide  for non-enabled apps

- .git-blame-ignore-revs
Ignores the formatting changes in git blame:
https://docs.github.com/en/repositories/working-with-files/using-files/viewing-and-understanding-files#ignore-commits-in-the-blame-view
> Ignore the prettier changes in git blame

- client/packages/core/src/instaql.js
- server/src/instant/db/datalog.clj
- server/src/instant/db/instaql.clj
This is a prerequisite for supporting links in the Add/Edit row dialog in the Explorer.
This gives us a way to let the user search for the id that they want to link.
A better solution would be to support `$startsWith` on uuid fields, but I didn't want to get into adding support for uuid indexes just yet.
Query looks like this:
```clojure
{:posts {:$ {:where {:$entityIdStartsWith "f20"}}}}
```
> $entityIdStartsWith

- client/pnpm-lock.yaml
- client/www/components/dash/PersonalAccessTokensScreen.tsx
- client/www/components/dash/auth/Apple.tsx
- client/www/components/dash/auth/Clerk.tsx
- client/www/components/dash/auth/Google.tsx
- client/www/components/dash/auth/Origins.tsx
- client/www/components/dash/explorer/EditNamespaceDialog.tsx
- client/www/components/dash/explorer/EditRowDialog.tsx
- client/www/components/dash/explorer/Explorer.tsx
- client/www/components/dash/explorer/QueryInspector.tsx
- client/www/components/docs/Fence.jsx
- client/www/components/docs/MobileNavigation.jsx
- client/www/components/marketingUi.tsx
- client/www/components/ui.tsx
- client/www/lib/toast.js
- client/www/package.json
- client/www/pages/_devtool/index.tsx
- client/www/pages/dash/index.tsx
- client/www/pages/index.tsx
Updates heroicons from v1 to v2. Main motivation is that v2 has an "undo" icon and v1 doesn't.
Icons mostly seem the same, maybe a little dimmer?
Preview URL: https://instant-www-js-icons-v2-jsv.vercel.app
Old:
New:
Old:
New:
> Upgrade heroicons to v2

- server/deps.edn
- server/src/instant/intern/metrics.clj
Before:
```
[~/ws/instant/server] make dev
Booting up backend w/ local db...
WARNING: abs already refers to: #'clojure.core/abs in namespace: clojure.core.matrix.impl.mathsops, being replaced by: #'clojure.core.matrix.impl.mathsops/abs
Warning: protocol #'clojure.core.matrix.protocols/PMathsFunctions is overwriting function abs
WARNING: abs already refers to: #'clojure.core/abs in namespace: clojure.core.matrix.protocols, being replaced by: #'clojure.core.matrix.protocols/abs
WARNING: abs already refers to: #'clojure.core/abs in namespace: clojure.core.matrix, being replaced by: #'clojure.core.matrix/abs
WARNING: abs already refers to: #'clojure.core/abs in namespace: clojure.core.matrix.dataset, being replaced by: #'clojure.core.matrix/abs
WARNING: abs already refers to: …
```
> Reduce amount of warnings printed on startup

- client/www/pages/docs/index.md
We used to use the 'bare' nextjs template. The downside for this, was that there was no tailwind. In order to make copy pasting as easy possible, we added inline styles. 
However, inline styles can be problematic because: 
1. Most people use tailwind, so if they wanted to repurpose things they couldn't
2. Most LLMs are better at tailwind. Having inline styles confuses them and gets them creating more inline styles. 
Recently nextjs has fixed their light mode bug. This means we can use their basic starter. I went ahead and updated our example so: 
1. We use nextjs' normal template, with tailwind. (I added a `--yes` flag so there are no questions when user pastes create-next-app command) 
2. I changed the typescript we used for `onSubmit` (this was causing errors when pasting)
3. I updated …
> [docs] use tailwind in our react example

- client/packages/core/src/devtool.ts
- client/packages/core/src/utils/flags.ts
- client/packages/core/src/utils/log.ts
- client/www/pages/_devtool/index.tsx
A few improvements to devtool: 
1. I added a localStorage flag, so when these are on on, we default devtools to open our local dashboard
2. I added an `X` button in the devtools pane. people may not know that you can escape with an `esc` key, so wanted to add the button to be explicit 
> [devtool] Improve devtool local flow, and add an `X` button 

- server/src/instant/reactive/session.clj
Unless I am missing something, `receive-q-delay-ms` and `worker-delay-ms` are no longer collected, while `total-delay-ms` is
> Restore total-delay-ms metric

- server/src/instant/flags_impl.clj
- server/src/instant/machine_summaries.clj
- server/src/instant/reactive/ephemeral.clj
- server/src/instant/reactive/invalidator.clj
- server/src/instant/reactive/query.clj
- server/src/instant/reactive/session.clj
- server/src/instant/reactive/store.clj
- server/src/instant/runtime/routes.clj
- server/src/instant/session_counter.clj
- server/test/instant/reactive/session_test.clj
- server/test/instant/reactive/store_test.clj
Design:
- `rs/store-conn` becomes a record w/ 2 fields
- `:sessions` is a datascript conn that stores session info. Shouldn’t have too high concurrent access as it’s only modified on connect/disconnect
- `:conns` is a `ConcurrentHashMap` of `app-id` → datascript conn that store instaql queries, datalog queries, tx-meta and subscriptions.
- All `instant.reactive.store` methods accept opaque `store` argument instead of explicit `conn`/`db`
This way we solve:
- Opening ws conn without app-id is okay, as it only goes into `:sessions` db and stays there
- When we modify any other data in datascript, we _must_ have app-id, so we can always find correct conn in `:conns`
- Current schema design doesn’t use datascript ref to sessions, it uses `.../session-id` (uuid) instead. That makes splitting …
> Split rs/store-conn by app

- server/test/instant/db/instaql_test.clj
Our `pagination` test has been flaky for a while. join-rows tend come back in some slightly different order, and cause issues. 
I think the long term fix is it improve our `query-pretty` function. However for now, just changing this test to be a bit more specific about what we test. 
> simplify pagination test

- client/www/pages/docs/instaml.md
Hello, this is a fix in the `Writing data` docs where `id` fn was omitted from import. It is important as it took me 10 minutes to find out where this was imported from. Initially, I thought `id` was something that just works inside `transact` as some kind of remarkable js macro.
Current docs: 
Hope this helps 👍
> Add `id` import in `Writing data` docs

- server/src/instant/stripe.clj
We got an email about a webhook failing when we manually deleted the subscription for an app that no longer exists.
Longer term fix for this would be to introduce a trigger + sweeper on app deletes for subscribed users
> [Stripe] sm stripe fix

- client/www/components/dash/Auth.tsx
- client/www/pages/_devtool/index.tsx
Made the following changes: 
1. Added a window around error states, so the user always sees a `Close` button 
2. Made sure we had a sign out button in every state (error, signed in, etc)
3. Made some of the error messages more descriptive.
> [devtool] add sign out buttons, and more descriptive errors

- client/www/pages/docs/init.md
We got feedback that it wasn't clear if users had to create a singleton model or if the Instant library already handled this and a user could init the db wherever they needed it.
Add a section to the init docs to clear this up
> [Docs] Flexibile initialization

- client/www/pages/docs/instaql.md
We got a question in [discord](https://discord.com/channels/1031957483243188235/1338329481961803837) about how to pause/disable queries. We don't support pausing but we do support deferring and just haven't added that into the docs.
> [Docs] Defer query docs

- client/packages/core/__tests__/src/instaql.test.js
- client/packages/core/src/instaql.js
Previously, if you wrote a query like: 
```
{
"posts": {
"$": {
"where": {
"slug": {
"$like": "%2)"
}
}
}
}
}
```
You would get an error: 
```
SyntaxError: Invalid regular expression: /^.*2)$/: Unmatched ')'
Source
new RegExp
<anonymous> (0:0)
../packages/core/dist/module/instaql.js (79:1) @ makeLikeMatcher
77 |     }
78 |     const regexPattern = pattern.replace(/%/g, '.*').replace(/_/g, '.');
> 79 |     const regex = new RegExp(^${regexPattern}$, caseSensitive ? undefined : 'i');
| ^
```
This is because we did not escape special regex chars when creating our like matcher. I updated it so we do. 
> [like] handle regex chars

- server/src/instant/model/app_file.clj
Noticed a bug with `app-file/create!` where we were returning the lookup instead of the entity id.
> Return entity_id instead of lookup

- client/packages/core/src/instaql.js
- server/src/instant/db/instaql.clj
Consider a setup like so: 
todo { name todo1 } links to blocks {name child1}  and blocks { name child2 } 
The following query would fail to return any rows: 
```json
{
"todos": {
"$": {
"where": {
"and": [
{
"blocks.name": "child1"
},
{
"blocks.name": "child2"
}
]
}
}
}
}
```
This is because when we generated the datalog, the variable `?blocks-1` was re-used across and conditions: 
```edn
{:children
{:pattern-groups
[{:patterns
[{:and
[{:and
[[{:idx-key :ave, :data-type :string}
?blocks-1
#uuid "36410869-50da-442a-86cd-5e75e0143254"
"child1"]
[:eav
?blocks-1
#uuid "59b5b318-d71b-47e2-abb5-107004b5ee82"
?blocks-0]]}
{:and
[[{:idx-key :ave, :data-type :string}
?blocks-1
#uuid "36410869-50da-442a-86cd-5e75e0143254"
"child2"]
[:vae
?blocks-1
#uuid "59b5b318-d71b-47e2-abb5-107004b5ee82" …
```
> [self-links] Fix and clauses for self links

- server/src/instant/db/instaql.clj
Technically both seem to work, but feels safer to use level-sym
> Use level-sym instead of default-level-sym

- server/src/instant/db/instaql.clj
- server/test/instant/db/instaql_test.clj
A user as confused by our `type-checked` error message. It looks like he assumed `type-checked` was different from `typed`. 
I thought might be nicer to have the error message say `typed`. 
https://discord.com/channels/1031957483243188235/1338513223795605564
> type-checked -> typed in error message

- server/resources/migrations/53_change_indexing_of_triple_nulls.down.sql
- server/resources/migrations/53_change_indexing_of_triple_nulls.up.sql
- server/src/instant/db/datalog.clj
- server/src/instant/db/model/triple.clj
- server/src/instant/util/exception.clj
- server/test/instant/db/instaql_test.clj
Part 1 of fast paginated queries across many entities.
Also fixes a bug reported at https://discord.com/channels/1031957483243188235/1304944961380286515
After this change, users will be able to store multiple entities that have null as the value for a unique attribute.
As part of making pagination queries faster, we need all the null values to already be in the index. We'll have to auto-populate the null values ourselves if they're undefined. We don't want to break users' `unique` indexes by inserting nulls, so we treat jsonb nulls like postgres null and postgres automatically treats them as distinct values.
We do this by converting `'null'::jsonb` into a postgres `NULL` in an index expression. That way postgres treats the null just like postgres nulls in the index.
Other alternatives we …
> Treat json nulls as postgres nulls in the unique index

- server/src/instant/reactive/invalidator.clj
If there's no conn in the store for the given app, we'll get a `Cannot invoke "java.util.concurrent.Future.get()" because "fut" is null` error.
> Fix store snapshot when no store for app

- client/www/pages/docs/auth/apple.md
User noted this from the docs -- frontend doesn't require the email key.
> [sm] remove user.email in signOut

- client/packages/core/src/coreTypes.ts
- client/packages/core/src/devtool.ts
- client/packages/core/src/index.ts
- client/www/pages/_devtool/index.tsx
1. Set the toggler to a high z-index, so it still shows up if the user writes some code that uses absolute positons
2. Set the default to be bottom-right (nextjs also has a button that shows up on the bottom left
3. Added a little (* localhost) flag in our iframe. This is mainly for us, as it's hard to quickly know when loading the iframe, if we are loading localhost:3000 dash or instantdb.com/dash
I am going to follow up with a docs page. I realize we don't have docs for devtool 
> [devtool] let folks set positions, and set z-index

- client/packages/cli/src/index.js
A user reported that they would get 'no changes' whenever they ran schema push.
It's because they did not export the `schema`. Right now adding a detection for it, and erroring out: 
We may want to be more forgiving in the future (for example by detecting if the export includes a { schema } 
> [cli] make sure to check that the default export is a schema export

- server/src/instant/db/datalog.clj
Not the greatest fix, but this should fix the slow queries people are reporting.
The issue is that we generate a join clause that looks like this:
```
match_0_1 AS MATERIALIZED (
SELECT
match_0_0.*,
...
FROM
triples,
match_0_0
WHERE
app_id = 'app-id'
AND (av = true)
AND (attr_id = 'attr-id')
-- join clause to parent here
AND (value = TO_JSONB(match_0_0_entity_id))
)
````
That won't use the av_index without nulls, because it has json_null_to_null(value) stored in the index.
When we generate the join clause, we don't know that it's an av index, so we don't know to wrap in `json_null_to_null`. As a hack, this pr maps through the extra join clauses and wraps `:value` in `[:json_null_to_null :value]` when it knows that it's using the :av index.
> Fix join queries not using the av-index

- client/packages/core/src/coreTypes.ts
- client/packages/core/src/devtool.ts
- client/packages/core/src/index.ts
- client/www/pages/docs/devtool.md
This adds an `allowedHosts` config key. It can be useful if a user has a custom scheme for loading dev pages -- i.e `site.local`, etc 
> [devtool]  allowedHosts

- server/src/instant/reactive/store.clj
- server/src/instant/util/coll.clj
- server/test/instant/reactive/store_test.clj
Our comparators relied on `<`-like operators and those only work on numbers in Clojure.
Created a set of custom functions for comparing each type we support (bool, string, number, and date).
Also fixes how we handle `nil`, which will become more relevant when I merge in https://github.com/instantdb/instant/pull/869
> Fix match topic for comparators with non-numbers

- server/src/instant/db/cel.clj
According to profile, we spend a lot of time in ->cel-map, specifically walking data structures and rebuilding them to stringify keys and values. This patch changes it so that we coerce to string at retrieval time, which should be faster
I am only not sure about CelMap::entrySet. It doesn’t show up in tests, but could it be used somewhere nevertheless?
> optimize ->cel-map

- server/Makefile
- server/dev-resources/hooks/pre-commit
- server/src/tasks.clj
To install:
```
make bootstrap-oss
```
Looks like this:
```
[~/ws/instant/server] git commit -am "abc"
server/src/instant/db/cel.clj:6:5: warning: namespace clojure.java.io is required but never used
server/src/tasks.clj:82:41: warning: unused binding e
linting took 63ms, errors: 0, warnings: 2
Error: new clj-kondo errors found. Please fix them, make sure 'make lint' runs without warnings and then commit.
[~/ws/instant/server]
[~/ws/instant/server] git commit -am "abc"
server/src/instant/db/cel.clj:6:5: warning: namespace clojure.java.io is required but never used
linting took 32ms, errors: 0, warnings: 1
Error: new clj-kondo errors found. Please fix them, make sure 'make lint' runs without warnings and then commit.
[~/ws/instant/server] git commit -am "abc"
linting took 14ms, errors: 0, …
```
> pre-commit hook that checks linting

- client/www/components/docs/Layout.jsx
I realized our table of contents wasn't staying sticky. This is because of the `overflow-x-auto` I added to the top element. 
I jigged and jigged, but eventually opted to just use position:fixed. I don't think we really need position:sticky for the table of contents, as it's not something we are 'scrolling' too really.  
> [docs] keep the table of contents fixed

- client/packages/cli/src/index.js
Ah, the search was looking for `instant.rules`, rather than `instant.perms`. Introduced this bug in `0.17.16` onwards
> [bugfix] instant.rules -> instant.perms

- server/test/instant/db/indexing_jobs_test.clj
Seeing some flaky tests where we timeout while the test is still going because simple sql queries take forever (e.g. an update by id will take 200ms). I suspect there's some issue with the test machine that makes it slow, so increasing the timeout. 
If it keeps happening, I'll look into a better way to check that progress is being made.
> Increase timeout during indexing-job tests

- client/www/components/docs/Layout.jsx
- client/www/components/docs/Navigation.jsx
- Added bottom padding for sidebar
- Reducing the spacing between sidebar sections. This way in at least a 15 inch macbook with bookmarks enabled, there is no need to scroll the sidebar
> [docs] small scroll improvements

- server/src/instant/db/datalog.clj
Postgres is using the created_at index for fetching attributes for an entity and it's making some queries very slow. Using an OR instead of IN seems to make it use the ea index instead.
> Use multiple `or`s instead of `in` for filtering attr ids

- server/src/instant/admin/routes.clj
Clark gave `uploadFile` from the admin SDK a whirl and noticed we weren't parsing content-type correctly. I remember previously I keywordized the params but then got rid of that. Needed to also update the parsing.
Doing that here!
> Parse content-type and content-disposition in admin sdk

- client/www/pages/docs/modeling-data.md
Since `queries` and `transactions` both linked to the same place I figured this was a typo.
> Update transactions link in modeling-data.md

- server/src/instant/db/model/attr.clj
- server/src/instant/model/schema.clj
Previously when we pulled from the CLI we'd get things like
```
$files: i.entity({
"content-disposition": i.string().indexed(),
"content-type": i.string().indexed(),
"key-version": i.number(),
"location-id": i.string().unique().indexed(),
path: i.string().unique().indexed(),
size: i.number().indexed(),
})
```
But things like `key-version` and `location-id` aren't relevant to users. For most folks`content-type`, `content-disposition` and `size` won't be used either.
With this change pulling from the CLI will return
```
$files: i.entity({
path: i.string().unique().indexed(),
url: i.string(),
})
```
If a user does want to leverage fields like `content-type` in their app they can add these fields into `instant.schema.ts` and when they use `instant-cli push` the `plan!` step will ignore the …
> Hide system files attrs from CLI

- client/www/components/dash/Perms.tsx
- client/www/components/ui.tsx
When we had an error, we would show an error pane. But our Monaco editor would not resize. I fixed this by adding a few `min-h-0`s.
I also updated our Loading state, so it's a bit less jarring. It used to flash "Loading...". Now it's white background, and does a pulse animation. In most cases users won't see the pulse.
> [monaco] improve height resize, loading state

- client/sandbox/react-nextjs/pages/play/avatar.tsx
- client/sandbox/react-nextjs/pages/play/storage-v2.tsx
- client/www/data/docsNavigation.js
- client/www/pages/docs/auth/magic-codes.md
- client/www/pages/docs/index.md
- client/www/pages/docs/storage.md
[Preview Link](https://instant-www-js-storage-docs-jsv.vercel.app/docs/storage)
> New Storage docs

- server/src/instant/core.clj
We got a report that json uploads were blocked and indeed it was because of our middleware which would parse the upload as json instead of an input stream.
This PR updates our middleware to conditionally `wrap-json-body`
> [Storage] Enable json uploads

- server/src/instant/data/bootstrap.clj
- server/test/instant/db/instaql_test.clj
- server/test/instant/db/transaction_test.clj
- server/test/instant/reactive/invalidator_test.clj
Zeneca in the tests does a weird thing where it makes ids into refs. No other app behaves like this and it's causing problems for the select-keys PR https://github.com/instantdb/instant/pull/831
This updates the zeneca fixtures to create ids like a normal app and fixes all of the tests.
> Make zeneca normal

- client/www/pages/docs/instaml.md
Got feedback that it wasn't clear that transacts are atomic. I realized we don't mention this in the docs and thought it would be nice to be more explicit.
> [Docs] Be explicit that transact is atomic

- client/www/pages/docs/patterns.md
I noticed on the patterns page we'd get an error related to the bottom example
```
client.ts:59 Warning: Expected server HTML to contain a matching text node for "
" in <pre>. Error Component Stack
at pre (<anonymous>)
at div (<anonymous>)
at Highlight (index.js:191:1)
at Fence (Fence.jsx:8:25)
at MarkdocComponent (patterns.md:93:25)
at div (<anonymous>)
at Prose (Prose.jsx:3:29)
at article (<anonymous>)
at PageContent (Layout.jsx:148:24)
at main (<anonymous>)
at div (<anonymous>)
at div (<anonymous>)
at div (<anonymous>)
at Layout (Layout.jsx:264:26)
at DocsPage (DocsPage.jsx:54:28)
at ErrorBoundary (ErrorBoundary.tsx:10:5)
at App (_app.tsx:26:16)
at PathnameContextProviderAdapter (adapters.tsx:70:3)
at ErrorBoundary (ErrorBoundary.tsx:11:8)
at ReactDevOverlay (ReactDevOverlay.tsx:32:3) …
```
> [Docs] sm hydration fix

- server/src/instant/db/cel.clj
- server/test/instant/db/cel_test.clj
We've been getting error reports when folks do things like `!data.isFavorite`
Turns out we weren't parsing `false` values correctly and they would get coerced into null values. And doing a logical not on null throws an error.
Now we check whether our cel-map contains the key and if it does we extract the value from the map. Adding in a test too to verify this behavior
> [CEL] Parse false values correctly

- server/src/instant/db/datalog.clj
Pushing up a quick fix for a user to unblock them for now. Seems like turning off materialize results in a 10x slow-down. For now just enabling it for their apps
> [Temp] Hotfix for user apps

- server/src/instant/db/datalog.clj
- server/test/instant/db/instaql_test.clj
Looked for patterns we could use to determine when to use `not-materialized` and when to use `materialized`, but couldn't come up with anything definitive.
With this PR, we'll only use `not materialized` when we need it for ordering.
> Only use `not materialized` when we need it in an ordered query

- server/src/instant/db/datalog.clj
We know we'll include the final pagination CTE in the json_build_object result from datalog, so we can materialize it ahead of time.
> Materialize the pagination cte that we include in the result

- server/scripts/export.sh
- server/scripts/export/copy_apps.sql
- server/scripts/export/copy_attrs.sql
- server/scripts/export/copy_idents.sql
- server/scripts/export/copy_rules.sql
- server/scripts/export/copy_triples.sql
Adds a cli script to import an app locally,
Usage is like:
```
scripts/export.sh --email 'dwwoelfel@gmail.com' --app-id 1c0a9039-c387-4315-8471-58979bef93bf
```
Still not super fast, but faster than export.clj and uses a lot less cpu/memory.
> Add a cli export script

- server/src/instant/db/datalog.clj
- server/src/instant/db/instaql.clj
- server/test/instant/db/instaql_test.clj
When we're joining to a previous CTE in the or gather, we can use a left join instead of a full join, which reduces the number of rows that postgres has to filter.
There are a couple of other small improvements:
1. We check if offset is 0 instead of just if it's nil to allow us to skip the has-prev query
2. We materialize any CTE that shows up in the `json_build_object`. This prevents postgres from running some queries twice.
3. If we see multiple ors on the same field, we'll combine them into an in `{:or [{field: value}, {field: value}]}` -> `{:or [{field: {in: [value, value]}]}`. This had huge improvement for one of the queries in production.
For the backtesting, I did a distinct by query_hash, only compared queries whose sql query changed, and got the time from `explain` instead of …
> Use a left-join for ors when possible

- server/flags-config/instant.schema.ts
- server/src/instant/db/datalog.clj
- server/src/instant/flags.clj
- server/src/instant/jdbc/sql.clj
Occasionally we have a query that's slow, but we could fix it with a postgres setting `set enable_nestloop = off`.
This adds a facility where we can set those config settings for individual queries by their query hash.
To set it, you just have to add a new row in `instant-config` with the query_hash, the setting, and the value.
There's no validation on the config to ensure they're valid settings. We complain loudly if the db throws when we apply the setting, but we won't break the query.
Inspired by a query that takes 8 seconds with a nested loop, but takes 80ms with `set enablenestloop = off`.
> Add flags to set query settings for slow queries

- client/packages/cli/src/index.js
- server/src/instant/system_catalog.clj
I noticed we would write: 
'We inferred 1 attribute' 
This was because $files.url was not typed. 
This PR: 
1. Adds the checked data type to the system_catalog.clj file
2. Makes sure we ignore system catalog attrs in cli inference
@nezaj @tonsky @dwwoelfel 
Once landed, I will run the following sql on prod, to update the files system catalog to have a checked data type :
```sql
UPDATE attrs 
SET checked_data_type = 'string'
WHERE attrs.id = '96653230-13ff-ffff-2a35-48afffffffff'::uuid;
UPDATE triples
SET checked_data_type = 'string'
WHERE triples.attr_id = '96653230-13ff-ffff-2a35-48afffffffff'::uuid;
```
> [cli] do not infer system catalog attrs, add checked data types to system catalog attrs

- server/deps.edn
- server/src/instant/data/bootstrap.clj
- server/src/instant/db/model/triple.clj
- server/test/instant/db/instaql_test.clj
Follow-up to https://github.com/instantdb/instant/pull/925
A lot of the instaql tests rely on the zeneca app that we insert during oss bootstrap. This PR uses `with-zeneca-app` for all of them.
Also includes a helpful `(update-snapshot #'my-test-var)`, which will replace `()` in `(is-pretty-eq? expected '())` with whatever `expected` returns. Very useful when you're writing new tests or updating existing tests. It acts kind of like snapshot testing. The idea was inspired by @tonsky's https://tonsky.me/blog/clojure-macros/
> Don't rely on existing data in the db for instaql tests

- server/src/instant/db/instaql.clj
The `or` batching from https://github.com/instantdb/instant/pull/944 broke it
> Fix $entityIdStartsWith

- server/test/instant/admin/routes_test.clj
- server/test/instant/db/datalog_test.clj
- server/test/instant/reactive/session_test.clj
Follow up to https://github.com/instantdb/instant/pull/952, removes the remaining dependencies on the apps in the db.
Much easier to review when ignoring whitespace (https://github.com/instantdb/instant/pull/955/files?w=1)
> Remove the rest of the dependencies on apps in the database for tests

- client/packages/cli/src/index.js
When I was playing with instantgram, found myself put off by the amount of comments we print out when we generate the code. 
I thought it would be a bit cleaner to just have a `// Docs: ` link at the top, similar to what we do in instant.perms.ts 
Here's how the current output looks for a fresh app:
> [cli] simplify schema comments

- client/packages/cli/src/index.js
I realize we didn't annotate when a user added onDelete cascade rules. 
Now we do: 
Note: this has the same issue that prod currently has, where if a user links to the same etype, the onDelete rule will look ambiguous. Going to tackle that in a separate PR 
@tonsky @dwwoelfel @nezaj
> [cli] add onDelete: cascade annoation

- server/src/instant/db/datalog.clj
We use a "join CTE" to connect separate datalog queries into a single postgres query.
For a instaql query like `{:users {:$ {where {:name "daniel"}}}`, we'll generate two datalog queries:
```clojure
;; Query to get the user ids
[[:ea ?e ?eid-attr ?e]
[:av ?e ?name-attr "daniel"]]
;; Query to get the attrs
[[:ea ?e]]
```
The CTEs look something like:
```sql
--[:ea ?e ?eid-attr ?e]
with match_0 as (
select * from triples where attr_id = :eid-attr:
),
-- [:av ?e ?name-attr "daniel"]
match_1 as (
select * from triples join match_0 on entity_id = match_0.entity_id where attr_id = :name-attr: and value = 'daniel'
),
-- get all of the entity_ids
match_2 as (
select distinct entity_id from triples join match_1 on entity_id = match_1.entity_id
),
-- now we can get all of the attrs for the entity …
```
> Faster join CTE

- server/scripts/export.sh
- server/src/instant/db/instaql.clj
- server/src/instant/db/model/attr.clj
- server/src/instant/db/model/entity.clj
- server/test/instant/db/instaql_test.clj
Fixes a bug introduced in https://github.com/instantdb/instant/pull/958
We were still using the all-attrs query to fetch entity maps, so the permission checks weren't getting data from the datalog cache. This causes permission checks to do a ton of additional fetching and can cause queries to time out.
> Use blob ids for entity maps

- .github/workflows/js.yml
- client/www/pages/docs/instaql.md
Adds docs for the new `fields` param to limit the fields in the result.
Direct link to preview https://instant-www-js-fields-docs-jsv.vercel.app/docs/instaql#limiting-fields
> Docs for `fields` param

- client/www/components/dash/explorer/EditRowDialog.tsx
- client/www/lib/hooks/explorer.tsx
Updates the explorer to fetch ids instead of the full object for fetching links.
I had to update the link editor to fetch the object by its id when you click on the info icon to see the full object. 
Also fixes a bug where the search input for editing links wouldn't show up if the modal content overflowed.
> Only fetch ids for nested fields in explorer

- server/src/instant/storage/s3.clj
- server/src/instant/util/aws_signature.clj
- server/src/instant/util/date.clj
- server/src/instant/util/s3.clj
- server/test/instant/storage/s3_test.clj
AWS URLs depend on the signing-instant.  
We want to keep URLs stable: repeated calls to the same object should return 
the same URL, so that browsers can cache the object. 
To do this, we bucket dates to the start of the day. 
This gives about 24 hours where URLs are stable
> [aws] stable presign urls

- client/packages/core/src/queryTypes.ts
- client/sandbox/react-nextjs/pages/play/checkins.tsx
- client/sandbox/react-nextjs/pages/play/fields.tsx
Updates the return type to pick from the fields param (if the fields param is provided):
> Fix the return type of query data when using fields

- server/src/instant/auth/oauth.clj
- server/src/instant/runtime/routes.clj
We got an ask for passing through the `hd` param on Google Auth. [[Discord]](https://discord.com/channels/1031957483243188235/1346360958309761125) Thought this could be a nice win!
This enables us to do things like
```
const [request, _response, promptAsync] = useAuthRequest(
{
clientId: 'instant-awedience',
redirectUri: makeRedirectUri(),
extraParams: {
hd: 'tufts.edu',
},
},
discovery,
);
```
To hook into SSO for domains integrated with google
https://github.com/user-attachments/assets/87d1ef3a-a61e-4b8f-8809-13d1d5fd7d53
> [OAuth] Enable passing hd param

- client/packages/core/__tests__/src/instaql.test.js
- client/packages/core/__tests__/src/utils/object.test.js
- client/packages/core/src/Reactor.js
- client/packages/core/src/utils/object.js
- client/sandbox/react-nextjs/pages/play/ephemeral-counts.tsx
**Bug** 
If a user published:
```
publishPresence({ item: { n: 1 } })
publishPresence({ item: { n: 2 } })
```
The `patch-presence` for `n: 2` would not get propagated to `subscribePresence`. 
**Root cause** 
We received a `patch-presence` command. We would run: 
```
sessions = assocIn(sessions, path, value);
```
The path would look something like `['item', 'n']`
This would mutate the original `item`. 
Then, when `hasPresenceResponseChanged` would run, we would see that in fact nothing had changed, and skip the update. 
**This only happened when the user had a deeply nested presence.** 
**Fix** 
1. Updated it so that `assocIn` and `dissocIn` are explicit about being mutative
2. Then, used `mutative` to generate new `session` objects.
--- 
> [presence] ensure we don't mutate `this._presence`

- client/packages/core/__tests__/src/utils/object.test.js
- client/packages/core/src/Reactor.js
- client/packages/core/src/utils/object.js
- client/sandbox/react-nextjs/pages/play/presence-arrays.tsx
- server/.clj-kondo/imports/babashka/sci/config.edn
- server/.clj-kondo/imports/babashka/sci/sci/core.clj
Consider a presence state that uses arrays: 
```
{ selectedIds: []
```
We had two bugs:
**1. `+` operations**
If machine1 sent: 
```
// Machine1
set-persence ['sticker-5']
set-persence ['sticker-4', 'sticker-5']
```
machine2 would receive: 
```
// Machine2
patch-presence  [peerId, 'data', 'selectedIds'], 'r', ['sticker-5']
patch-presence  [peerId, 'data', 'selectedIds', 0], '+', 'sticker-4' // Uh oh
```
In the case where we had a `+`, we actually want to _insert_ at index 0, but instead we replaced it: 
```
// Desired: ['sticker-4', 'sticker-5']
// Got ['sticker-5']
```
Fixed this by created an `insertInMutative` function, which splices at index N rather than replace
**1. `-` operations**
Now imagine if `machine-1` sent: 
```
set-persence ['sticker-5']
set-persence ['sticker-4', …
```
> [presence] handle arrays when doing `+` and `-` patches

- client/www/components/dash/explorer/EditRowDialog.tsx
- client/www/components/dash/explorer/Explorer.tsx
A user pointed out that you couldn't set json values as `null` I thought this would be straightforward fix but it was a bit more involved. This does the following:
* Introduce a checkbox for setting a value to null
* Restricts fields types when attr is type checked
* Upgrade reset functionality to restore previous values even if you changed the input type
https://github.com/user-attachments/assets/eb45111d-0f8f-422d-a7d7-f00de9090544
> [Explorer] Enable setting null

- client/packages/core/__tests__/src/instaql.test.js
- server/src/instant/db/datalog.clj
- server/src/instant/db/instaql.clj
- server/test/instant/db/instaql_test.clj
Ran into this bug while working on cel -> instaql, where we can generate lots of nested ORs.
Three fixes in this PR:
1. If there's a single AND or OR, then we just strip it out (`[{:or [{handle: 'dww'}]}]` is the same as `{handle: 'dww'}`)
2. Collapse the ors properly, so that `[{:or [{:or [cond-a, cond-b]}, cond-c]]}]` generates `{:or [cond-a, cond-b, cond-c]}` instead of `{:or [[cond-a, cond-b], cond-c]}`.
3. Fix in datalog.clj to handle ORs in the destination path. I simplified the logic to only do recursion for generating the join conds in one place.
There is still a remaining issue where we could potentially include the same cte twice, leading to postgres complaints about ambiguous columns. I can't reproduce it without disabling the `or` collapsing, so I'm ignoring it for now. I …
> Fix lots of nested ands and ors

- client/www/pages/docs/instaql.md
Small adjustment to the schema section to
1) better match the examples in the docs (we show goals -> todos at the top and todos -> goals in the reverse direction), 
2) better match the screenshot
> [Docs] Update instaql.md

- client/www/pages/docs/cli.md
* Fix typos
* Change `npx instant-cli` to `npx instant-cli@latest` like in the other cli commands on this page
> docs(cli): fix typos

- client/packages/core/src/queryTypes.ts
- client/sandbox/strong-init-vite/src/typescript_branded.tsx
**Context** 
If you use branded types like so: 
```
type BusinessEmail = string & { readonly __brand: unique symbol };
const schema = i.schema({
entities: {
leads: i.entity({
email: i.string<BusinessEmail>(),
}),
},
});
const db = init({
appId: 'my-app-id',
schema,
});
const r = db.useQuery({
leads: {},
});
const x = r.data?.leads[0];
```
`InstaQLEntity` would expanded the branded type: it would like so:
{
id: string;
email: {
readonly [x: number]: string;
toString: () => string;
charAt: (pos: number) => string;
charCodeAt: (index: number) => number;
concat: (...strings: string[]) => string;
indexOf: (searchString: string, position?: number) => number;
... 43 more ...;
readonly __brand: unique symbol;
};
} | undefined
I made sure that we don't expand primitives. This short circuits and …
> [client] support branded types

- client/packages/core/src/index.ts
The devtool uses the Browser Object Model API, which is not available in react-native. This change tests for the existance of `document` in the global namespace chain and aborts devtool creation if it does not exist.
This allows usage in react native without explicitly passing `devtool: false` to `init`.
> [client] Disable devtool in non-DOM contexts (React Native)

- client/www/pages/dash/index.tsx
- server/flags-config/instant.schema.ts
- server/resources/migrations/57_apps_deletion.down.sql
- server/resources/migrations/57_apps_deletion.up.sql
- server/src/instant/app_deletion_sweeper.clj
- server/src/instant/core.clj
- server/src/instant/dash/routes.clj
- server/src/instant/fixtures.clj
- server/src/instant/flags.clj
- server/src/instant/model/app.clj
- server/src/instant/superadmin/routes.clj
- server/test/instant/admin/routes_test.clj
- server/test/instant/db/instaql_test.clj
- server/test/instant/db/transaction_test.clj
A user had a really large app, and our "delete" button was starting to time out. 
Changed our system to schedule apps for deletion. The way it works: 
1. Added an `deletion_marked_at` flag on apps 
2. When a user deletes an app, we only mark this flag
3. A worker runs every day. we pick up the app and run the operation in the background, with a 5 minute timeout 
4. You can disable this using the `app-deletion-sweeper` flag in instant-flags 
Deploy plan:
1. push instant-config
2. push migration
3. deploy
> [apps] mark for deletion

- client/www/pages/docs/modeling-data.md
Small PR to suggest folks import from `react` rather than `core` for typesafety
> Update import from core to react

- server/src/instant/reactive/session.clj
- server/src/instant/storage/coordinator.clj
- server/src/instant/storage/routes.clj
- server/src/instant/util/s3.clj
We were getting some errors with our async s3 crt client: 
> The service request was not made within 10 seconds of doBlockingWrite being invoked. Make sure to invoke the service request BEFORE invoking doBlockingWrite if your caller is single-threaded.
storage-routes/upload-put was not sending `content-length` to `upload-stream-to-s3!`.
This forced us to use the CRT client, as it can send streams without content-length. You may be wondering: how does the CRT client send the stream without a content length? It chunks the stream, and uses S3's multipart API to sends chunks (with content-length) over. 
**But, we _do_ receive the content-length header.** 
Our http handler receives a content-length header. If we passed it along, we could skip the more error-prone 'no content-length' branch of …
> [s3-uploads] pass content-length

- server/src/instant/core.clj
- server/src/instant/storage/s3.clj
- server/src/instant/storage/sweeper.clj
- server/src/instant/util/s3.clj
- We currently use 2 kinds of s3 clients, and one special purpose credential arg for presign urls:
- `s3-client`: for blocking calls, used for most operations
- `s3-async-client`: used for uploading a stream to s3
- `presign-creds`: used to generate long-lived presign urls
We had all three in `util.s3`. These are more related to Instant though. Moved them to instant.storage. I also added some comment blocks, to explain the "why" behind each s3-client. 
> [storage][clean] move clients from util.s3 to storage.s3

- client/packages/core/__tests__/src/instaml.test.js
- client/packages/core/src/instatx.ts
consider: 
```js
tx.users[id].update(...).this_is_an_unsupported_command
```
Right now, we would have returned a `chunk` object. But `this_is_an_unsupported_command` is not a valid command. 
I updated our logic so unless the user calls a valid function command, we return undefined. 
> [instatx] proxy should return undefined with unknown keys

- client/www/components/docs/Layout.jsx
- client/www/components/marketingUi.tsx
**Before**
We had this weird bug, where if you 'overscrolled' our marketing and docs pages, you would see a jarring white bg:
https://github.com/user-attachments/assets/2658435e-1079-4b08-bf25-753e7edd0634
**After**
This was because our html element had a white background. Updated so for those pages, we set html to have the correct background color. 
https://github.com/user-attachments/assets/60023eb6-1551-4700-bab5-f4d9bcee882d
> [sm] make sure html bg matches content bg

- server/src/instant/db/instaql.clj
This moves the unnesting of ors up a level so that the intermediate isNull checks we add for relations will benefit from unnesting.
It also simplifies the type of the where conds to make `and` and `or` just a list of where conds instead of a list of a list of where conds.
**Example**
Take a crazy query like this one:
```clojure
{:test {:$ {:where {:or
[{:or
[{:or
[{"users.id" {:$isNull true}}
{"teams.team_ownerships.users.id" {:$isNull true}}]}
{"teams.users.id" {:$isNull true}}]}
{:or
[{"isPublished" true} {"invites.receiver.id" {:$isNull true}}]}]}}}}
```
Before
```clojure
({:k "test",
:option-map
{:where-conds
([:or
{:or
([[:or
{:or
([[:cond
{:path ("users"), :v [:args-map {:$isNull true}]}]]
[[:cond
{:path ("users" "id"),
:v [:args-map {:$isNull true}]}]])}]]
[[:or
{:or
([[:cond …
```
> Better handling of unnesting ors and ands in instaql

- client/packages/core/__tests__/src/store.test.js
- client/packages/core/src/store.js
- client/sandbox/react-nextjs/pages/play/ruleParams.tsx
- server/src/instant/db/transaction.clj
Been playing with ruleParams, and found some bugs. Fixed two, but have 2 more two fix (updated our ruleParams sandbox to transact with ruleParams too)
1. store.js was failing, because it was not able to handle the `rule-params` tx-step.
a. Fixed this by no-oping the `rule-params` tx-step on the client
1. validation-failed for `params`, because it expected a `map-of string?`, but got `map-of keyword`
a. Fixed by accepting both string and keyword 
Updated the `ruleParams` sandbox, so we test a) `tx.foo[id].ruleParams` and `tx.foo[lookup].ruleParams`
After fixing these bugs I notice more `validation-failed` in permissioned-transaction. Going to dive deeper on those shortly. 
@tonsky @nezaj @dwwoelfel
> [rule-params] two client-side bugs, and transact in sandbox

- client/sandbox/react-nextjs/pages/play/ruleParams.tsx
- server/src/instant/db/permissioned_transaction.clj
- server/src/instant/util/coll.clj
- server/test/instant/db/transaction_test.clj
Fixed `ruleParams` for creates with lookups like
```
tx.docs[lookup('key', key)]
.ruleParams({ ... })
.update({ ... });
```
> Fix rule params create with lookup

- client/www/components/docs/Layout.jsx
When we matched from local cache, we did not check if the app still existed. This meant that if a user deleted an app, we'd get in a broken state. 
Fixed by making sure that we match to an actual app in our `apps` list. 
> [docs] fix inconsistency when loading from cache

- client/www/components/dash/explorer/Explorer.tsx
I noticed in dev we get: 
```
Warning: validateDOMNesting(...): <div> cannot appear as a child of <thead>. Error Component Stack
```
This is because `<div>` is not a proper child of `<thead>`. I went ahead and updated it to be a `<tr>` 
> [explorer] wrap delete row button in tr

- client/pnpm-lock.yaml
- client/www/package.json
- client/www/pages/_app.tsx
- client/www/pages/api/og/essay.tsx
- client/www/pages/dash/index.tsx
- client/www/pages/dash/oauth/callback.tsx
- client/www/pages/essays/[slug].tsx
- client/www/pages/essays/index.tsx
- client/www/pages/examples.tsx
- client/www/pages/hiring.tsx
- client/www/pages/index.tsx
- client/www/pages/intern/signup.tsx
- client/www/pages/intern/top.jsx
- client/www/pages/pricing/index.tsx
- client/www/pages/privacy.tsx
- client/www/pages/terms.tsx
- client/www/pages/tutorial.tsx
Made a series of improvements to our social link improvements. 
- I use the actual blog post title for the og title 
- I leave off the description, so og properly loads a preview of the text
- I made a custom og image generator
In `_app.js` we set defaults like:  `title`, `description`, and `url`. But this doesn't quite make sense. If you loaded pricing for example: 
**Before**
- You got a non-descriptive title and description
- The og:url was wrong here, saying it was the same as the home page. 
**After** 
@tonsky @nezaj @dwwoelfel
> [landing] improve our social previews

- client/www/components/docs/Layout.jsx
Nicole caught a bug, where if you clicked a docs link from our dashboard, and it included the `app` param, our logic to select the app would break. This was due to a rename issue. 
> [docs][bugfix] app id from query params should work

- client/www/components/dash/explorer/Explorer.tsx
User pointed out our icons in explorer are confusing. Seems like the convention is indeed to be reverse of what we currently have. [[Discord]](https://discord.com/channels/1031957483243188235/1148284450992574535/1351718429924659294)
> [Dashboard] Reverse sort icons

- client/packages/core/__tests__/src/instaml.test.js
- client/packages/core/src/instaml.js
- server/src/instant/admin/model.clj
- server/test/instant/admin/routes_test.clj
Consider a transaction like: 
```js
db.tx.users[lookup('handle', 'bobby_newuser')].link({ bookshelves: bookshelfId })
```
If a `user` with handle `bobby_newuser` did not exist, we would: 
1. add triple [user-id :handle "bobby-new-user"]
2. add triple [user-id :bookshelves bookshelfId]
In this case, we never added the `id` triple. This means that when writing queries like: 
```
{ users: { } }
```
This newly created `bobby_newuser` would not show up. 
I went ahead and inserted the id triple even when we are making links 
@dwwoelfel @nezaj  @tonsky
> create entities from link lookups

- server/src/instant/db/cel.clj
- server/test/instant/db/cel_test.clj
If a user wrote a query like this: 
```
{ 
"books": { 
"allow": { 
"view": "newData.id == ruleParams.knownBookId"
}
}
```
This would incorrectly count as a `passing` test. 
**The reason? CelUnknownSet**
Since cel did not receive `newData` as an argument, it returned an `Unknown` evaluation. 
**Fix:** I updated `eval-program` to throw if we get an unknown evaluation. 
@nezaj @dwwoelfel @tonsky  
**Note: I'll take a quick look at using a different compiler for view checks, so we don't even allow `newData`**
> [perms] throw for unknown expressions

- server/Makefile
- server/deps.edn
- server/dev/user.clj
- server/test/instant/test_core.clj
Removes usage of color and right-aligned stack traces that made it hard to scan test output.
Before:
After:
```
1/21 Testing instant.admin.routes-test... 1640 ms
2/21 Testing instant.config-edn-test... 3 ms
3/21 Testing instant.db.cel-test... 265 ms
4/21 Testing instant.db.datalog-test... 1276 ms
5/21 Testing instant.db.indexing-jobs-test... 4592 ms
6/21 Testing instant.db.instaql-test...
FAIL in instant.db.instaql-test/comparators (instaql_test.clj:2588)
└╴string
└╴uses index
├╴form:     (= "triples_string_trgm_gist_idx" (run-explain :string "2"))
├╴expected: "triples_string_trgm_gist_idx"
└╴actual:   "triples_app_id"
FAIL in instant.db.instaql-test/comparators (instaql_test.clj:2591)
└╴string
└╴like uses index
├╴form:     (= "triples_string_trgm_gist_idx" (run-explain :$like :string …
```
> Replace eftest with clojure+.test

- server/src/instant/db/cel.clj
- server/src/instant/model/rule.clj
- server/test/instant/db/cel_test.clj
Previously it was possible to write a `view` or `delete` rule, with a `newData` var. We never passed this value in though, so it would cause an error. 
I update dour cel-compiler, so we use one without the `newData` field for view and delete checks 
I checked to see if there are any rules in prod that does this, and found none: 
```sql
SELECT 
app_id,
r.rule_name,
r.rule_obj->'allow' AS allow_rules
FROM rules,
jsonb_each(code) AS r(rule_name, rule_obj)
WHERE 
r.rule_obj ? 'allow'
AND (
(r.rule_obj->'allow'->>'view' ILIKE '%newData%')
OR (r.rule_obj->'allow'->>'delete' ILIKE '%newData%')
);
```
> [cel] throw when `view` or `delete` has `newData`

- server/src/instant/db/cel.clj
- server/test/instant/db/cel_test.clj
We automatically prepend all binds to cel rules. This caused an error when using our view-delete compiler. 
> [hotfix] add newData back to view-delete rules

- client/www/pages/docs/instaql.md
This was not what I expected, so I think its worth elaborating a bit more. My interpretation of `isLoading` was "in flight" which is not the case here.
> Add further note about useQuery(null).isLoading being true

- client/packages/admin/src/index.ts
For NextJS users who want to use admin.query in ISR:
If they use `admin.query`, it will explicitly fail, because we pass in `cache: 'no-store'` into fetch headers.  
I added a `fetchOpts` option, so users can explicitly set a different option: 
```js
admin.query({ ... }, { fetchOpts: { cache: 'force-cache' } })
```
> [admin][query] add fetchOpts to query

- client/packages/admin/src/index.ts
- client/sandbox/react-nextjs/app/play/check-admin-cache/page.tsx
Right now, we explicitly set `cache: no-store` in the admin API.
We did this, because NextJS 13 & 14 made it so all fetch requests were cached _by default_. 
**However, NextJS 15 onwards** has reverted this, so all fetch request are 'no-store' by default. 
Because we explicitly set `cache: 'no-store'`, folks can't use admin.query in [ISR](https://nextjs.org/docs/app/building-your-application/data-fetching/incremental-static-regeneration#:~:text=If%20any%20of%20the%20fetch%20requests%20used%20on%20a%20route%20have%20a%20revalidate%20time%20of%200%2C%20or%20an%20explicit%20no-store%2C%20the%20route%20will%20be%20dynamically%20rendered.). 
--- 
What I did: 
- I changed our logic so we _only_ add the `no-store` flag, if we are inside nextjs 13 and 14. This way ISR works 'out-of-the-box' with …
> [admin] only set `no-store` for nextjs 13 and 14

- server/src/instant/db/cel.clj
- server/src/instant/db/instaql.clj
- server/src/instant/db/permissioned_transaction.clj
- server/src/instant/model/rule.clj
- server/test/instant/model/rule_test.clj
Only adds a `bind` when the rule actually uses the bind.
For this rule, we don't need to include the `isOwner` bind:
```json
{"myns": {"bind": ["isOwner", "data.ownerId == auth.id"], "allow": {"view": "true"}}}
```
Before:
```
cel.bind(isOwner, data.ownerId == auth.id, true)
```
After:
```
true
```
This should fix the problem we had with `newData` showing up in `view` rules.
I also added a cache for the converting the rule to a program, since we're doing a little extra work each time we parse the rule now.
> [rules] Only include binds that are used

- client/packages/core/__tests__/src/instaml.test.js
- client/packages/core/__tests__/src/store.test.js
- client/packages/core/src/instaml.js
- client/packages/core/src/store.js
- client/packages/core/src/utils/object.js
- client/sandbox/react-nextjs/pages/play/patch.tsx
- client/sandbox/react-nextjs/pages/play/save-undefined.tsx
- client/sandbox/react-nextjs/pages/play/saveundefined.tsx
Made the following changes to instaml: 
**Updating with `undefined` is a no-op:** 
Previously, writing: 
```js
tx.items[id].update({ foo: 1, bar: undefined })
```
Would generate: 
```js
{ foo: 1, bar: null }
```
Now we no-op undefined: 
```js
{ foo: 1 } 
```
**Undefined is ignored in deepMerge**
Previously `deepMerge` would remove keys that came in as undefined: 
```js
// original
{ a: 1, b: 2 }
// toMerge
{ b: undefined } 
// produced: 
{ a: 1 }
```
Now we ignore undefined. 
--- 
> [client] no op of undefined

- client/packages/cli/src/index.js
Sometimes folk put the instant module in devDependenices. This could happen if they are writing a script for example. 
Updated it so when detecting an instant module, we check both dependencies and devDependencies
> [cli] detect packages in devDependencies too

- server/src/instant/db/cel.clj
- server/test/instant/db/cel_test.clj
Reverts the hotfix from https://github.com/instantdb/instant/pull/1044
Should no longer be needed after https://github.com/instantdb/instant/pull/1057
> Revert "[hotfix] add newData back to view-delete rules (#1044)"

- server/deps.edn
- server/src/instant/db/datalog.clj
- server/src/instant/db/instaql.clj
- server/src/instant/scratch/backtest.clj
- server/test/instant/db/instaql_test.clj
When we do `$not`, we also have to check that the attr is not undefined since there might be entities that are missing a triple for the attr. But with indexed attrs, we already insert a `null` for every triple so we can skip that step.
This PR skips adding the `$isNull true` where cond when we know we're checking not on an indexed attr.
> skip null check for `$not` with indexed attrs

- client/www/components/ui.tsx
- client/www/pages/dash/index.tsx
A user pointed out that it's a bit annoying you can't cmd + click on our dash menu items. 
I went ahead and upgraded how we use `ToggleCollection` and `TabBar`, so that these are treated as links. 
@nezaj @dwwoelfel @tonsky 
**Note: we _may_ want to do this for our selector, as well as our explorer tabs too. But first, wanted to ship what users actually asked for**
> [dash] make cmd+click work on tabs

- server/src/instant/core.clj
- server/src/instant/storage/s3.clj
- server/test/instant/db/instaql_test.clj
- server/test/instant/storage/sweeper_test.clj
OS devs reported that they get this error: 
"Unable to load region from any of the providers in the chain software.amazon.awssdk.regions.providers.DefaultAwsRegionProviderChain@375bc55f: [software.amazon.awssdk.regions.providers.SystemSettingsRegionProvider@6dbb85bd: Unable to load region from system settings. Region must be specified either via environment variable (AWS_REGION) or  system property (aws.region)., software.amazon.awssdk.regions.providers.AwsProfileRegionProvider@4a038130: No region provided in profile: default, software.amazon.awssdk.regions.providers.InstanceProfileRegionProvider@37ac16a5: Unable to contact EC2 metadata service.]"}}
I have a hunch this may be because we eagerly load s3 configuration when we start storage/s3. I wrapped the config objects into a delay …
> [storage] delay storage apis

- server/Makefile
- server/resources/migrations/60_statistics.down.sql
- server/resources/migrations/60_statistics.up.sql
Adds most common value statistics for attr_id, ave, checked_data_type, and value, which help postgres to choose a better join strategy for nested loops.
https://www.postgresql.org/docs/current/planner-stats.html#PLANNER-STATS-EXTENDED-MCV-LISTS
I chose 2500 as the `set statistics` value because it allows the db to finish analyze in under 30 seconds.
> Add pg statistics that help pg choose better indexes

- client/www/components/dash/auth/Google.tsx
- server/src/instant/auth/oauth.clj
- in IOS, you can't always provide a `nonce` check. At least not with `react-native-google-signin/google-signin`, the currently popular google sign in module. 
- I went ahead added an option to disable the nonce check. This lets you sign in with Google. 
Coming up, I'll: 
1. Update the UI, to perhaps make it a bit more nicer to flow (ios vs web, etc) 
2. Update the docs 
3. Mini announcement 
> [google] skip nonce checks

- server/src/instant/db/model/triple.clj
Parses dates in RFC 1123 / RFC 822 format, commonly used in headers.
They look like this `Tue, 3 Jun 2008 11:05:30 GMT`
> Parse RFC 1123 date times

- server/deps.edn
- server/src/instant/jdbc/sql.clj
- server/src/tool.clj
Adds a custom viewer for sql queries and a command to copy them to the clipboard in portal.
There's a line in sql.clj you can uncomment to send the queries to portal.
See it in action:
https://github.com/user-attachments/assets/be4d936a-f0c6-4e84-a249-80f267dea366
> [dev] Make it easier to view sql queries in portal

- server/src/instant/db/cel.clj
- server/src/instant/db/dataloader.clj
- server/src/instant/db/instaql.clj
- server/src/instant/db/permissioned_transaction.clj
- server/src/instant/model/rule.clj
- server/src/instant/storage/coordinator.clj
- server/src/instant/util/async.clj
- server/test/instant/db/cel_test.clj
- server/test/instant/util/async_test.clj
Refactors the cel code a bit in preparation for changing how we do prefetching.
Main changes:
1.  We no longer expect callers to construct `CelMap`s. Now that is all internal to `cel.clj`.
**Before**
```clojure
(cel/eval-program!
program
{"auth"       (cel/->cel-map {:ctx ctx, :type :auth, :etype "$users"} current-user)
"data"       (cel/->cel-map {:ctx ctx, :type :data, :etype etype} updated)
"newData"    (cel/->cel-map {} updated)
"ruleParams" (cel/->cel-map {} rule-params)})
```
**After**
```clojure
(cel/eval-program!
ctx
program
;; Don't have to provide auth, cel.clj will pull it from `ctx` for you
{:data updated
:new-data updated
:rule-params rule-params})
```
2.  Introduces a new `severed-vfuture` to fix a bug in dataloader where the dataload might get canceled if a parent `vfuture` …
> Small cel refactor

- client/www/tailwind.config.js
I added some custom divs in our docs: 
https://github.com/instantdb/instant/blob/main/client/www/pages/docs/auth/google-oauth.md?plain=1#L12-L47
**You may be wondering: why not just use a custom tag?** 
I needed to lay out the buttons as a 2 x 2 matrix with titles. When read in mobile, I had to make sure that the title covered the right buttons. 
In order to do this, I had to write a grid layout, and the number of `nav-items` really matters. I thought about using a custom tag, but didn't see an abstraction that was useful. 
So...I went with a `div` abstraction, and just wrote the markup in the markdown. This means though that we need tailwind to pick up those classes. 
> [docs] add to tailwind detection

- server/Makefile
- server/deps.edn
- server/src/instant/dash/routes.clj
- server/src/instant/db/indexing_jobs.clj
- server/src/instant/model/schema.clj
- server/test/instant/admin/routes_test.clj
- server/test/instant/db/indexing_jobs_test.clj
As a preparation for adding new job for required fields, a little refactoring on indexing_jobs.
Main motivation was to decouple scheduling/dispatching from job body itself. After this PR, job body just changes what needs to be changed, but doesn’t know what stage is next or how to handle error. This is decided outside, from data-first description instead of imperative code. Functional core, imperative shell (although our “functional” core still runs updates over SQL, I still feel like scheduling and execution should be separated)
Nothing functionally changed, just moved code around.
Also net negative on code size: 530 insertions(+), 808 deletions(-)
> Refactor indexing_jobs

- server/src/instant/db/instaql.clj
- server/test/instant/db/instaql_test.clj
Forgot to provide an argument.
Also removed the call to `partial`, since clj-kondo won't find invalid arity errors with `partial`.
Includes a test.
> Bug fix for ors and and in rule-wheres

- server/src/instant/db/model/attr.clj
- server/src/instant/util/exception.clj
- server/test/instant/db/transaction_test.clj
- server/test/instant/util/exception_test.clj
Creates a better error for `record not unique: triple`.
**Before**
**After**
Full error:
```json
{
"op": "error",
"status": 400,
"type": "record-not-unique",
"message": "`handle` is a unique attribute on `users` and an entity already exists with `users.handle` = \"daniel\"",
"hint": {
"record-type": "triple",
"attr-id": "d985fdee-8848-46d5-98fa-580625c43c3e",
"etype": "users",
"label": "handle",
"value": "\"daniel\""
}
}
```
> Better error for record-not-unique errors

- server/src/instant/db/instaql.clj
- server/src/instant/db/rule_where_testing.clj
Two changes:
1. Fixes a bug where I tried to call `instaql-nodes->object-tree` on an Exception
2. Puts the user's where clauses first in hopes we'll get a more efficient match.
> Fix rule-where-testing compare on errors

- client/sandbox/react-nextjs/components/EphemeralAppPage.tsx
- client/sandbox/react-nextjs/pages/play/ephemeral-demo.tsx
- client/sandbox/react-nextjs/pages/play/fields.tsx
- client/sandbox/react-nextjs/pages/play/missing-attrs.tsx
- client/sandbox/react-nextjs/pages/play/notandnil.tsx
- client/sandbox/react-nextjs/pages/play/operators.tsx
- client/sandbox/react-nextjs/pages/play/pagination.tsx
- client/sandbox/react-nextjs/pages/play/query-like.tsx
- client/sandbox/react-nextjs/pages/play/stress.tsx
- server/src/instant/dash/ephemeral_app.clj
Creates a new `EphemeralAppPage` component that takes optional `schema` and `perms` props. You can use it to quickly create ephemeral apps for your play page. 
Also updates the ephemeral app endpoint to accept a schema.
You can even seed it with data using the `onCreateApp` prop.
Hopefully this will make it easier to quickly create new play pages. And if you forget how it works, there's a play page for that at http://localhost:4000/play/ephemeral-demo
Here's what the code for a page looks like:
```jsx
import { i, id, InstantReactAbstractDatabase, tx } from '@instantdb/react';
import EphemeralAppPage, {
ResetButton,
} from '../../components/EphemeralAppPage';
const schema = i.schema({
entities: {
docs: i.entity({
title: i.string(),
}),
},
});
const perms = {
docs: {
allow: {
view: 'true', …
```
> Make it easier to create play pages with ephemeral apps

- .github/workflows/clojure.yml
- server/Makefile
- server/README.md
- server/build.clj
- server/deps.edn
- server/src/instant/util/logging_exporter.clj
- server/src/instant/util/tracer.clj
- server/src/java/instant/SpanTrackException.java
This does two things:
1. It sets us up to be able to include java code in our codebase. There have been a few times where it would be easier to just write something in Java, but it was too much effort to get clojure to consume the java file. Now we can easily add new java files in src/java. You still have to restart if you make changes to the java file, though, so it's not super easy (but maybe somebody knows how to set up a reload workflow?). 
2. It only logs a single exception in a set of nested spans.
Right now, we'll log the exception in every single span, since each span will catch the exception, log it, then rethrow the exception.
We accomplish this by adding some data to the throwable. You can add a "suppressed" exception to any throwable, so we add a custom `SpanTrackException` …
> Single exception log and java in src

- server/src/instant/jdbc/wal.clj
We are getting this on app shutdown now:
```
[1761] 1ms [wal-worker/shutdown!] slot_name=dev_768cfcd2597ab83d_0b0067c0cab6f683 exception.message=No matching clause: class org.postgresql.core.v3.replication.V3PGReplicationStream clojure.error.source=wal.clj exception.type=java.lang.IllegalArgumentException exception.escaped=true clojure.error.class=java.lang.IllegalArgumentException clojure.error.cause=No matching clause: class org.postgresql.core.v3.replication.V3PGReplicationStream exception.stacktrace=java.lang.IllegalArgumentException: No matching clause: class org.postgresql.core.v3.replication.V3PGReplicationStream
at instant.jdbc.wal$closed_QMARK_.invokeStatic(wal.clj:330)
at instant.jdbc.wal$closed_QMARK_.invoke(wal.clj:329)
at …
```
> Fix wal shutdown

- client/packages/admin/src/index.ts
- client/packages/core/src/index.ts
- client/packages/core/src/utils/fetch.ts
Previously, promise rejections used plain objects, losing debugging context. Now, using a custom `Error` instance ensures proper (though possibly truncated [^1] ) stack traces, enhancing clarity when debugging failed `await db.transact` calls.
Using `Error` instances in promise rejections is considered a best practice: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/reject
[^1]: (My understanding is), to get full stack traces in npm-installed version, [current compile target](https://github.com/instantdb/instant/blob/main/client/tsconfig.base.json#L8) has to be changed from `es2015` to `es2017`
When an InstantDB transaction such as:
```typescript
const p = await db.transact(memberTxs);
```
fails during development, the error output currently lacks …
> Use custom `Error` instances in `Promise.reject` for improved stack traces

- client/www/components/dash/explorer/EditNamespaceDialog.tsx
A user pointed out that the default had this reversed. Likely folks will want `parent` in the forward direction
> [Dash] Reverse parent <-> children self-link

- client/www/lib/config.ts
- client/www/pages/debug-uri/[trace-id]/[span-id].tsx
- server/src/instant/dash/routes.clj
- server/src/instant/util/exception.clj
- server/src/instant/util/http.clj
- server/src/instant/util/tracer.clj
- server/test/instant/db/transaction_test.clj
This adds a trace id to instant exceptions to make it easier for us to find those errors when users report them:
A regular error looks like this:
```
{
"name": "InstantAPIError",
"status": 400,
"body": {
"type": "validation-failed",
"message": "Validation failed for coerced-query",
"hint": {
"data-type": "coerced-query",
},
"trace-id": "266763b27b2acbff8b4953a7cdb91425"
}
}
```
An unexpected error looks like this:
```
{
"name": "InstantAPIError",
"status": 500,
"body": {
"type": "unknown",
"message": "Something went wrong. Please ping `debug-uri` in #bug-and-questions, and we'll take a look. Sorry about this!",
"hint": {
"debug-uri": "http://localhost:3000/debug-uri/05dc1329925857cc117647024098089c/e261a08df3772884"
}
}
}
```
The debug-uri goes to a custom page. It looks like this when a …
> Add trace ids to user-visible errors

- client/packages/admin/src/index.ts
- client/packages/core/src/Reactor.js
- client/packages/core/src/StorageAPI.ts
- client/packages/core/src/authAPI.ts
- client/packages/core/src/index.ts
- client/packages/react-native/src/index.ts
- client/packages/react/src/init.ts
I was still receiving errors when starting my Tanstack Start app with vinxi. I even had to change the import from the fetch to fetch.js while it is a typescript file. This is a quick fix and will make the builds for Tanstack and Nuxt apps work again.
```
[7:59:27 PM]  ERROR  Cannot find module '/node_modules/.pnpm/@instantdb+core@0.18.6/node_modules/@instantdb/core/dist/utils/fetch' imported from /.output/server/index.mjs
Did you mean to import "/node_modules/.pnpm/@instantdb+core@0.18.6/node_modules/@instantdb/core/dist/utils/fetch.js"?
```
> Fix /utils/fetch and /version imports with .js

- server/resources/migrations/64_better_uuid_constraint.down.sql
- server/resources/migrations/64_better_uuid_constraint.up.sql
- server/src/instant/util/exception.clj
- server/test/instant/db/transaction_test.clj
Right now if you transact an empty string as a linked uuid, you'll get an unhelpful "invalid-text-representation" error.
Example:
```js
db.transact(tx['with-number'][id()].update({}).link({'ref-ns': ''}))
```
This happens because we throw in the constraint on the triples table when we encounter an invalid uuid (in `(value ->>0)::uuid)`:
```sql
CONSTRAINT ref_values_are_uuid CHECK (
CASE
WHEN eav OR vae THEN jsonb_typeof(value) = 'string'::text AND ((value ->> 0)::uuid) IS NOT NULL
ELSE true
END)
```
Now that we're on postgres 16, we can use the handy `pg_input_is_valid` function to check that the value is valid.
Now the error looks like this:
> Better error when you transact an invalid ref value

- server/resources/migrations/64_better_uuid_constraint.up.sql
- server/resources/migrations/65_drop_old_constraint.down.sql
- server/resources/migrations/65_drop_old_constraint.up.sql
- server/test/instant/db/transaction_test.clj
Part 2 of https://github.com/instantdb/instant/pull/1139
Shouldn't be merged until the migration from #1139  is run and the constraint is checked.
> Drop old ref_values_are_uuid constraint 

- server/resources/migrations/63_seed_homepage_app.up.sql
I got an error running my migration locally:
error: migration failed: insert or update on table "apps" violates foreign key constraint "apps_creator_id_fkey", Key (creator_id)=(6f0f64c9-207f-4b35-aec7-82739dcde58e) is not present in table 
I think this could happen when stopa@instantdb.com is inserted, but the id is not 6f0... 
Afaik @verveguy had this issue here too https://github.com/instantdb/instant/issues/1114 
This updates the migration so we do all the transactions in one query, and get the id from the db. 
> [db] fix home page migration

- client/www/pages/docs/patterns.md
Narek pointed out a typo in one of our permission examples. Based on the schema, it should be `owner.ownedTodos`
@nezaj @tonsky
> [docs] ownedTodos fix

- client/www/components/dash/Sandbox.tsx
- client/www/pages/_devtool/index.tsx
- client/www/pages/dash/index.tsx
Adds a combobox to the auth.email field in the sandbox that pulls data from the `$users` table. 
You can still enter a email that's not in the $users table and there's a special `<none>` option for selecting no user.
We'll also keep the last user that you selected in localstorage so you can navigate in the dashboard without losing your place.
I moved it to the middle of the sandbox to give a place for the autocomplete to go and to make it easier to see what user was set.
> Autocomplete users in the sandbox

- server/src/instant/reactive/ephemeral.clj
This reverts commit c7ec7ebcfd28de2287135e80eac29e0867b2735f.
It ended up not being needed. I was able to get around the hazelcast blockage, by manually stopping all instances in AWS
> Revert "[hz] change cluster name and instance-name (#1145)"

- client/www/components/dash/explorer/EditRowDialog.tsx
I noticed an annoying bug when editing rows in the Dashboard. 
If you:
- Erase a number input, you automatically get a `0`
- There's no way to erase this zero and type the number `12` for example
- You invariably type `012`, or `120` 
I updated the code, so we allow an empty state for the number input. 
> [dash] allow for '' in number input

- server/src/instant/scripts/welcome_email.clj
We thought it would be nice to follow up with all non-personal email signups. Feels like it could be an easy win to get more engagement from business users!
> [Growth] Send welcome email to all business users

- server/src/instant/admin/model.clj
I realize we threw an `ex-info` when an unsupported action was provided. I updated this to be a 400 error. 
**Why?**
Previously, we made this a 500, because only our client SDKs provided the `steps`. But now some users call the api directly. In this case, they _could_ provide invalid steps. 
> [sm] better error for admin api

- server/src/instant/core.clj
I noticed that if I made api calls to misspelled routes, I would get an empty 200 response.
Updated so we get a 404. 
> [routes] default 404 in our api routes

- server/src/instant/db/model/attr_pat.clj
- server/test/instant/db/instaql_test.clj
Consider a `createdAt` column: 
```js
posts: i.entity({ 
createdAt: i.date() // unindexed
}) 
```
Insert an object:
```js
db.transact(db.tx.posts[id()].update({ createdAt: 1 }))
```
Now let's query for it: 
```js
{ posts: { $: { where: { createdAt: 1 } } }
```
This query would return an empty result. 
This is because, under the hood, we would always _coerce_ a date value, to a full `Date` object. 
The intention was, that sql would write a query that looks like: 
```sql
triples_extract_date_value(#instant "1970-01-01T00:00:00.001Z") = triples_extract_date_value(v)
```
But since `createdAt` was not indexed, we can't use `triples_extract_date_value`. We would instead write: 
```sql
#instant "1970-01-01T00:00:00.001Z" = v
```
Which would eventually stringify: 
```
"1970-01-01T00:00:00.001Z" = …
```
> [dates] fix equality on dates without an index

- server/src/instant/util/exception.clj
- server/src/instant/util/http.clj
- server/test/instant/db/transaction_test.clj
Give a better error when we get a transaction with too many params. This can happen when you do a transaction that writes a lot of entities at the same time.
```json
{
"name": "InstantAPIError",
"status": 400,
"body": {
"type": "parameter-limit-exceeded",
"message": "There are too many parameters in the transaction or query.",
"hint": {
"message": "Consider batching transactions to reduce the number of writes in a single transaction.",
"doc-urls": [
"https://www.instantdb.com/docs/instaml#batching-transactions"
]
},
"trace-id": "64972e6c3cef4051940b96c5268905a3"
}
}
```
> Too many params error

- server/src/instant/util/tracer.clj
Sometimes tests intentionally run broken/incorrect code to assert on exception. We currently log these as exception when, in fact, they are not—they are expected to break during test.
If some exception is unhandled, it will be logged by test runner as before.
> Hide exception logging outside asserts during tests

- client/packages/core/src/Reactor.js
- client/packages/core/src/index.ts
- client/sandbox/react-nextjs/pages/play/schema-hot-reloading.tsx
Users reported a bug that worked like so: 
1. Take a schema
2. Change it
3. Make a transaction, which _should_ include the changes to your schema
4. But turns out, **it does not**
We cache calls to `init`. This means that when hot-reload triggered a new `init` call, we would return the previously cached `db` instance. The rub? The previous db includes the _old_ schema
Now we detect if the schema has changed. If it _did_ change, we patch the existing client, with the new schema.
You may be wondering: 
**Why not _replace_ the reactor?** 
There's a _lot_ of state in the existing reactor instance. For example, we include current subscriptions there. If we shut down and start a new reactor instance, we'd have to be extra careful to make sure that previous callers don't accidentally end up …
> [client] Schema updates should propagate in a hot reload

- server/src/instant/db/indexing_jobs.clj
- server/src/instant/db/transaction.clj
- server/src/instant/util/exception.clj
- server/src/instant/util/json.clj
- server/test/instant/db/transaction_test.clj
Updates constraint violation errors to be a little more user friendly:
1. Puts the problem in the message, e.g. "Validation failed for triple" -> "Invalid value type for posts.title. Value must be a string but the provided value type is number."
2. Shows the attribute name and namespace that caused the failure
3. For invalid values, tells you the type of the input (if it wasn't truncated)
4. Removes some weird nesting, where we put a list of `errors` in the `hint` field.
Before:
```js
​​{
​​  "name": "InstantAPIError",
​​  "status": 400,
​​  "body": {
​​    "type": "validation-failed",
​​    "message": "Validation failed for triple",
​​    "hint": {
​​      "data-type": "triple",
​​      "input": "2",
​​      "errors": [
​​        {
​​          "message": "Invalid value type for triple.", …
```
> User-friendly constraint violation errors

- client/packages/admin/src/index.ts
Returns error messages as text if we can't parse it as JSON instead of throwing a JSON parse error.
Before:
```
⨯ SyntaxError: Unexpected token 'w', "whoops" is not valid JSON
at JSON.parse (<anonymous>) {
digest: '936232253'
}
```
After:
```
⨯ Error [InstantAPIError]: whoops
at eval (../../src/index.ts:191:6)
at Generator.next (<anonymous>)
at fulfilled (webpack-internal:///(rsc)/../../packages/admin/dist/module/index.js:22:32)
189 |   } catch (_e) {
190 |     return Promise.reject(
> 191 |       new InstantAPIError({
|      ^
192 |         status: res.status,
193 |         body: { type: undefined, message: body },
194 |       }), {
status: 400,
body: { type: undefined, message: 'whoops' },
digest: '301343937'
}
```
> Handle non-json error payloads in admin sdk

- server/flags-config/instant.schema.ts
- server/src/instant/flags.clj
- server/src/instant/util/logging_exporter.clj
Adds a config so we sample logs for heavier apps. The hunch is sampling one or a few apps could significantly reduce our cloudwatch bill!
Steps to make it live:
1) Merge code
2) Push config 
3) Add app id(s)
4) Deploy
> Add config to sample logs

- client/packages/cli/src/index.js
- server/src/instant/dash/routes.clj
- server/src/instant/system_catalog.clj
- server/src/instant/util/coll.clj
Users who didn’t pull make have $files/$users be marked as required from before, which breaks on push. Solution: do not try to push system namespaces at all
> CLI: skip system namespaces during schema push

- server/src/instant/core.clj
- server/src/instant/dash/routes.clj
- server/src/instant/reactive/store.clj
Removes the cloudflare-specific "cf-connecting-ip" in favor of taking the last ip from `x-forwarded-for`. Should be the same and it's dependent on Cloudflare.
Also fixes a bug where I did `::type` instead of `::ex/type`, using the wrong namespace prefix.
And returns a JSON payload from our not found handler.
> Remove cloudflare-specific header

- client/www/components/ui.tsx
- server/src/instant/util/exception.clj
- server/test/instant/db/transaction_test.clj
I noticed we don't give a helpful error message if someone un-intentionally tries to create an attr that already exists. Thought it would be nicer to have a more specific error message
**Before**
**After**
> Better errors duplicate ident creation

- server/src/instant/reactive/ephemeral.clj
- server/src/instant/reactive/session.clj
- server/src/instant/util/hazelcast.clj
Followup to https://github.com/instantdb/instant/pull/1176
Removes the deprecated join-room hazelcast code.
> Remove old join-room code

- client/packages/core/src/index.ts
Followup to https://github.com/instantdb/instant/pull/1176
In core, `db.joinRoom` now takes a third argument with the initial presence data:
```ts
db.joinRoom('roomType', 'room-id', {name: user.name})
```
> Support join-and-set-presence for @instantdb/core

- server/src/instant/reactive/store.clj
- server/src/instant/util/http.clj
Fixes the x-forwarded-for header. The load balancer appends to x-forwarded-for also, so we need to remove the one it added (it will see the cdn's IP address) to get the user's IP.
Also adds the cdn and load balancer trace ids to the http-req span.
> Fix x-forwarded-for, add cdn trace ids

- client/sandbox/admin-sdk-express/package.json
- client/sandbox/cli-nodejs/package.json
- client/sandbox/react-native-expo/package.json
- client/sandbox/react-nextjs/package.json
- client/sandbox/strong-init-vite/package.json
- client/sandbox/vanilla-js-nuxt/nuxt.config.ts
- client/sandbox/vanilla-js-nuxt/package.json
- client/sandbox/vanilla-js-vite/package.json
- client/sandbox/vanilla-js-vite/vie.config.ts
It was unnecessarily hard to see `issue-demo-idbinwisr` in logs and figure out that it corresponds to `sandbox/vanilla-js-nuxt`
> Made sandbox package names match folder names, made logs quieter

- .gitignore
- client/www/lib/markdoc.ts
- client/www/package.json
- client/www/pages/docs/using-llms.md
- client/www/scripts/gen-llms-txt.ts
- client/www/scripts/gen-md-docs.ts
With this PR you can add `.md` to the end of our doc urls to get the extracted markdown. This can be useful for customizing context in an llm setting.
Also updates our llms.txt to point directly to these urls
See [Getting Started](https://instant-www-js-enable-md-jsv.vercel.app/docs.md) as an example
or [explore the docs ](https://instant-www-js-enable-md-jsv.vercel.app/docs) and add `.md` at the end
> [llms] Enable md extension to get raw docs

- client/www/components/dash/Sandbox.tsx
Was using the sandbox to repro a potential bug and noticed we get type warnings on `db.tx` when in fact that should work and is what we recommend folks use in the docs.
This PR makes it so `db.tx` works in the Sandbox
**Before**
**After**
> [Sandbox] Enable db.tx

- client/pnpm-lock.yaml
- client/sandbox/react-nextjs/package.json
- client/sandbox/react-nextjs/pages/play/join-room-set-presence-core.tsx
- server/src/instant/reactive/session.clj
- server/src/instant/util/hazelcast.clj
Fixes a bug where we would reset the presence to null in `@instantdb/core` if you called:
```js
const room = db.joinRoom('name', 'id', { initialPresence: { example: 'value' } });
room.subscribePresence({}, (response) => console.log(response));
```
`room.subscribePresence` also calls `joinRoom` with `null` for initialData (unless you call `room.subscribePresence({data: initialDataHere}, cb)`). That would set the presence data back to null until you called `setPresence` again. 
Now we'll ignore that `null` state in our join room handler.
> Ignore data in join-room if it is null

- client/www/components/admin/AdminRoot.jsx
- server/src/instant/dash/admin.clj
Fetching tx counts causes the recent sign-ups query to timeout. I tried re-working the query a bit but looks like to make it faster we'll need to add some additional indexes.
For now thought it would be nice to get this page working again to have a quicker overview into how recent users are finding us / what they're trying to build
> Remove num tx from intern signup

- client/www/pages/docs/auth/google-oauth.md
You don't need the `drive.readonly` scope to get auth to work. Originally included this, from perusing rn-google-signin's docs. 
One of our users mentioned that webClientId is required as well. I tried running this in my iOS simulator, and it worked, but maybe it's necessary in some other context. I will get some more info from them and push up a fix. 
> [rn-google-signin] remove scopes

- client/www/components/dash/explorer/QueryInspector.tsx
- client/www/components/ui.tsx
Currently we just show "{}", [which can be confusing to users](https://discord.com/channels/1031957483243188235/1370341848304058500/1372154115609853952).
Now we'll show the error message:
> Show errors in query inspector

- server/src/instant/oauth_apps/routes.clj
Errors should include the state param so that they can be tied back to the original request.
> Include state in oauth error response

- server/src/instant/dash/routes.clj
- server/src/instant/util/token.clj
*Note to self: switch base branch back to main before merging*
Depends on https://github.com/instantdb/instant/pull/1205
Allows the `schema` and `rule` endpoints we use from the cli to be used with platform tokens.
This will allow us to do a `npx instant-cli pull` to bootstrap the schema and rules when selecting an existing Instant app on bolt.
> Allow platform tokens for cli push/pull

- client/www/components/dash/PersonalAccessTokensScreen.tsx
- server/resources/migrations/67_personal_access_token_lookup.down.sql
- server/resources/migrations/67_personal_access_token_lookup.up.sql
- server/src/instant/dash/routes.clj
- server/src/instant/model/instant_personal_access_token.clj
- server/src/instant/model/instant_user.clj
- server/src/instant/model/oauth_app.clj
- server/src/instant/superadmin/routes.clj
- server/src/instant/util/token.clj
Prefixes the personal access tokens with `per_` so that we can dispatch on the token type.
I want to allow platform tokens to do `instant-cli push` and `instant-cli pull`, but I need a way to identify that it's a platform token and not a regular user token.
Also changes how we display the tokens--we'll now hash the token when we store it and look it up by the hash. We'll only show you the token when you first create it.
There's a migration to allow older tokens to still function as they did before (but only newer tokens will be able to do `push` and `pull`).
Also includes the changes from https://github.com/instantdb/instant/pull/1206
1. Merge into main
2. run migration
3. deploy code (there will be a short period between step 2 and 3 where people won't be able to generate tokens)
> Prefix personal access tokens

- client/www/components/dash/OAuthApps.tsx
Fixes a bug where you couldn't click the delete button redirect because it would disappear when your mouse moved off of the url.
Changing from `display: hidden` to `visibility: hidden` keeps the button from disappearing.
> Fix deleting the redirect url

- client/packages/platform/src/crypto.ts
- client/packages/platform/src/index.ts
- client/packages/platform/src/oauth.ts
Adds a new `OAuthHandler` to `@instantdb/platform` with helpers for performing the client-only PKCE oauth flow.
How to use:
On the page where you start the OAuth flow:
```tsx
import { useState } from 'react';
import { OAuthHandler } from '@instantdb/platform';
const handler = new OAuthHandler({
clientId: 'instant-oauth-client-id',
redirectUri: 'https://example.com/oauth/instant/redirect',
});
function ConnectPage() {
const [token, setToken] = useState(null);
const handleConnect = async () => {
try {
const token = await handler.startClientOnlyFlow();
setToken(token);
} catch (e /*InstantOAuthError*/) {
console.log(e);
}
};
return token ? (
<div>Connected!</div>
) : (
<button onClick={handleConnect}>Connect to your Instant Account</button>
);
}
```
On the redirect page …
> Adds oauth flow to platform SDK

- server/resources/migrations/68_attrs_etype_label_schema.down.sql
- server/resources/migrations/68_attrs_etype_label_schema.up.sql
- server/src/instant/db/model/attr.clj
Currently almost all operations that include `attrs` have to join `idents` table to get an attr name or a namespace name.
This PR adds these columns directly to `attrs` table (`etype`, `label`, `reverse_etype`, `reverse_label`). It saves us an extra join at the cost of a little denormalization.
`idents` table is kept around for backwards compatibility, it might take some doing to get rid of it.
Not queries have been updated to use new fields. This is more to simplify writing future queries. But I did update some just to demonstrate how it feels.
Deploy plan:
1. Upgrade schema to 68
2. Deploy this PR #1212
3. Upgrade schema to 69
4. Deploy PR #1215
> Add `etype` and `label` to `attrs` table (part 1 of 2)

- client/www/pages/platform/oauth/start.tsx
- server/src/instant/admin/routes.clj
- server/src/instant/model/oauth_app.clj
- server/src/instant/superadmin/routes.clj
Also adds `storage-read` and `storage-write`.
The new scopes allow oauth apps to use the admin sdk (`@instantdb/admin`) to query (data-read/data-write), transact (data-write), download files (storage-read), and modify files (storage-write).
You can use it with the admin sdk like a regular admin token:
```ts
import { init } from '@instantdb/admin';
const db = init({appId: 'some-app-id', adminToken: 'oauth-access-token'})
await db.query({posts: {}})
```
Here's what the scopes look like in the /oauth/start page:
> Add `data-read` and `data-write` scopes to oauth-apps

- client/packages/core/src/index.ts
- client/packages/core/src/rulesTypes.ts
- client/www/components/dash/Perms.tsx
- client/www/components/ui.tsx
- client/www/pages/dash/index.tsx
Updates the `InstantRules` type to accept a schema for better intellisense.
Also updates the json schema for the rules editor to autocomplete with your type names.
Intellisense:
Permissions editor:
> New rules type that accepts a schema

- server/src/instant/db/indexing_jobs.clj
- server/src/instant/db/model/triple.clj
- server/test/instant/db/indexing_jobs_test.clj
Patches an issue where setting required causes the query to time out while we verify that there are no entities that are missing the attribute.
If I'm reading it right, the old query checked for all entities that had any attribute with a matching etype to the required attr. The new query just looks for entities with the id attr. That should be equivalent.
The new query also looks up the id-attr from the `attrs` on the clojure side instead of doing it in the database.
I think we will eventually need an approach where we perform the check in batches, but this should hold us off for a little longer.
It also might help to require that the attribute is indexed to set it as required?
Also adds tests for "required" and "remove-required" jobs.
> Faster check to validated required attrs in the indexing job

- client/packages/core/src/Reactor.js
One of our users noted a bug in the dashboard that worked liked so
* Select 50 items in the dashboard
* Delete them
* See a success toast
* See the rows come back
There was no UI indicating why this happens. Upon inspecting the console, we could see that the transaction timed out.
Looking at our explorer code I notice that we `await db.transact` and if we don't get an error then we show a success toast. When I logged the results of the await, I noticed we were getting back a promise resolved in status pending.
Looking at the Instant core code in Reactor.js, when you call `transact()`, it goes through this flow:
1. `pushTx` → `pushOps` → `_sendMutation`
2. In `_sendMutation`, after 3 seconds, we call `_finishTransaction('pending', eventId)`
3. This resolves the promise with status …
> [Reactor] Remove eager transaction resolution

- client/www/components/dash/Sandbox.tsx
- client/www/pages/docs/patterns.md
It would be nice to start giving users more observability for their queries and transactions. One simple win is to include approximate execution time in the Sandbox. This way users can at least get a sense for how long their slow queries are taking
> [Profiling] Add execution time to Sandbox

- client/www/pages/intern/overview.tsx
- server/src/instant/machine_summaries.clj
- server/src/instant/reactive/ephemeral.clj
Couple of small changes to the overview:
1. Puts the number of sessions for an app on the left so that we don't have to scroll
2. Shows the count of sessions per instance next to the total
It will look something like this:
> Put session count on left in overview, show sessions per machine

- client/packages/platform/src/api.ts
- server/src/instant/superadmin/routes.clj
Adds `createApp` to the PlatformApi.
Accepts optional schema and perms.
```ts
const { app } = await api.createApp({
title: 'My new app',
// Optional permissions
perms: { $default: { allow: { $default: 'false' } } },
// Optional schema
schema: i.schema({
entities: { books: i.entity({ title: i.string() }) },
}),
});```
> Add missing `createApp` function in platform sdk

- client/packages/platform/src/index.ts
- client/packages/platform/src/oauth.ts
- client/packages/platform/src/oauthCommon.ts
- client/pnpm-lock.yaml
- client/sandbox/react-nextjs/package.json
- client/sandbox/react-nextjs/pages/platform/oauth-landing.tsx
- client/sandbox/react-nextjs/pages/play/platform-sdk-demo.tsx
- client/www/pages/docs/auth/platform-oauth.md
I accidentally hard-coded the scopes as `apps-write`. Now you have to pass in the scopes you want when you start the OAuth flow.
Also adds a basic playground at `/play/platform-demo`
> Add scopes to client-only oauth flow

- client/packages/platform/src/api.ts
In `PlatformApi.createApp`, schema and perms should be optional.
> Fix body type for createApp

- server/deps.edn
- server/src/instant/util/hazelcast.clj
- server/test/instant/util/hazelcast_test.clj
I noticed it on tonsky.me, and #kosmik-js reported same recently. Sometimes ephemeral sessions get “stuck”, showing people present that are long gone, with no way to clean it up.
This PR adds periodic 30s heartbeat to every ws connection (new op `"heartbeat"`) and a periodic task on a server to clean up sessions that have not sent heartbeat in 2 to 3 intervals.
> Clean up stale ephemeral sessions (1 of 3)

- server/README.md
Puts the pg_hint_plan library in `/usr/local/lib` instead of the postgres application directory. Mac didn't like us messing around in a signed application bundle.
This method should also make it easier to keep pg_hint_plan working after postgres.app updates.
> Update pg_hint_plan installation instructions

- server/src/instant/db/datalog.clj
- server/src/instant/db/instaql.clj
- server/src/instant/db/rule_where_testing.clj
- server/src/instant/util/instaql.clj
Saw some bad plans for queries that use pagination, so let's just ignore hints for that part of the query for now.
I also noticed we're getting a lot of the same queries in the test pipeline, so I added a cache to try to filter out queries we've already seen. It uses a ttl cache with a ttl of 1 minute--if we see the same query hash twice in that period, then we'll only run the query once (that's not exactly true, b/c we check when we put the query in the queue, but don't set the flag until the query executes, but it's close enough).
> Disable hints for pagination also

- server/src/instant/reactive/session.clj
If we timeout while sending an error, then we'll send another error informing the session that we failed to send the error. We can get into an infinite loop of errors until the session eventually disconnects.
Easier to review with whitespace off: https://github.com/instantdb/instant/pull/1246/files?w=1
> Don't send an error if we fail to handle the error op

- server/src/instant/db/datalog.clj
- server/src/instant/db/instaql.clj
- server/src/instant/db/rule_where_testing.clj
- server/src/instant/flags.clj
- server/test/instant/db/instaql_test.clj
Enables pg_hint_plan for the ea_index. We've been testing it in production overnight and I'm not seeing any queries that are negatively impacted in the logs, whereas we know it helps queries that get the first page by serverCreatedAt (e.g. `{ posts: { $: { limit: 1 } } }`).
Also starts background testing for other indexes. To start testing an index, we just have to add a new row to `toggles` in the instant-config app with setting="pg-hint-test/postgres-index-name" (e.g. pg-hint-test/av_index), value=true.
If we have issues, we can turn it off by setting "disable-pg-hints" to true in the flag toggles.
> Enable pg_hints for the ea index

- client/www/components/dash/auth/Email.tsx
- server/src/instant/dash/routes.clj
A user let us know that protonmail was showing a suspicious-looking error on custom email magic code sends. 
This is because they were stricter about domain checks: specifically with the DKIM value. 
Well, When we create a sender signature, we actually also get the DKIM value that the user can add to their records. 
I went ahead and: 
1. Started to show the DKIM value
2. I also showed the confirmation status for the email.
**Some further work:** 
1. Right now it will take some time for Postmark to pick up the DKIM status. They do have an endpoint that lets us specifically check for DNS records -- it may be nice to push run that when someone says "Refresh status" 
> [custom-emails] add domain verification instructions

- client/packages/cli/src/index.js
- client/packages/core/src/schemaTypes.ts
- client/packages/platform/__tests__/src/schema.test.ts
- client/packages/platform/src/api.ts
- client/packages/platform/src/index.ts
- client/packages/platform/src/schema.ts
- client/packages/platform/src/util.ts
- client/sandbox/react-nextjs/pages/play/platform-sdk-demo.tsx
This PR hides the API format of the schema from the `@instantdb/platform` consumer.
Whenever we return the schema from the API, we always convert it to the `InstantSchemaDef` format (e.g. `i.schema({entities: {...}})`).
When you call any of the functions that would return a schema, like `api.getSchema(appId)`, we'll convert it before we return it, and you'll get a `InstantSchemaDef` back instead.
The code that generates the typescript `instant.schema.ts` file also takes a `InstantSchemaDef` now. I had to make one small change to `DataAttrDef` so that we could keep track of which attrs were inferred. It now has a `metadata` field that you can write to. I store whether the type was inferred there.
~~The code generation also generates `i.json()` instead of `i.any()` now. If that's a problem, …
> Convert InstantAPIPlatformSchema to InstantSchemaDef in platform package

- client/packages/platform/README.md
- client/packages/platform/__tests__/src/schema.test.ts
- client/packages/platform/__tests__/src/typescript-schema.test.ts
- client/packages/platform/package.json
- client/packages/platform/src/index.ts
- client/packages/platform/src/schema.ts
- client/packages/platform/src/typescript-schema.ts
- client/packages/platform/src/util.ts
- client/pnpm-lock.yaml
Adds `schemaTypescriptFileToInstantSchema` to `@instantdb/platform`. 
You can use it to parse a schema file generated by the CLI into an `InstantSchemaDef` (e.g. `i.schema({...})`). 
It's not as robust as the parser we use in the `cli`. The `cli` uses a package called `unconfig`, which requires node APIs that aren't available in the browser.
The code to parse the schema file is pretty inflexible. It parses the typescript with babel, then walks the ast to find all of the `entities`, `links` and `rooms`. I think we could make it a lot nicer if we used `@babel/traverse`, but that doubles our bundle size. With just `@babel/parse`, our bundle is 88kb gzipped. But you'll only pay that bundle cost if you import the `schemaTypescriptFileToInstantSchema` helper. Otherwise it's closer to 13kb …
> @instantdb/platform helper to parse a schema file into an InstantSchemaDef

- client/README.md
- client/packages/core/src/StorageAPI.ts
- client/packages/core/src/index.ts
changed the typing of `uploadFile` to allow uploading a `Blob`s bcz its already supported and its common to have `Blob`s in JS
also minor change in client README to add syntax highlighting
btw great work. thanks!
> Change `uploadFile` typing to allow uploading `Blob`s

- server/src/instant/util/token.clj
It was using the access token prefix instead of the refresh token prefix
> Fix refresh token prefix

- client/www/pages/docs/permissions.md
One of our users noticed a slight security flaw in our example. Before the example wouldn't prevent someone from creating a task and then linking it over to another user (by using their user ID). This change would close that hole
> [Docs] Update perms example

- server/src/instant/grouped_queue.clj
- server/test/instant/grouped_queue_test.clj
Right now, when running `grouped-queue-test/the-queue-is-fair` test, an error get printed out by uncaught exception handler. We expect this error, so there’s no point in printing it out
```
Testing instant.grouped-queue-test... 5 ms
╶───╴
Ran 1 tests containing 1 assertions in 5 ms.
0 failures, 0 errors.
RejectedExecutionException: Task instant.grouped_queue.ProcessTask@67bf8e1a rejected from java.util.concurrent.ThreadPoolExecutor@45d190ca[Shutting down, pool size = 1, active threads = 1, queued tasks = 0, completed tasks = 3]
ThreadPoolExecutor$AbortPolicy.rejectedExecution  ThreadPoolExecutor.java 2081
ThreadPoolExecutor.reject                         ThreadPoolExecutor.java 841
ThreadPoolExecutor.execute                        ThreadPoolExecutor.java 1376
instant.grouped-queue/execute …
```
> Silence expected group-queue-test error

- client/packages/platform/src/api.ts
- client/packages/platform/src/index.ts
- client/packages/platform/src/oauth.ts
- client/packages/platform/src/serverOAuth.ts
This enables automatic token refresh for the platform API.
If you provide an `auth` object with `{clientId, clientSecret, accessToken, refreshToken}`, then we'll notice when the token is expired and we'll refresh it and try again.
The way we determine that it's expired is to catch exceptions that return 401 and refresh. It might be nicer to check the expiredAt first, but I didn't want to make callers keep track of the `expiresAt` for their token. This seemed like a nicer interface.
If you want to know when the token refreshed so that you can save the new accessToken, you can provide an `onRefresh` callback in the `auth` object.
If you want to manage refreshing tokens yourself, just keep passing `{accessToken: token}` as the `auth` arg when you create the `PlatformAPI`.
> Set up platform API to refresh tokens

- client/www/pages/dash/index.tsx
A user reported they saw a warning that said: 
client.ts:59 A component is changing from uncontrolled to controlled. 
I repro'd this by loading /dash without an pre-existing app set. 
What is happening is that `Combobox` was receiving `undefined`, which caused it to believe that it was an uncontrolled component. 
I went ahead and used `null` instead. 
> [dash] ensure controlled component

- client/www/components/dash/explorer/EditRowDialog.tsx
A user once asked us to include a "now" button for dates. I went ahead and added the button. 
> [ui] add a "now" button for dates

- server/src/instant/model/oauth_app.clj
- server/src/instant/oauth_apps/routes.clj
Fixes the error stopa ran into when clicking deny (I think the request had previously been approved, maybe?). Right now it just returns JSON. It would be nicer if we returned an HTML page, but I think that's a bigger project.
> Make deny-redirect throw if there is no redirect

- client/www/pages/platform/oauth/start.tsx
- server/src/instant/oauth_apps/routes.clj
Allows the user to see which Instant account they're giving access to.
Looks like this:
> Show the logged in user in the oauth confirmation page

- client/packages/mcp/README.md
This is a requirement for getting listed on the Cline marketplace. They want a README in the repo that will tell them how to install the MCP server: https://github.com/cline/mcp-marketplace?tab=readme-ov-file
> Include mcp usage in the @instantdb/mcp readme

- client/packages/platform/src/api.ts
- client/sandbox/react-nextjs/pages/play/platform-sdk-demo.tsx
The platform api currently returns an admin token on app creation but we did not include that in the platformSDK.
This PR adds `adminToken` to `InstantAPIAppDetails` when it's returned from the server
> [Platform] Include admin-token on create

- server/src/instant/db/datalog.clj
- server/src/instant/reactive/ephemeral.clj
- server/test/instant/db/instaql_test.clj
Analyzes the datalog pattern to determine which index we should use based on which columns are known.
Consider this datalog query:
```clojure
[:ea ?tbl-0 :tbl/id _]
```
We generate a query that looks like:
```sql
SELECT * FROM triples WHERE (app_id = :app) AND ea AND (attr_id = :tbl/id)
```
We know that `a` is a constant, but `e` and `v` are unknown, so we should use an index that starts with `a`. The only index like that in the `triples` table is the `triples_created_at_idx`, so we use that. 
Before we would try to use the `ea` index, which doesn't help us at all because it has `e` before the `a`.
I'll run this in testing mode to see if there are any queries that it makes worse, but I didn't find any when testing the usual suspects locally.
> Better index selection for pg_hint_plan

- server/src/instant/model/app.clj
- server/src/instant/superadmin/routes.clj
Allows the admin token for an app to be used with the platform SDK for operations that take an appId.
Example:
```
const api = new PlatformApi({auth: {token: 'YOUR_APP_ADMIN_TOKEN'}});
await api.getSchema('YOUR_APP_ID');
```
> Allow app admin tokens in the platform SDK

- client/packages/cli/src/index.js
The create app endpoint returns the admin token and I thought it would be nicer for us to include that in the `.env` file we generate on `init` to make it slightly easier for folks who want to get started with Instant on the backend
> [CLI] Include admin token on init

- client/www/pages/docs/cli.md
What it says on the tin! We've seen focus sometimes be surprised that they need to run `login` first before `init` so thought it would be nice to include a blurb about that too
> [DOCS] Add docs for cli create-app

- server/src/instant/db/datalog.clj
- server/test/instant/db/instaql_test.clj
We use a gist index for strings so that `like` will be efficient, but it's not very good for exact matches, and it's not very good for ordering because it doesn't produce a sorted output ([according to the documentation](https://www.postgresql.org/docs/current/indexes-ordering.html), only B-Tree indexes produce sorted output).
We already have everything in the `ave` index and it sorts in the same order as strings do. We can use it for any index comparisons that don't use `like` or `ilike`.
This PR uses the `ave` index when we're sorting by strings, but still uses the gist index when comparing with `like` or `ilike`.
> Use ave index for string operations

- server/resources/migrations/73_vae_uuids.down.sql
- server/resources/migrations/73_vae_uuids.up.sql
- server/src/instant/db/datalog.clj
- server/src/instant/db/instaql.clj
- server/src/instant/db/model/attr_pat.clj
- server/test/instant/db/datalog_test.clj
- server/test/instant/db/instaql_test.clj
We only put refs in the vae and eav indexes so we know that the value will be a uuid. This PR stores those uuids as actual uuids in the index itself. 
This makes the indexes take up less space (they're about 30% smaller).
The big change is that now we can use `vae` instead of `eav` when we do a join on a ref, which saves us doing an expensive json->uuid conversion in the join filter. Here's a simple example:
```clojure
{:books {:where {:category "western" :author :eid/elmer-kelton}}}
```
That generates two ctes:
```
with m_0 as (
select entity_id as m_0_eid from triples t0 where attr_id = :category-eid and value = "western"
),
m_1 as (
select m_0.*, entity_id as m_1_eid from triples t1 where value = :eid/elmer-kelton and m_0.m_0_eid = json_to_uuid(value)
)
```
If we use the `eav` index …
> Put uuids in the vae and eav index

- server/src/instant/util/logging_exporter.clj
Drops a few logging events in prod that aren't very useful for debugging via the logs.
Chosen [based on this query](https://us-east-1.console.aws.amazon.com/cloudwatch/home?region=us-east-1#logsV2:logs-insights$3FqueryDetail$3D~(end~0~start~-3600~timeType~'RELATIVE~tz~'UTC~unit~'seconds~editorString~'parse*20*40message*20*22*5b*2a*5d*20*2ams*20*5b*2a*5d*20*2a*22*20as*20trace_id*2c*20duration*2c*20span_name*2c*20rest*20*0a*7c*20stats*20sum*28strlen*28*40message*29*29*20as*20total_length*20by*20span_name*20*0a*7c*20sort*20total_length*20desc~queryId~'0af4912b-bb7e-45e7-b549-bdde6ef091b6~source~(~'*2faws*2felasticbeanstalk*2fInstant-docker-prod-env-2*2fvar*2flog*2feb-docker*2fcontainers*2feb-current-app*2fstdouterr.log)~lang~'CWLI)), which shows the span names that generate the most log …
> Drop some logging events in prod

- client/packages/mcp/src/oauth-service-provider.ts
Fixes a bug with VSCode, where it will generate the client without any scopes, then fail to go through the OAuth flow because the client doesn't have the requested scope.
> Set default scopes for the MCP server if they're not provided

- server/src/instant/auth/oauth.clj
Report: https://discord.com/channels/1031957483243188235/1384530339354906654
Reason: apparently Invertase converts `nonce` to SHA256 of `nonce` before sending it to Apple. During `signInWithIdToken` we compare nonce from `id_token` returned by Apple and nonce user provides, and that check was failing
https://github.com/invertase/react-native-apple-authentication/blob/cadd7cad1c8c2c59505959850affaa758328f1a3/android/src/main/java/com/RNAppleAuthentication/AppleAuthenticationAndroidModule.java#L139-L146
Kicker: Comment in invertase codebase:
```
// SHA256 of the nonce to keep in line with the iOS library (and avoid confusion)
```
Avoid confusion 🥴
> Fix Sign In with Apple with Invertase lib

- client/www/components/dash/explorer/Explorer.tsx
I noticed when we fail to delete rows in the explorer we don't give a helpful error to our users. This is especially confusing in the following scenario
```typescript
// instant.schema.ts
const _schema = i.schema({
entities: {
$users: i.entity({
email: i.string().unique().indexed().optional(),
}),
profiles: i.entity({
handle: i.string(),
}),
posts: i.entity({
title: i.string(),
content: i.string(),
createdAt: i.number().indexed(),
}),
},
links: {
userProfiles: {
forward: { on: "profiles", has: "one", label: "user" },
reverse: { on: "$users", has: "one", label: "profile" },
},
postAuthors: {
forward: { on: "posts", has: "one", label: "author", required: true },
reverse: { on: "profiles", has: "many", label: "posts" },
},
},
});
```
Now if you create some users/profiles/posts and then try …
> [Explorer] Better error for failed delete

- server/src/instant/scripts/daily_metrics.clj
Let's run the metrics job on the weekends. I _think_ only computing one days worth at a time should be enough for the jobs to finish w/o timing out
> [Metrics] Run on weekends

- server/src/instant/db/model/triple.clj
Found one more use of the vae_index in the auto_explain.
This makes us do the comparison with `json_uuid_to_uuid(value)` so that we can look it up directly in the vae_uuid_index without doing the conversion.
> Remove another usage of the vae index

- server/src/instant/scripts/daily_metrics.clj
Previously the timeout for the metrics job was 3 minutes.
Saw the metrics job didn't run again today -- looks like it takes just over 3 minutes to run query for one day of data. Doubling the timeout time to unblock the jobs.
The main culprit is the size of our transactions table. It's almost ~1bil records! (which in itself is a fun fact -- we've almost processed a billion transactions on instant!)
> [Metrics] Increase daily job metrics timeout to 6 minutes

- client/www/lib/auth.ts
- client/www/pages/intern/index.tsx
- server/src/instant/dash/routes.clj
Thought it would be nice to have an index page for all our current internal tools!
This also adds a `dash` endpoint to check whether we are an admin.
> [WWW] Add intern index page

- client/packages/core/src/Reactor.js
- client/packages/core/src/index.ts
- client/packages/react/src/useQuery.ts
- client/sandbox/react-nextjs/components/EphemeralAppPage.tsx
- client/sandbox/react-nextjs/lib/useIsHydrated.tsx
- client/sandbox/react-nextjs/pages/play/query-cache-test.tsx
Adds a new option to `init` to allow users to specify the number of queries they want to cache. The default it still 10, but now you can do ``init({ appId ..., schema, queryCacheLimit: 50 })` to persist the last 50 queries.
You can test this out in the sandbox app at `http://localhost:4000/play/query-cache-test`
In making the sandbox app I discovered two bugs
- When switching between different todos (changing the query), the component would briefly show data from the previously selected todo
- This created a confusing UX where clicking Todo B, which was not cached, showed Todo A data
Looking at the `useQueryInternal` function in `/packages/react/src/useQuery.ts`, there was an issue in how `resultCacheRef` was being managed:
```typescript
// Line 56-58: This ref is only initialized ONCE on …
```
> [core] Add configurable offline query cache size

- client/www/lib/hooks/explorer.tsx
Fixes the type error when we use `aggregate: 'count'` in our admin query on the dashboard.
We don't put that in the types because it only works if you're on the dashboard. The type changes in https://github.com/instantdb/instant/pull/1335 must have added stricter type checking of the useQuery query somehow.
> Type fix for aggregate in admin query

- client/pnpm-lock.yaml
- client/www/components/dash/Schema.tsx
- client/www/components/dash/explorer/EditNamespaceDialog.tsx
- client/www/components/ui.tsx
- client/www/lib/hooks/explorer.tsx
- client/www/lib/schema.tsx
- client/www/package.json
- client/www/pages/dash/index.tsx
- server/src/instant/model/schema.clj
This adds a `Schema` tab to the dashboard where you can see the full schema for an app in `instant.schema.ts` form.
I've found it very useful for debugging query issues that people report. 
Opening as an RFC because I'm not 100% sure it's a good fit for the dashboard. It's read-only and people might expect you could do a bit more on the schema tab besides just view your `instant.schema.ts`. If we're worried that users will get confused, we could just leave it off the sidebar. Then we could still use it for debugging by adding `t=schema` manually.
Here is what it looks like:
> Add a schema page to the dashboard where you can see the full schema

- server/src/instant/core.clj
Adds caching to our cors preflight requests.
If the cors origin is allowed, then we will tell the browser and CDN to cache it for 5 minutes. If it's not allowed, we don't add any caching headers. If everything works well, we could increase the cache duration to something like a day.
This will make things like initializing a session or creating an ephemeral app faster. If the user makes two requests within 5 minutes, their browser will cache and they won't have to make a second options request. And if other people have made requests in the last 5 minutes, then they can get the response directly from the CDN instead of going all the way back to the origin.
There is an instant-config toggles setting to turn off caching globally. I've set the toggle to disable it until we get it in production …
> Cache preflight options requests

- server/src/instant/model/app.clj
This makes creating an app a little bit faster because we don't have to do two round trips to the database. 
Inserts both the app and the admin token with a CTE instead of two queries inside of a transaction.
> Single query for create-app

- client/packages/platform/src/api.ts
Fixes a bug where it used the wrong inflection, now it will say "Finished 1 schema operation" or "Finished 10 schema operations".
> Fix inflection on schema operations

- client/packages/mcp/package.json
- client/packages/mcp/src/db/instant.schema.ts
- client/packages/mcp/src/index.ts
Fixes the rate limit from a global limit to an IP-based limit. `express-rate-limiter` didn't like that we were setting `trust proxy` to true, instead we have to set it to 2.
Other minor changes:
1. Replaces `--preserveWatchOutput` with `--clear-screen=false` in the `dev` alias (`--preserveWatchOutput` isn't a supported flag for tsx)
2. Marks the tokenHashes as unique to fix deleting tokens
3. Stops logging health checks to make the logs easier to parse
> [mcp] Fix rate limit in remote server

- client/www/components/dash/Sandbox.tsx
A user reported an edge case where we could accidentally double-run in the sandbox. This makes it so we can only run one exec at a time
> [Sandbox] Prevent double running

- client/www/pages/docs/init.md
Recently added `queryCacheLimit` as a new option to `init` and wanted to add docs for this. Figured it would be good to document all the options for init as well.
> [Docs] Add info on init options to docs

- client/Makefile
- client/www/components/docs/RatingBox.tsx
- client/www/components/intern/docs-feedback/analytics-dashboard.tsx
- client/www/components/intern/docs-feedback/comments-view.tsx
- client/www/components/intern/docs-feedback/page-drilldown.tsx
- client/www/lib/intern/docs-feedback/README.md
- client/www/lib/intern/docs-feedback/analytics.ts
- client/www/lib/intern/docs-feedback/instant.schema.ts
Main change is adding `createdAt` to the feedback app so we can show when someone gave us feedback about our docs.
Also changed the following:
* Added deep-linking so when you refresh you don't go back to the index
* Updated docs / removed the makefile command for updating the feedback app
I had trouble with the Makefile command not being able to pick up the schema/perms, it always wanted to create a new app. Figured instead of having those commands would be nicer to just be explicit on how to update the app
> Add created date to feedback app

- server/src/instant/db/model/attr.clj
Makes add-attr fast when you're adding a new non-indexed attr on a large table.
If the attr is indexed, we have to add nulls to every entity in the triples table. Postgres was getting confused and trying to check which entities needed nulls even when you added an unindexed attr. 
Removing the joins to the idents table allowed postgres to build a better query plan that skipped the whole check when you weren't adding an indexed attr.
Adding indexed attrs to an existing table is still slow. I'll follow-up with a PR that does that in two steps: 1. adds the attr without indexing it, 2. creates a background job to index it.
> Faster add-attr when not indexed

- client/www/pages/essays/[slug].tsx
- client/www/pages/essays/index.tsx
The whole blog being Sans-serif felt a bit bland. Thought we could spruce it up a bit. Added back font-mono to headings: 
> Add font-mono back to the blog

- server/src/instant/db/datalog.clj
Sometimes it's better to use the eav index, for example in the zeneca query:
```clj
{:books {:$ {:where {:bookshelves.users.handle "stopa"}}
```
We send patterns to datalog that look like:
```clj
[[:av ?users-2 :user-aid "stopa"]
[:vae ?users-2 :bookshelves-aid ?bookshelves-1]
[:vae ?bookshelves-1 :books-aid ?books-0]]
```
Since we've resolved `?users-2` as an entity-id in the first pattern and it's in the e position in the second pattern, using the eav index will hit the `e` and the `a`, which will usually make a good plan for postgres.
On the other hand, if we went the other way through the links:
```clj
{:users {:$ {:where {:bookshelves.books.title "The Count of Monte Cristo"}}}}
```
We'll create patterns:
```clj
[[:ave ?books-2 :title-eid "The Count of Monte Cristo"]
[:vae …
```
> Use the eav index when it's better

- server/src/instant/intern/metrics.clj
Noticed I introduced some reflection warnings, looking a little closer at `format-date-label` I realize I only pass in `java.sql.Date` type so figured would just simplify and hint it
> [Metrics] Fix reflection warning

- server/src/instant/util/aws_signature.clj
- server/test/instant/util/aws_signature_test.clj
Following up from #977 , let's set a response cache header to speed up subsequent loads of a presigned url.
**Before** (on reload)
**After** (on reload)
> Add response cache control

- client/www/components/dash/explorer/Explorer.tsx
In #1418 added `autofocus` to the create namespace input which triggers password managers. Interestingly we don't have this problem for the new app modal which also auto-focuses.
The only difference is the new app modal doesn't provide a label for the `TextInput`. Looking at `TextInput`, we wrap the whole input inside a `label` tag regardless of whether a value for label was provided. If a value was provided though, we add a div before the input with the label text.
I'm not too familiar with how password managers detect and autofill fields, but from some sleuthing on stack overflow and talking with claude removing the "Name" text from inside the <label> eliminates detection.
Another alternative was to remove the `label` tag and instead wrap the whole input in a `div` -- but this seems …
> Tweak create namespace input

- client/www/components/dash/explorer/EditRowDialog.tsx
pressing backspace at this state would previously do nothing and you would be stuck with a single quote you couldn't remove. this pr allows the text field to be empty
> allow backspace to empty field when editing json

- server/src/instant/db/instaql.clj
This ignores ordering for child forms on the postgres side. We'll still give the user the data in the right order when they get it from the client or the admin query. 
We don't support pagination on child forms and we don't rely on the order of the triples from postgres to apply the order-by on the client (or in admin query). So any ordering we do in postgres for child forms is just wasted cycles.
In this query:
```clj
{:users {:$ {:where {:email {:$ilike "%org.com"}, :order {createdAt "desc"}
:comments: {:$ {:order {:createdAt "desc"}}}}}
```
We'll order the users in the database so that we can get cursors, but we'll treat the comments query as if it was written without the order by.
I'd also like to skip the ordering when you don't provide a `first`, `last`, `before`, or `after` param, …
> Skip child order

- server/deps.edn
- server/src/instant/core.clj
- server/src/instant/db/datalog.clj
- server/src/instant/db/hint_testing.clj
- server/src/instant/db/instaql.clj
- server/src/instant/util/pg_hint_plan.clj
Uses counts from the database to choose better hints.
This is an experiment to see how good we can be at generating query plans if we have count information from the database. Right now it does an actual query like `count * from triples where attr_id = :attr-id and value = :value`. But if this works, then we should be able to replace that database query with a lookup in a [count-min sketch](https://en.wikipedia.org/wiki/Count%E2%80%93min_sketch) that we maintain for each attr.
**How it works**
If the *testing-pg-hints* flag is on, we'll walk the `nested-named-patterns` to determine the best index to use for each pattern and update each pattern with the index to use. We walk it in two phases--in phase 1, we collect all of the count queries we will need to make. Then we fetch all of the …
> Better pg_hint_plan with counts

- client/packages/cli/src/util/packageManager.js
Bun recently switched to a non-binary lockfile format for new projects. If that is in use, this will detect it.
> Detect Bun in cli for newer versions of Bun.

- client/www/pages/docs/instaql.md
- client/www/pages/docs/users.md
A user pointed out that we had an extra `userId` column in one of our docs examples. This isn't really necessary, as we already have a link to a particular user. 
Ref: 
https://x.com/maxrusakovic/status/1944417503163125993
I went ahead and updated that example, plus one other place in the docs where we used a `userId` as an example. 
> [sm] remove `userId` from docs examples

- client/www/pages/docs/auth/apple.md
A user pointed out that in one of our steps for sign in with apple, we were talking about a "step 3.5", which was non-existent for their flow. 
Ref: https://x.com/maxrusakovic/status/1944073418204119395
This is because our conditional param was not working, when we included `` beside it. 
I went ahead and removed the prettier-ignore, and the conditional now works. 
> [docs] Fix reference to step 3.5 in Sign in with Apple

- client/www/components/docs/Layout.jsx
- client/www/lib/locallySavedApp.tsx
- client/www/pages/dash/index.tsx
In one of our user sessions, a user mentioned how he was surprised that the selected app across dash and docs weren't in sync.
I went ahead and made it so both the docs and the dash use the same local storage key to store the app id. 
Hence, they now stay in sync!
**Note: you may be wondering, why keep using getLocal and setLocal, instead of useLocalStorage?** 
If we switch to `useLocalStorage`, we can't quite keep the useEffect logic as it currently is, since setting our cached item will trigger a re-render. I wanted to keep this change incremental. 
> Use the same cache key for docs and dash selected app

- server/src/instant/db/datalog.clj
Improves the cost estimator for pg-hint-plan:
1. Tries to determine the cost of using the index with a join. The algorithm is pretty dumb, it just multiples the average number of items in the index path with the number of items in the join condition. But it seems to work pretty well. I'll be studying the [pg optimizer code](https://github.com/postgres/postgres/tree/master/src/backend/optimizer) for better ideas when I get a chance.
2. We're smarter about join orders with pagination. Before, if the query was very simple, we put the page pattern first. That's not ideal if the first pattern would filter out most of your rows. Now we check if there are few rows in the first pattern.
3. We mark more things as `not materialized` if we're using hints. 
One other small change: I updated our logic …
> Planning improvements

- server/resources/migrations/74_drop_old_vae_eav_indexes.down.sql
- server/resources/migrations/74_drop_old_vae_eav_indexes.up.sql
Removes the indexes that were replaced in https://github.com/instantdb/instant/pull/1326
I'll delay merging and check the autoexplain to be sure we don't still have queries relying on these indexes.
```sql
drop index concurrently if exists vae_index;
drop index concurrently if exists eav_index;
```
> Remove old vae and eav indexes

- client/www/components/dash/Perms.tsx
- client/www/components/dash/Schema.tsx
- client/www/components/dash/explorer/Explorer.tsx
- client/www/components/dash/explorer/QueryInspector.tsx
- client/www/pages/_devtool/index.tsx
- client/www/pages/dash/index.tsx
We got a repro in https://github.com/instantdb/instant/issues/790 which shows that shows when users created a new namespace in the Sandbox tab, it wouldn't appear in the Explorer tab until they refreshed the page.
Moved the schema subscription to the dashboard level to capture all namespace changes, eliminating the issue where newly mounted tabs wouldn't receive the current namespace state
1. Created `DashboardContent` component in `/www/pages/dash/index.tsx` that:
- Calls `useSchemaQuery` at the dashboard level
- Passes namespace data as props to child components
- Ensures namespace updates are always being listened to
2. Created `DevtoolContent` component in `/www/pages/_devtool/index.tsx` with the same pattern
Thought it was also nicer to encapsulate these into their own components -- …
> [Dash] Fix namespace updates no propagating

- client/www/components/marketingUi.tsx
- client/www/pages/index.tsx
I realize the only links we have to the tutorial at the moment are the button in the hero unit and in the home tab of the dashboard. Thought it would be nice to also add it into the header nav and be more explicit in the CTA.
Also removed some links in the footer which I thought was a little crowded
> Tweak header and footer navs

- client/www/pages/docs/using-llms.md
After clicking the `whirlwind tutorial` link, it redirected to the home page `instantdb.com` as the link is not found.
Use the right link to the tutorial and it should navigate to it.
> Update using-llms.md: fix the not-found link

- client/www/pages/docs/instaql.md
A user was surprised that they could use nested attributes for `where` but not for `order` -- clarifying that in the docs!
> Clarify nested order

- server/deps.edn
- server/src/instant/jdbc/copy.clj
- server/src/instant/util/json.clj
- server/test/instant/jdbc/copy_test.clj
This adds support for postgres copy. We'll use this to populate the attr sketches when we first create the new logical replication slot for the aggregator.
It also upgrades cheshire and jackson to fix a bug with parsing bytes. I looked through the change history and didn't see any breaking changes in the documentation that would affect us.
When we create the replication slot, postgres will give us a snapshot identifier. We can use that snapshot identifier to call `set transaction snapshot :snapshot-id` and get a view into the database as of the time that the snapshot was created. Then we can call `copy` on that connection to fetch all of the triples and build up the attr sketches. Once the sketches are saved, we can start listening to changes on the new slot. This will give us a …
> Adds support for postgres copy out

- client/packages/core/__tests__/src/queryValidation.test.ts
- client/packages/core/src/queryValidation.ts
- client/packages/version/src/version.ts
For the query
```typescript
const todosQuery = {
todos: {
owner: { $: { limit: 1 } },
},
} satisfies InstaQLParams<AppSchema>;
```
> Validate pagination params are only used at top level

- client/www/pages/docs/instaql.md
The docs said order can only be used in top-level namespaces but it can be used in nested namespaces. Clarifying that here!
> [Docs] Clarify order can be used in nested namespace

- client/www/lib/intern/llm-example/app/page.tsx
- client/www/lib/intern/llm-example/llm-rules-template.md
- client/www/pages/intern/llm-example.tsx
- client/www/pages/tutorial.tsx
Did a pass on the live tutorial and noticed a few fixes
* The frontmatter was off for cursor and windsurf
* Updated instructions for cursor to specify `.mdc` format
* Used `<div></div>` instead of `<></>` in App component.
* Fixed SSR issue for `intern/llm-example`
> Tweak llm rules

- client/www/lib/intern/llm-example/app/page.tsx
- client/www/lib/intern/llm-example/llm-rules-template.md
Made a few more tweaks. To address these issues I've been seeing
* Sometimes `useProfile` is used outside of `db.SignedIn`
* Seeding data on the client can lead to infinite loops due to permission failures.
* Standardize on using `CRITICAL` instead of `IMPORTANT` for hints
> [RULES] Tweak seed rules

- client/packages/mcp/src/index.ts
It looks like we are getting some errors authenticated with MCP. It looks like the reason is because of a validation failure when we give the admin sdk lookups. Disabling validation for now to see if that fixes things. 
> [tempfix] disable validation for mcp

- client/packages/mcp/src/index.html.ts
- client/www/pages/docs/using-llms.md
- client/www/pages/tutorial.tsx
looks like cursor added a `/en` to their install-mcp link 
> fix cursor link

- client/packages/core/__tests__/src/transactionValidation.test.ts
- client/packages/core/src/queryValidation.ts
- client/packages/core/src/transactionValidation.ts
- client/packages/version/src/version.ts
- client/sandbox/admin-sdk-express/package.json
- client/sandbox/admin-sdk-express/src/index.ts
- client/sandbox/admin-sdk-express/src/with-schema.ts
This PR fixes the issue of lookup attributes being tested as UUIDs and throwing errors for valid transactions
> fix lookup strings being tested as uuids

- server/src/instant/db/indexing_jobs.clj
- server/src/instant/reactive/session.clj
- server/src/instant/reactive/store.clj
- server/src/instant/util/http.clj
Various debugging improvements:
1. Adds a tag to sql query in indexing-jobs
2. Moves the tracer around the try-catch in indexing jobs so that we can see what caused the errors in honeycomb
3. Adds `x-amzn-trace-id` and `x-amzn-cf-id` to `handle-receive`'s tracer attrs to make it easier to trace the connection back to the load balancer and cdn
4. Doesn't skip the websocket request in the tracer. The idea was that we shouldn't wrap a span around the websocket handler because it's long-running and all of its children would be attached to the trace. I was expecting to have to use [`tracer/with-new-trace-root`](https://github.com/instantdb/instant/pull/1511) on it, but it turns out not to be necessary. The handler completes immediately and just gets handed off to an internal undertow handler.
> Add more debugging data

- client/packages/core/__tests__/src/instaql.test.js
- client/packages/core/src/instaql.js
- client/packages/core/src/utils/strings.ts
- client/packages/version/src/version.ts
Sorts strings lexicographically using `Intl.Collator('en-US')`, with a fallback to `String.localeCompare`.
This will fix some issues with pagination where items get cut out due to incompatible sorting. 
More info in this paper doc: https://www.dropbox.com/scl/fi/zcoagghpaztcrz388d2jo/How-should-we-sort-strings_.paper?rlkey=n7btkf1hxxcym2z9ssdct30kj&st=we5c28dh&dl=0
> Sort strings lexicographically on the client

- server/src/instant/db/datalog.clj
- server/src/instant/flags.clj
This adds support for `always-materialize-attr-ids` in the flags instant-config field.
Quick hack to make some queries more efficient while we work on improving join orders with the attr sketches.
> Hack to improve some slow queries

- server/src/instant/reactive/store.clj
- server/test/instant/reactive/store_test.clj
Before we were just replacing `%` with `.*` and `_` with `.` and then creating a pattern out of it. If you had some regex special characters in the pattern, then we would include those as part of the pattern.
Now we walk the pattern and quote any strings in the pattern, so that it matches the string exactly.
Also added some additional tests.
> Fix for converting like pattern to regex

- client/packages/core/src/index.ts
- client/packages/version/src/version.ts
```ts
const schema = i.schema({
entities: {
todos: i.entity({
text: i.string(),
done: i.boolean(),
createdAt: i.date(),
}),
},
});
type Todo = InstaQLEntity<typeof schema, "todos", {}, undefined, true>;
// Initialize the database
// ---------
const db = init({ appId: APP_ID, schema, useDateObjects: true });
// Subscribe to data
// ---------
db.subscribeQuery({ todos: {} }, (resp) => {
if (resp.error) {
renderError(resp.error.message); // Pro-tip: Check you have the right appId!
return;
}
if (resp.data) {
render(resp.data);
}
});
```
Type of resp.data is 
```typescript
(property) data: {
todos: {
id: string;
text: string;
done: boolean;
createdAt: string | number | Date;
}[];
}
```
it should be
```typescript
(property) data: {
todos: {
id: string;
text: string;
done: boolean;
createdAt: …
```
> fix subscribe query typing with useDates

- client/packages/mcp/src/index.ts
- client/packages/version/src/version.ts
It's very easy to return a lot of data from `get-apps`. We likely don't need the schema and perms but just the app name. Verified this works as expected in the MCP inspector
> Remove schema and perms from get-apps

- client/www/pages/docs/instaql.md
A user pointed out a broken link in the 'reading data' section. Went ahead and fixed it. 
Note: I saw some other places where we use /docs/schema. I will push up a separate PR fixing those -- wanted to action fast on the pertinent feedback.
> [docs] quickfix: broken link in reading data

- client/packages/core/src/schema.ts
- client/sandbox/react-native-expo/instant.schema.ts
- client/sandbox/strong-init-vite/instant.schema.ts
Goes over all the places where we linked to /docs/schema, and link to /docs/modeling-data instead. 
I tried to be a bit more general about the link (rather then linking to subsections), so the links have a higher chance of standing the test of time. 
@dwwoelfel @nezaj @tonsky @drew-harris
> [docs] fix docs/schema

- server/deps.edn
- server/src/instant/reactive/ephemeral.clj
- server/src/tool.clj
Gets properties that hazelcast publishes to jmx and sends them to honeycomb with our gauges.
Adds a dependency on https://github.com/clojure/java.jmx, which provides a nicer interface to jmx info.
> Log info from hazelcast's jmx metrics to gauges

- server/src/instant/db/permissioned_transaction_new.clj
- server/test/instant/db/transaction_test.clj
Report: https://discord.com/channels/1031957483243188235/1407291069015785522
Issue is that we validate reserve names after cascade delete expansion (which is more correct, as we actually check what we are deleting). In the old version we were only checking it before expansion (so technically you can delete from any namespace that is cascade linked to e.g. users)
> Fix delete cascade that goes into system namespaces

- client/packages/core/__tests__/src/queryValidation.test.ts
- client/packages/core/src/queryValidation.ts
- client/packages/version/src/version.ts
Amendment to [previous pr](https://github.com/instantdb/instant/pull/1529) that blocked complex related where clauses from passing validation.
> fix or query complex link

- server/src/instant/db/attr_sketch.clj
- server/src/instant/db/datalog.clj
- server/src/instant/db/hint_testing.clj
- server/src/instant/db/instaql.clj
- server/src/instant/db/rule_where_testing.clj
- server/src/instant/flags.clj
- server/src/instant/util/test.clj
- server/test/instant/db/instaql_test.clj
Adds a new instant-config toggle to enable pg_hint_plan by default, with an instant-config flag to disable hints for individual queries by their hashes.
The testing is looking good and I've already enabled it for the 20 best queries.
Changes in this PR:
1. Enables hints for the lookup subqueries in datalog queries.
When you do a lookup, we do something like:
```sql
where entity_id = (select entity_id from triples where attr_id = :lookup-attr-id and value = :lookup-value)
```
Lookups are unique, so we know that should be an `av_index` lookup. It complicated the `where-clause` function a bit because now it needs to pass pg-hints back up. There are other subqueries that we'll want to add hints to also.
2. Uses hints during tests and adds some helpers to get the sketches during tests, since …
> Enable pg hint plan by default (gated behind a feature flag)

- client/www/pages/docs/storage.md
I noticed LLMs would keep using `upload` instead of `uploadFile` for the storage admin sdk even though `upload` is the deprecated method.
Realized we probably needed to update that section in the docs. Lo and behold!
> [Docs] Tweak storage docs

- client/packages/admin/src/index.ts
- client/packages/core/src/index.ts
- client/packages/version/src/version.ts
- client/sandbox/admin-sdk-express/src/index.ts
As part of stress testing uploads, noticed we don't support uploading streams from the admin sdk but we do support it via API. With this PR the admin SDK can now also upload streams
```typescript
async function testUploadFileStream(
src: string,
dest: string,
contentType?: string,
) {
const fp = path.join(__dirname, src);
const stream = fs.createReadStream(fp);
const fileSize = fs.statSync(fp).size;
const data = await db.storage.uploadFile(dest, stream, {
contentType: contentType,
fileSize,
});
console.log('Uploaded with stream:', data);
}
```
Separately, I noticed after we migrated to `tshy` we changed our package.json for tests to be `module`. This mean using `__dirname` was broken. Fixed that here!
If this looks good will add docs in a follow-on!
> Add support for uploading streams to admin sdk

- client/packages/admin/src/index.ts
- client/packages/version/src/version.ts
- client/sandbox/admin-sdk-express/src/index.ts
- server/src/instant/admin/routes.clj
- server/src/instant/dash/routes.clj
- server/src/instant/storage/coordinator.clj
- server/test/instant/admin/routes_test.clj
One of our users mentioned surprise that uploading as guest would work with the admin sdk. Normally we don't do permission checks for admin usage but we do allow impersonation for queries and transact.
This PR enables impersonation for storage methods too.
```typescript
const scopedDb = db.asUser({ email: 'alyssa_p_hacker@instantdb.com' });
const buffer = fs.readFileSync(path.join(__dirname, src));
// admin storage will run with scoped permissions
const { data } = await scopedDb.storage.uploadFile(dest, buffer, {
contentType: contentType,
});
```
Added some tests for both client and server!
Once this is deployed will follow-up with a PR for docs!
> [Admin] Support impersonation for storage

- server/src/instant/util/tracer.clj
Increases the span attribute limit from 128 to 1900. Honeycomb's API limit is 2000, so this leaves a little headroom for refinery to add attrs. 
This will fix a problem where we're missing some of the attributes for the gauges.
> Increase span attr limit

- client/packages/admin/package.json
- client/packages/admin/src/index.ts
- client/packages/admin/src/subscribe.ts
- client/pnpm-lock.yaml
- client/sandbox/react-nextjs/components/EphemeralAppPage.tsx
- client/sandbox/react-nextjs/pages/play/admin-sdk.tsx
- server/deps.edn
- server/src/instant/admin/routes.clj
- server/src/instant/lib/ring/sse.clj
- server/src/instant/lib/ring/undertow.clj
- server/src/instant/reactive/session.clj
- server/src/instant/reactive/store.clj
- server/src/instant/util/exception.clj
Adds `subscribeQuery` over SSE for the admin SDK.
Only allows a single query per connection. Unlike websockets, the SSE connection is send-only. The client can't send new `add-query` commands through the SSE connection. If we want to multiplex, we will need to have some way to send an `add-query` POST request and have it route to the machine that holds their session (possibly through hazelcast?).
It uses our regular session middleware with a couple of small differences: 
1.`init` and `add-query` are triggered on the backend in `on-open` instead of having the user send `init` and `add-query`.
2. The session has `:sse-conn` instead of `:ws-conn`, then store/send-event dispatches based on which is in the session
```ts
const sub = db.subscribeQuery({goals: {}});
for await (const payload of …
```
> subscribeQuery in the admin SDK

- server/flags-config/instant.schema.ts
- server/src/instant/flags.clj
- server/src/instant/reactive/store.clj
- server/src/instant/util/lang.clj
- server/test/instant/reactive/session_test.clj
We seem to have long pauses (10+ seconds) in reactive store
These seem to be related to high congestion on a lock (see lock_time_ms above)
One thing we can try is ReentrantLock.
On its own, it could be faster. That’s what we will be testing by default.
Another option is to try making it fair. Javadoc (highlight mine):
> When set true, under contention, locks favor granting access to the longest-waiting thread. Otherwise this lock does not guarantee any particular access order. Programs using fair locks accessed by many threads may display lower overall throughput (i.e., are slower; often much slower) than those using the default setting, but have __smaller variances in times to obtain locks__ and __guarantee lack of starvation__.
I made the fairness enabled through a flag, in case we see …
> Try ReentrantLock in reactive store

- server/src/instant/jdbc/wal.clj
- server/src/instant/reactive/aggregator.clj
- server/test/instant/reactive/aggregator_test.clj
When we get a giant transaction from a COPY or an app delete, we collect all of the changes for the transaction in memory and then apply them in the invalidator.
This can cause the jvm to run out of memory and crash. With the invalidator, we'll create a new slot the next time we start up that skips over the giant transaction, so it's self-healing in a way.
The aggregator will keep trying and failing to process the giant transaction.
This PR fixes the problem for the aggregator by ignoring transaction boundaries and just putting the `update`, `delete`, and `insert` records directly into the process channel. It doesn't wait for all of the changes for the transaction and just handles them as they come. This is fine for the aggregator--it doesn't need to care about transactions. We can't do …
> Make aggregator resilient to huge transactions

- server/src/instant/db/attr_sketch.clj
Alternative to https://github.com/instantdb/instant/pull/1579 because aurora won't let us set `auto_explain.log_parameter_max_length`
This will help reduce the amount of postgres logs we produce.
> Don't log bins in auto-explain

- server/src/instant/jdbc/sql.clj
This adds back the `-- trace-id=x, span-id = y` comment for queries that use pg_hint_plan.
It looks like in the original PR I forgot to add in the debug-info.
We can't just put the debug hint at the beginning with pg-hint-plan. In postgres 16, if the hint plan comment isn't the first comment, then the hints won't be applied.
Tested that it works:
```clojure
instant.jdbc.sql> (tool/with-prod-conn [conn]
(tracer/with-span! {:name "test"}
(select conn
(honey.sql/format {:raw "explain analyze"
:select :id
:from :apps
:where [:= :id (random-uuid)]
:pg-hints [[:'SeqScan :apps]]}))))
[{:QUERY PLAN
"Seq Scan on apps  (cost=0.00..318.59 rows=1 width=16) (actual time=2.441..2.442 rows=0 loops=1)"}
{:QUERY PLAN
"  Filter: (id = '58c9ba87-06a4-448c-aa9b-0b00fd21ce96'::uuid)"}
{:QUERY PLAN "  Rows …
```
> Fix trace info for queries using pg_hint_plan

- client/packages/admin/src/subscribe.ts
- client/packages/version/src/version.ts
- server/src/instant/lib/ring/sse.clj
- server/src/instant/reactive/session.clj
Two changes here:
1. If admin-init succeeds, set the retry interval on the connection to 500ms (configurable with an instant-config flag). The default is 3 seconds, which is a bit too long. 
2. Only deliver an error on disconnect if we don't reconnect after 5 seconds.
> Improve reconnect handling for admin subscribe

- server/test/instant/reactive/aggregator_test.clj
I've noticed the aggregator test is timing out occasionally. If the problem is that the test machines are way underpowered, then just updating the time out might help.
Seemed to work on the run for the push.
> Increase timeout for aggregator test

- client/www/pages/docs/permissions.md
- server/src/instant/db/permissioned_transaction_new.clj
- server/test/instant/db/transaction_test.clj
Per @nezaj request, link/unlink now work like this:
- if `link` is not defined for either direction, `update`/`view` fallback is used
- if `link` is defined for one direction, only that `link` permission is checked. The other side is not using `update`/`view` fallback (this is the part that changed)
- if `link` is defined for both directions, both are checked and results are ANDed
Same logic for `unlink`
Second change relates to `delete`. Before, when we were deleting entity and that entity had links, we were checking both `delete` for entity and `unlink` for the other side of the relation. After this PR, we only check `delete`.
Third change is introduction of `$default` for links. If you don’t want to list all attribute names manually, you can use `$default` as attribute name & override …
> Change link unlink fallback

- client/packages/create-instant-app/src/claude.ts
- client/packages/create-instant-app/src/index.ts
- client/packages/version/src/version.ts
Small pr to allow people to set CLAUDE_CODE_PATH environment variable
I tried using the `which` command to find it but that doesn't play nice with claude code sdk. 
Also fixed an issue where ctrl-c kept hiding the cursor.
> custom claude code path + show cursor after ctrl c

- server/src/instant/model/instant_subscription.clj
- server/src/instant/stripe.clj
We were getting an error processing subscriptions because the user_id was a string instead of a uuid. 
I made it a uuid and also cast it to a uuid in the query for good measure.
> Fix subscription error

- server/src/instant/stripe.clj
Followup to https://github.com/instantdb/instant/pull/1614, in tests the metadata already has uuids.
> Fix subscription error (2)

- client/www/components/dash/Orgs.tsx
- client/www/pages/dash/index.tsx
- server/resources/migrations/82_org_subscriptions.down.sql
- server/resources/migrations/82_org_subscriptions.up.sql
- server/src/instant/config.clj
- server/src/instant/dash/routes.clj
- server/src/instant/fixtures.clj
- server/src/instant/model/instant_stripe_customer.clj
- server/src/instant/model/instant_subscription.clj
- server/src/instant/model/org.clj
- server/src/instant/stripe.clj
- server/test/instant/stripe_test.clj
Adds subscriptions for orgs that closely match the structure of subscriptions for apps.
We reuse the same `instant_subscriptions` and `instant_stripe_customers` tables. Each table has a new `org_id` column and a constraint that ensures they have exactly one of `app_id` or `org_id` (sub `user_id` for `app_id` in the stripe_customers table).
We tie the stripe customer to an org instead of a user so that if a user leaves the org, we don't lose billing for the org. I added a billing_email field to the orgs table so that users could set a generic email (e.g. billing@) (no route for updating that yet).
> Subscriptions for orgs

- server/src/instant/dash/ephemeral_app.clj
- server/src/instant/superadmin/routes.clj
Right now when we check for validation-errors on `rules`, we expect the json to have string keys. But the server automatically keywordizes keys. 
In our original endpoint we used `ex/get-param!` with w/stringify-keys to get around this issue. 
I went ahead and updated our remaining endpoints to do the same. 
**Considerations for the future**
This feels a _bit_ brittle. Right now we always have to remember to do three things when getting rules: 1. stringify, 2. validate, 3. save. Maybe we can create one function that does this. I skipped past this for now, as no clean solution came to mind. 
@dwwoelfel @nezaj @tonsky @drew-harris
> [bugfix] w/stringify-keys for rules-code

- client/packages/core/__tests__/src/instaql.test.js
- client/packages/core/src/Reactor.js
- client/packages/core/src/instaql.js
- client/packages/version/src/version.ts
Consider a table `docs` with `title` and `updatedAt`
```js
{ docs: { $: { order: { updatedAt: 'desc' } } } }
```
Say this returns the following docs:
```js
{ id: doc2id, title: Doc 2, updatedAt: 2 }
{ id: doc1id, title: Doc 1, updatedAt: 1 }
```
The `pageInfo` in this case would be: 
```js
{ 'start-cursor': [doc2id, updatedAtAttrId, 2, ts] }
```
We have two problems here: 
Imagine if the user adds `Doc 3, updatedAt: 3`
The user would expect Doc 3 to show up right away. **However, right now Doc3 would get filtered out.** 
Why?
Because `pageInfo` still says `[doc2id, updatedAt, 2]`
And in this case updatedAt: 3 would fall out of bounds for this pageInfo. Look at [isBefore](https://github.com/instantdb/instant/blob/main/client/packages/core/src/instaql.js#L533):
```js
updatedAt 3 > updatedAt …
```
> [order] support optimistic updates for `order: desc`

- client/packages/create-instant-app/template/base/expo/db.ts
- client/packages/version/src/version.ts
Got a report from a user we had an extra `db.ts` in the expo template -- removing it here!
> Remove extra db.ts from expo template

- server/test/instant/dash/routes_test.clj
Currently routes_test is the only test that prints errors to stdout during testing. The problem is that it sends http requests to localhost and http handler is running in a completely different thread group, so it does not inherit e.g. `test/*report-counters*`. I found `*silence-exceptions?*` and that seems to do the trick when used with `with-redefs`
> Hide routes_test exceptions

- server/src/instant/dash/routes.clj
- server/src/instant/db/indexing_jobs.clj
- server/src/instant/fixtures.clj
- server/src/instant/model/org.clj
- server/test/instant/dash/routes_test.clj
- server/test/instant/model/orgs_test.clj
Updates the transfer route to remove members from the app where the user has a matching role on the org.
Returns the removed app members in the body as:
```json
{
"app_member_changes" : {
"removed" : [ {
"member" : {
"id" : "628e83f7-8923-4f3a-b6a8-04f6a9f62543",
"email" : "me@example.com",
"role" : "collaborator"
},
"reason" : "user_is_member_of_org"
} ]
}
}
```
cc @drew-harris
> Remove app members that are already on the org on transfer

- .github/workflows/clojure.yml
Skips the PR runs for clojure tests. 
I'm not sure they're all that useful because we already have the tests run on every push.
> Only run clojure tests on push

- server/resources/migrations/89_creator_or_org_on_app.down.sql
- server/resources/migrations/89_creator_or_org_on_app.up.sql
- server/src/instant/fixtures.clj
- server/test/instant/dash/routes_test.clj
Ensure that apps have either a creator_id or an org_id, but not both.
> Add constraint to app requiring org or creator

- client/packages/create-instant-app/template/base/expo/babel.config.js
- client/packages/create-instant-app/template/base/expo/package.json
- client/packages/version/src/version.ts
Adds missing dependency and babel config for create-instant-apps with expo
Right now if you use `create-instant-app` with expo you'll get some errors when running the app on ios.
First we'll get a missing dependency error
And then you'll get a babel error
> Fix create-instant-app for expo

- client/packages/core/__tests__/src/instaql.test.js
- client/packages/core/src/store.js
Reported by Kosmik https://discord.com/channels/1031957483243188235/1417133699094548601
Core of the issue is strict update mode on the client was filtering out triples if entity existed but triple with previous value didn't. Observed result was that in case like this
```
db.transact(
db.tx.stickers[id].create({ v: 0 });
);
db.transact(
db.tx.stickers[id].update({ v: 1, resizable: true });
);
```
after second transact you were getting query results with `{ v: 1 }` but without `resizable`
> Fix optimistic update for entity that exists but triple with attr does not

- client/www/components/dash/PersonalAccessTokensScreen.tsx
after:
before:
adds an empty state to the personal access tokens screen
> personal access tokens empty state

- client/www/components/dash/explorer/Explorer.tsx
before:
after:
cleans up border radius and padding for things in the explorer (especially file view) to make things more consistent .
> explorer style changes

- client/www/components/dash/ProfilePanel.tsx
- client/www/pages/dash/index.tsx
- server/src/instant/dash/routes.clj
If you go directly to an org's `app` and it's not in the apps from the dash response, we'll find the org that the app belongs to and redirect to the app with the org.
Test plan:
1. Go to the url for an app in an org, copy the url and make sure to remove any `org` param.
2. Go to your personal account and click on an app. 
3. Paste in the url you copied and make sure that it landed on the same app from step 1
cc @drew-harris
> Redirect to org if the app is in another org

- client/pnpm-lock.yaml
- client/www/components/ui.tsx
- client/www/lib/muxVideos.ts
- client/www/package.json
- client/www/tsconfig.json
We sometimes noticed a `TypeError: j.default.getLevel is not a function` in prod. 
I _think_ it's related to mux. I wasn't able to figure out how to repro this. But I thought, let's go ahead and update Mux -- maybe they fixed the bug, we are 1 major version behind. 
I also updated our `moduleResolution` to `bundler`, so typescript 5.0 can look up the types that come packages with the newer mux library. 
@dwwoelfel @nezaj @drew-harris @tonsky
> [experiment] update mux

- client/packages/cli/src/index.js
- client/packages/version/src/version.ts
- client/www/pages/dash/index.tsx
When you do `create-app`, it will ask you which org to pull from (if you have orgs). 
For pull, it will ask you which org to check if you want to import an app.
Demo: https://asciinema.org/a/q0p1jbTA4s8CEzOYpZu420FB6
Also fixes a bug in the dashboard where it can't find an app if you go to the direct url after being in an org.
> Make cli aware of orgs

- server/src/instant/model/app_user_magic_code.clj
- server/src/instant/runtime/magic_code_auth.clj
- server/src/instant/system_catalog.clj
Prerequisite for #1730
Adds and fills $magicCodes.email, but doesn't use them yet. After a 24h has passed, it’ll be safe to deploy #1730
> Postpone user creation during magic code auth (part 1)

- server/resources/migrations/90_add_e_to_ave_index.down.sql
- server/resources/migrations/90_add_e_to_ave_index.up.sql
- server/src/instant/db/datalog.clj
Now that we're using pg_hint_plan, we can slowly roll out changes to the underlying indexes.
This adds the entity_id back to the `ave_index`. There are a lot of queries where we use the primary key instead of the ave_index because it makes the join more efficient. With the `entity_id` in the ave index, it makes it much more efficient.
We initially removed it in https://github.com/instantdb/instant/pull/622.
It's behind a feature flag toggle at `ave-with-e-index`
Deploy plan:
Later (if this goes well)
> Experiment with adding back `e` to the ave_index

- client/packages/create-instant-app/src/login.ts
- client/packages/version/src/version.ts
Following up from https://github.com/instantdb/instant/pull/1732, this adds support for creating/importing apps with orgs.
If you don't have orgs this extra prompt will be skipped.
- If you have orgs, prompts: "Would you like to create the app in an organization?"
- Shows list of orgs (plus "No organization" option)
- Creates app in selected org
- If you have orgs, prompts: "Would you like to import an app from an organization?"
- Shows list of orgs (plus "No organization" option)
- Fetches and displays apps from selected org
- Imports the selected app
- Added `fetchDashboard` to get both apps and orgs in one call
- Added `fetchOrganizationApps` to get apps from a specific org
- Filters out orgs where user only has `app-member` role (can't create apps there)
- Updated `createApp` to …
> Support orgs in create-instant-app

- client/www/lib/intern/docs-feedback/db.ts
Report: https://discord.com/channels/1031957483243188235/1421850181908824094
How it looks:
Current solution is to go to `client/www` and copy `.env.example` to `.env`. It doesn’t seem to care if app exists or not
I experienced this myself once or twice after resetting the project. Very cryptic error and honestly we shouldn’t really care if feedback app is configured for running locally
> Don't show error if feedback app is not configured

- server/src/instant/fixtures.clj
- server/src/instant/stripe.clj
- server/test/instant/dash/routes_test.clj
The stripe test was failing because it expected a refund, but since the subscription was started so close to the end of the month, there was no refund.
This changes the subscription not to anchor to the first of the month for the failing test. Then we'll always get a refund when we transfer the app to an org.
> Fix stripe test

- client/packages/admin/src/index.ts
- client/packages/version/src/version.ts
- client/sandbox/react-nextjs/pages/play/optional-admin-token.tsx
- server/src/instant/admin/routes.clj
- server/test/instant/admin/routes_test.clj
**Problem**
Right now, you need to provide an `adminToken` to use `@instantdb/admin`
**But, there are cases where you don’t really need it:** 
1. If you provide a user token with asUser({ token: '...' });
2. If you say you want to run a query as a guest asUser( { guest: true }); 
**Solution**
1. We now make `adminToken` optional in `init`
2. If you explicitly use `asUser({ token })` or `asUser({ guest: true })`, queries and transacts will work. Otherwise, they will fail. 
Got claude to help write tests in admin, and made a little sandbox app too:
> [admin] allow omitting admin token

- client/packages/cli/src/index.js
- client/packages/version/src/version.ts
I realized we didn't mention that we also set INSTANT_ADMIN_TOKEN. Updated the text to say that: 
@dwwoelfel @nezaj @tonsky @drew-harris
> [easy] add INSTANT_ADMIN_TOKEN to the note in cli

- .github/workflows/clojure.yml
- server/src/instant/db/datalog.clj
Adds a new cost function for determining the best index. It's behind a feature flag so that we can quickly roll back if it causes issues.
The old cost function treated `[e v]` as equivalent to `[v e]`, but if you have fewer `e`, then it's much better to start with the `e` first because the `e` is unique. You know that there only be at most one v per e. The `v` might point to many different `e`s. 
Still a long way to go to create a better model of the work the database will actually do, but this brings us a little closer.
> Better cost function for choosing datalog index

- server/src/instant/db/model/triple.clj
- server/test/instant/db/model/triple_test.clj
Updates the date-time parsers to allow single digit month values, e.g. `2025-9-29T23:59:59.999Z`
> Allow single-digit month in triple dates

- server/src/instant/model/app_oauth_code.clj
- server/src/instant/runtime/routes.clj
- server/src/instant/system_catalog.clj
- server/src/instant/system_catalog_ops.clj
Pre-requisite for #1750
We want to postpone user creation from `/oauth/callback` to `/oauth/token`. To do that, we need to store `$oauthClient` and `$authCode` in `$oauthCodes` and wait for all in-flight requests to expire (10-60 minutes)
Needs to be deployed before #1750
> Add client-id and auth-code to $oauthCodes

- .github/workflows/clojure.yml
- server/dev-postgres/Makefile
- server/dev-postgres/README.md
- server/docker-compose-dev.yml
We get occasional rate-limit errors when we pull the image from amazon's container registry. It doesn't fail the build, because we retry and start again, but it slows it down.
With this change, we'll push the image to the github container registry, which seems to be a bit faster.
It's also nice that we can have multiple package names--with the amazon registry, everything went into the `instantdb` package, and we just had to give it different tags.
> Publish our postgres image to github's container registry

- client/www/lib/swrCache.ts
I sloppily called it 'something-cache' for whatever reason during the org ui process. Let me know if i should write something to maybe migrate the key and transfer instead of just moving to this and leaving the old one.
> rename swr cache to descriptive key in localstorage

- client/packages/cli/src/index.js
- client/packages/version/src/version.ts
I noticed we had a bug with the following flow:
* `pnpx create-instant-app -b expo`
* Create a new project, no rules, create a new app
* cd into it
* `pnpx instant-cli pull` and/or `pnpx instant-cli push`
Would result in `Error: ParseError: Unexpected keyword 'typeof'`
The issue was `create-instant-app` would generate and import with single quotes which our `transform` didn't capture. This will now match on both single and double quotes
> Fix push and pull for react native

- client/packages/cli/src/index.js
- client/packages/version/src/version.ts
We got an email from a user who was confused about a deprecation warning with our cli.
He meant to run `pnpx instant-cli push perms` but instead did `pnpx instant-cli push perm` (no plural). If you do the later right now you get the following error.
```
[warning] `instant-cli push perm` is deprecated. Use `instant-cli push --app perm` instead.
```
This is because we previously allowed folks to do `instant-cli push <APP_ID>`, but since Nov 2024 we changed it to `instant-cli push --app <APP_ID>`.
It's been long enough that we can probably remove this deprecation warning.
With this PR, if you use an incorrect command like `instant-cli push perm` or `instant-cli pull perm` You'll get the following error instead
```
[error] perm is not valid. Must be one of schema, perms, all
```
> [CLI] Fix invalid args for push and pull

- server/src/instant/system_catalog.clj
- server/src/instant/system_catalog_migration.clj
- server/test/instant/db/transaction_test.clj
Had the on-delete direction reversed. It should delete the guest users when you delete the primary user, but it shouldn't delete the primary user if you delete the guest user.
Already updated the attr in production. Includes a test.
> Fix on delete direction for linked guest users

- server/src/instant/db/datalog.clj
Now that the ave_with_e_index has been in production for a while, we can start the process to remove the `ave_index`. 
It will take two steps.
1. Stop using the index. That's this PR. It adds a flag to stop using the ave_index.
2. Run a migration to drop the ave_index from the db. That will be in a new PR if everything goes fine with this one.
> Remove ave_index (part 1 of 2)

- client/www/lib/schema.tsx
- server/flags-config/instant.schema.ts
- server/flags-config/package.json
- server/flags-config/pnpm-lock.yaml
Now that we have docs for guest users, I think it's safe to show them in the explorer.
Also updates our server flags:
1. Updates to the latest versions
2. pulled the schema
> Show the guest fields on $users in the explorer

- server/src/instant/admin/routes.clj
- server/src/instant/util/exception.clj
If you pass a malformed token right now, you'll get a `Something went wrong. Please ping `debug-uri` in #bug-and-questions, and we'll take a look. Sorry about this!` error.
This makes it a normal `param-malformed` error:
> Better error for invalid asUser token in admin api

- client/www/components/ui.tsx
Not sure why it keeps disappearing but might be something to do with the use of opacity? Setting it to a solid color this time
BEFORE:
AFTER:
> fix the sidebar again

- server/src/instant/db/attr_sketch.clj
- server/src/instant/db/datalog.clj
We fixed `isNull` on unindexed fields in https://github.com/instantdb/instant/pull/1745, but it was still returning 0 when the attr didn't have a sketch in the db (which can happen if you're never stored a triple for the attr).
Now we default to an empty sketch instead of just returning 0. That lets our logic for determining the count work.
> Fix nil? sketch check when nil attr has no sketch

- server/resources/migrations/91_drop_ave_index.down.sql
- server/resources/migrations/91_drop_ave_index.up.sql
- server/src/instant/db/datalog.clj
- server/test/instant/db/instaql_test.clj
Follow up to https://github.com/instantdb/instant/pull/1782, drops the ave_index from the database.
1. Merge PR
1. Run `drop index concurrently ave_index;`
2. Run the migration
3. Deploy the code change
> Drop ave_index migration

- client/www/components/docs/CopyPromptBox.tsx
- client/www/markdoc/tags.js
- client/www/pages/docs/index.md
- client/www/pages/docs/start-rn.md
- client/www/pages/docs/start-vanilla.md
We've been hearing asks to make it easier to copy docs for folks using agents. Following [Clerk's example](https://clerk.com/docs/nextjs/getting-started/quickstart), this PR adds a box for letting people copy the getting started docs via one click.
> Add prompt boxes

- client/packages/core/src/utils/PersistedObject.js
- client/packages/version/src/version.ts
Adds a try/catch when we fetch data from the store. This will prevent an error in the store from completely blocking an app from working.
Prerequisite for https://github.com/instantdb/instant/pull/1793, so that users can roll back to this version if there is something wrong with that version.
> Add error handling to the persister

- client/packages/core/src/IndexedDBStorage.ts
- client/packages/core/src/Reactor.js
- client/packages/core/src/index.ts
- client/packages/core/src/utils/PersistedObject.ts
- client/packages/react-native/src/Storage.native.js
- client/packages/version/src/version.ts
- client/sandbox/react-native-expo/app/play/colors.tsx
Two changes in behavior:
1. We use `requestIdleCallback` to wait for things to simmer down before we persist to storage. We'll wait up to 1 second.
2. We store things directly as objects into indexeddb instead of serializing to JSON.
Also converted IndexedDBStorage and PersistedObject to typescript.
There's special handling for React native
> Store objects in indexeddb, wait for requestIdleCallback

- server/src/instant/db/instaql.clj
- server/test/instant/db/instaql_test.clj
Fixes a bug where we were trying to encode the clojure function `first` instead of the field "first". Includes a test!
> Fix error message for first

- server/src/instant/reactive/query.clj
- server/src/instant/reactive/session.clj
- server/src/instant/reactive/store.clj
- server/test/instant/reactive/session_test.clj
This fixes hasOne links in admin subscribe query. We weren't propagating the `inference?` field, so we were always returning an array.
> Pass through inference? for admin subscribe query

- client/www/components/docs/CopyPromptBox.tsx
Noticed the prompt box looked a little off on mobile and wanted to fix it
**Before**
**After**
> Fix prompt box mobile styles
